const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={csrf:'',posts:[],current:null,filter:'all',authenticated:false};
const els={login:$('#loginView'),app:$('#appView'),loginForm:$('#loginForm'),password:$('#password'),loginError:$('#loginError'),postList:$('#postList'),repoStatus:$('#repoStatus'),newBtn:$('#newBtn'),logout:$('#logoutBtn'),editing:$('#editingLabel'),lang:$('#lang'),date:$('#date'),title:$('#title'),category:$('#category'),slug:$('#slug'),description:$('#description'),translationKey:$('#translationKey'),body:$('#body'),descCount:$('#descCount'),wordCount:$('#wordCount'),preview:$('#preview'),previewBadge:$('#previewBadge'),status:$('#status'),saveDraft:$('#saveDraftBtn'),publish:$('#publishBtn'),del:$('#deleteBtn'),live:$('#liveLink')};

function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function slugify(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,90);}
function inline(s=''){let x=esc(s);x=x.replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+|\/[^\s)]*)\)/g,'<a href="$2" target="_blank" rel="noreferrer">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/(^|[^*])\*([^*]+)\*/g,'$1<em>$2</em>');return x;}
function markdown(md=''){const lines=String(md).replace(/\r\n/g,'\n').split('\n'),out=[];let para=[],list=null,code=false,codeLines=[];const fp=()=>{if(para.length){out.push(`<p>${inline(para.join(' '))}</p>`);para=[]}};const fl=()=>{if(list){out.push(`<${list.t}>${list.a.map(v=>`<li>${inline(v)}</li>`).join('')}</${list.t}>`);list=null}};const fc=()=>{if(code){out.push(`<pre><code>${esc(codeLines.join('\n'))}</code></pre>`);code=false;codeLines=[]}};for(const line of lines){if(line.startsWith('```')){fp();fl();if(code)fc();else code=true;continue}if(code){codeLines.push(line);continue}const h=line.match(/^(#{1,3})\s+(.+)/);if(h){fp();fl();out.push(`<h${h[1].length}>${inline(h[2])}</h${h[1].length}>`);continue}if(/^>\s?/.test(line)){fp();fl();out.push(`<blockquote>${inline(line.replace(/^>\s?/,''))}</blockquote>`);continue}const ul=line.match(/^[-*]\s+(.+)/);const ol=line.match(/^\d+\.\s+(.+)/);if(ul||ol){fp();const t=ul?'ul':'ol';if(!list||list.t!==t){fl();list={t,a:[]}}list.a.push((ul||ol)[1]);continue}if(/^---+$/.test(line.trim())){fp();fl();out.push('<hr>');continue}if(!line.trim()){fp();fl();continue}para.push(line.trim())}fp();fl();fc();return out.join('');}

async function api(url,opts={}){const headers={'Content-Type':'application/json',...(opts.headers||{})};if(state.csrf&&opts.method&&opts.method!=='GET')headers['X-CSRF-Token']=state.csrf;const r=await fetch(url,{credentials:'same-origin',...opts,headers});const data=await r.json().catch(()=>({ok:false,message:`HTTP ${r.status}`}));if(!r.ok||data.ok===false)throw Object.assign(new Error(data.message||data.error||`HTTP ${r.status}`),{data,status:r.status});return data;}
function setStatus(text,type=''){els.status.textContent=text;els.status.className=`status ${type}`;}
function emptyPost(){return{lang:'fi',date:new Date().toISOString().slice(0,10),title:'',category:'field',description:'',slug:'',translationKey:'',draft:true,body:'',path:'',sha:''};}
function currentForm(draft){return{lang:els.lang.value,date:els.date.value,title:els.title.value.trim(),category:els.category.value,description:els.description.value.trim(),slug:els.slug.value.trim()||slugify(els.title.value),translationKey:els.translationKey.value.trim()||slugify(els.slug.value||els.title.value),draft,body:els.body.value};}
function loadForm(p){state.current=p;els.lang.disabled=Boolean(p.path);els.lang.value=p.lang||'fi';els.date.value=p.date||new Date().toISOString().slice(0,10);els.title.value=p.title||'';els.category.value=p.category||'field';els.description.value=p.description||'';els.slug.value=p.slug||'';els.translationKey.value=p.translationKey||'';els.body.value=p.body||'';els.editing.textContent=p.path?(p.title||p.path):'Uusi lähetys';els.del.hidden=!p.path;renderLiveLink();refreshPreview();renderList();setStatus('');}
function renderList(){const posts=state.posts.filter(p=>state.filter==='all'||(state.filter==='draft'?p.draft:!p.draft));els.postList.innerHTML=posts.map(p=>`<button class="post-item ${state.current?.path===p.path?'active':''}" data-path="${esc(p.path)}"><strong>${esc(p.title||p.path)}</strong><span>${String(p.lang||'').toUpperCase()} · ${esc(p.category||'')} · ${esc(p.date||'')} ${p.draft?'· LUONNOS':'· JULKAISTU'}</span></button>`).join('')||'<p class="muted">Ei julkaisuja tässä näkymässä.</p>';$$('.post-item').forEach(b=>b.onclick=()=>{const p=state.posts.find(x=>x.path===b.dataset.path);if(p)loadForm(p)});}
function renderLiveLink(){const p=currentForm(Boolean(state.current?.draft));const slug=p.slug||slugify(p.title);if(!state.current?.path||state.current?.draft||!slug){els.live.hidden=true;return}els.live.href=`${p.lang==='en'?'/dispatches':'/lahetykset'}/${slug}`;els.live.hidden=false;}
function refreshPreview(){const p=currentForm(Boolean(state.current?.draft));const words=p.body.trim()?p.body.trim().split(/\s+/).length:0;els.wordCount.textContent=`${words} sanaa · ${Math.max(1,Math.ceil(words/220))} min`;els.descCount.textContent=`${p.description.length} / 220`;els.previewBadge.textContent=state.current?.draft===false?'JULKAISTU':'LUONNOS';els.preview.innerHTML=`<p class="kicker">${esc(p.category)}</p><h1>${esc(p.title||'Otsikko')}</h1><p class="muted">${esc(p.date||'')}</p>${markdown(p.body||'')}`;renderLiveLink();}
async function session(){const d=await api('/api/admin/session',{method:'GET'});state.authenticated=d.authenticated;state.csrf=d.csrf||'';els.login.hidden=state.authenticated;els.app.hidden=!state.authenticated;if(state.authenticated){els.repoStatus.textContent=d.github?.configured?`${d.github.repo} · ${d.github.branch}`:'GitHub-yhteys ei ole vielä konfiguroitu';els.repoStatus.className=`repo-status ${d.github?.configured?'ok':''}`;if(d.github?.configured){try{const st=await api('/api/admin/status',{method:'GET'});if(st.github?.fullName){els.repoStatus.textContent=`✓ ${st.github.fullName} · ${st.github.branch}${st.github.private?' · private':''}`;els.repoStatus.className='repo-status ok';}}catch(e){els.repoStatus.textContent=`GitHub-yhteys: ${e.message}`;els.repoStatus.className='repo-status';}}await loadPosts();}}
async function loadPosts(){try{const d=await api('/api/admin/posts',{method:'GET'});state.posts=d.posts||[];renderList();if(state.current?.path){const fresh=state.posts.find(p=>p.path===state.current.path);if(fresh)loadForm(fresh);else loadForm(emptyPost());}}catch(e){els.repoStatus.textContent=e.message;els.repoStatus.className='repo-status';}}
async function save(draft){try{setStatus(draft?'Tallennetaan luonnosta…':'Julkaistaan…');const post=currentForm(draft);const d=await api('/api/admin/posts',{method:'POST',body:JSON.stringify({path:state.current?.path||'',sha:state.current?.sha||'',post})});setStatus(draft?'✓ Luonnos tallennettu GitHubiin.':'✓ Julkaisucommitti tehty. Git-yhdistetty Vercel rakentaa sivun seuraavaksi.','ok');await loadPosts();const fresh=state.posts.find(p=>p.path===d.path);if(fresh)loadForm(fresh);}catch(e){setStatus(`✗ ${e.message}`,'err');}}
async function remove(){if(!state.current?.path||!confirm(`Poistetaanko “${state.current.title}”? Tämä tekee poistocommitin GitHubiin.`))return;try{setStatus('Poistetaan…');await api('/api/admin/posts',{method:'DELETE',body:JSON.stringify({path:state.current.path,sha:state.current.sha})});state.current=null;await loadPosts();loadForm(emptyPost());setStatus('✓ Poistettu GitHubista.','ok');}catch(e){setStatus(`✗ ${e.message}`,'err');}}

els.loginForm.onsubmit=async e=>{e.preventDefault();els.loginError.textContent='';try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:els.password.value})});els.password.value='';await session();}catch(e){els.loginError.textContent=e.message||'Kirjautuminen epäonnistui.'}};
els.logout.onclick=async()=>{try{await api('/api/admin/logout',{method:'POST',body:'{}'});}catch{}state.csrf='';state.authenticated=false;els.app.hidden=true;els.login.hidden=false;};
els.newBtn.onclick=()=>loadForm(emptyPost());els.saveDraft.onclick=()=>save(true);els.publish.onclick=()=>save(false);els.del.onclick=remove;
$$('.filters button').forEach(b=>b.onclick=()=>{$$('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderList()});
[els.lang,els.date,els.title,els.category,els.slug,els.description,els.translationKey,els.body].forEach(el=>el.addEventListener('input',refreshPreview));els.title.addEventListener('blur',()=>{if(!els.slug.value)els.slug.value=slugify(els.title.value);if(!els.translationKey.value)els.translationKey.value=slugify(els.title.value);refreshPreview()});
loadForm(emptyPost());session().catch(e=>{els.login.hidden=false;els.loginError.textContent=e.message});
