const q=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let workspace=null,template=null,constitution=null,project=null,revision=0,csrf='',active='project',baseline='',loading=false,runs=[],lastRemoved=null;
const RUN_STATUS_LABELS={queued:'Jonossa',running:'Käynnissä',paused:'Tauolla',completed:'Valmis',error:'Virhe',failed:'Virhe',cancelled:'Peruttu',canceled:'Peruttu',unknown:'Tuntematon'};
const KIND_LABELS={form:'Lomake',collection:'Kokoelma','run-explorer':'Ajohistoria'};
function isMancer(){return template?.mancerPackage?.format==='anomancer-mancer-package/v1';}
function headers(extra={}){return{...extra,'X-Anomancer-Workspace':workspace?.id||'default'};}
async function ensureCsrf(){if(csrf)return csrf;const r=await fetch('/api/admin/auth?resource=session',{credentials:'same-origin'}),d=await r.json().catch(()=>({}));if(!r.ok||!d.authenticated)throw new Error('Admin-istunto puuttuu.');csrf=d.csrf||'';return csrf;}
function sections(){return Array.isArray(template?.editorDefinition?.sections)?template.editorDefinition.sections:[];}
function section(){return sections().find(x=>x.id===active)||sections()[0]||null;}
function getPath(obj,path=''){return String(path).split('.').filter(Boolean).reduce((v,k)=>v&&typeof v==='object'?v[k]:undefined,obj);}
function setPath(obj,path='',value){const parts=String(path).split('.').filter(Boolean);if(!parts.length)return;let cur=obj;for(const k of parts.slice(0,-1)){if(!cur[k]||typeof cur[k]!=='object'||Array.isArray(cur[k]))cur[k]={};cur=cur[k];}cur[parts.at(-1)]=value;}
function uid(prefix='item'){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;}
function status(text,tone=''){const el=q('#mancerStatus');if(el){el.textContent=text;el.dataset.tone=tone;}}
function dirty(){return project!==null&&JSON.stringify(project)!==baseline;}
function renderSaveState(){const changed=dirty(),btn=q('#mancerSave'),dirtyEl=q('#mancerDirty'),globalSave=q('#workspaceSaveIndicator');if(btn){btn.textContent=changed?'Tallenna':'Tallennettu';btn.disabled=!changed||loading;}if(dirtyEl){dirtyEl.textContent=changed?'TALLENTAMATON':'TALLENNETTU';dirtyEl.dataset.dirty=changed?'true':'false';}if(globalSave&&isMancer()){globalSave.textContent=loading?'LADATAAN':changed?'TALLENTAMATON':'TALLENNETTU';globalSave.dataset.dirty=changed?'true':'false';}refreshDocumentTitle();}
function fieldInput(field,value,path,index=null){const attrs=`data-mancer-path="${esc(path)}"${index!==null?` data-mancer-index="${index}"`:''}`;const mono=field.monospace?' mancer-monospace':'';if(field.type==='textarea')return`<textarea ${attrs} class="${mono.trim()}" rows="${Number(field.rows)||6}" maxlength="${Number(field.maxLength)||200000}">${esc(value||'')}</textarea>`;if(field.type==='select')return`<select ${attrs}>${(field.options||[]).map(o=>`<option value="${esc(o.value)}"${String(value??'')===String(o.value)?' selected':''}>${esc(o.label||o.value)}</option>`).join('')}</select>`;return`<input ${attrs} class="${mono.trim()}" type="text" value="${esc(value||'')}" maxlength="${Number(field.maxLength)||200000}">`;}
function renderForm(s){return`<div class="mancer-form">${(s.fields||[]).map(field=>`<label><span>${esc(field.label||field.path)}</span>${fieldInput(field,getPath(project,field.path),field.path)}</label>`).join('')}</div>`;}
function removedLabel(item={},s={}){return item.title||item.name||item.path||s.itemLabel||'Kohde';}
function undoBanner(){if(!lastRemoved||lastRemoved.sectionId!==active)return'';return`<div class="mancer-undo" role="status"><span><strong>${esc(lastRemoved.label)}</strong> poistettiin luonnoksesta. Muutosta ei ole vielä tallennettu.</span><button class="ghost" type="button" data-mancer-undo>Kumoa poisto</button></div>`;}
function renderCollection(s){const items=Array.isArray(project?.[s.id])?project[s.id]:[];return`${undoBanner()}<div class="mancer-collection-head"><span>${items.length} ${items.length===1?'kohde':'kohdetta'}</span><button class="secondary" type="button" data-mancer-add="${esc(s.id)}">+ ${esc(s.itemLabel||'Kohde')}</button></div><div class="mancer-collection">${items.length?items.map((item,index)=>`<article class="mancer-item"><header><strong>${esc(item.title||item.name||item.path||`${s.itemLabel||'Kohde'} ${index+1}`)}</strong><button class="ghost mancer-remove" type="button" data-mancer-remove="${esc(s.id)}" data-mancer-index="${index}">Poista luonnoksesta</button></header><div class="mancer-form">${(s.fields||[]).map(field=>`<label><span>${esc(field.label||field.path)}</span>${fieldInput({...field,monospace:field.path===s.monospaceField},item?.[field.path],field.path,index)}</label>`).join('')}</div></article>`).join(''):`<div class="mancer-empty"><strong>Tyhjä näkymä</strong><p>${esc(s.emptyMessage||'Ei kohteita vielä. Lisää ensimmäinen rakenneobjekti.')}</p></div>`}</div>`;}
function runTone(run){return run?.status==='completed'?'ok':['error','failed'].includes(run?.status)?'error':'';}
function runStatus(statusValue){return RUN_STATUS_LABELS[String(statusValue||'unknown').toLowerCase()]||String(statusValue||'Tuntematon');}
function renderRuns(){return`<div class="mancer-run-toolbar"><button class="secondary" type="button" data-mancer-runs-refresh>Päivitä ajot</button><button class="ghost" type="button" data-mancer-machine>Avaa Konehuone</button></div><div class="mancer-runs">${runs.length?runs.map(run=>`<article data-tone="${runTone(run)}"><span>${esc(run.orchestra?.name||run.orchestraId||'Ajo')}</span><strong>${esc(runStatus(run.status))}</strong><small>${esc(run.id||run.orchestraRunId||'')} · ${esc(run.finishedAt||run.startedAt||'')}</small></article>`).join(''):'<div class="mancer-empty"><strong>Ei ajohistoriaa</strong><p>Tässä työtilassa ei ole vielä orkesteri- tai agenttiajoja.</p></div>'}</div>`;}
function contractDetails(){const p=template?.mancerPackage||{},approval=p.approvalModel||{},orchestras=p.orchestraRegistry?.orchestras||[];return`<section class="mancer-authority-note" aria-label="Työtilan toimivaltaraja"><div><strong>Ihminen hyväksyy soveltamisen ja julkaisun.</strong><span>Työtila tallentaa omaan artefaktisäilöön eikä kirjoita koodivarastoon automaattisesti.</span></div><details class="mancer-contract-details"><summary>Sopimuksen tekniset tiedot</summary><div class="mancer-contract-strip"><div><span>Mancer-paketti</span><strong>${esc(p.id||'mancer')} ${esc(p.version||'')}</strong></div><div><span>Hyväksyntämalli</span><strong>${approval.humanFinalAuthority?'Ihmisellä lopullinen päätösvalta':'Ei määritelty'}</strong></div><div><span>Orkesterirekisteri</span><strong>${orchestras.length} määritelty</strong></div><div><span>Arkistopolitiikka</span><strong>${p.archivePolicy?.automaticModelMemory===false?'Ei automaattista mallimuistia':'Ei määritelty'}</strong></div></div></details></section>`;}
function sectionNotice(s){return s.notice?`<div class="mancer-section-notice" data-tone="${esc(s.noticeTone||'')}"><strong>Toimivaltaraja</strong><span>${esc(s.notice)}</span></div>`:'';}
function renderPanel(){const root=q('#mancerPanel'),s=section();if(!root||!s)return;root.innerHTML=`<header class="mancer-section-head"><div><p class="kicker">${esc(template?.name||'MANCER')} / ${esc(s.label||s.id)}</p><h2>${esc(s.label||s.id)}</h2><p>${esc(s.description||'')}</p></div><span class="mancer-section-kind">${esc(KIND_LABELS[s.kind]||'Työtila')}</span></header>${sectionNotice(s)}${contractDetails()}${s.kind==='collection'?renderCollection(s):s.kind==='run-explorer'?renderRuns():renderForm(s)}`;renderSaveState();}
function renderShell(){if(!isMancer())return;const root=q('#mancerWorkspace');if(root)root.hidden=false;q('#mancerWorkspaceName').textContent=workspace?.name||template?.name||'Mancer';q('#mancerPackageName').textContent=`TYÖMAAILMA / ${template?.name||'Mancer'}`;q('#mancerConstitution').textContent=constitution?.name||'Sopimus + ihmisen hyväksyntä';if(!sections().some(s=>s.id===active))active=sections()[0]?.id||'project';renderPanel();}
async function loadRuns(){if(!isMancer())return;runs=[];try{const r=await fetch('/api/admin/core?resource=runs&limit=12',{credentials:'same-origin',headers:headers()}),d=await r.json().catch(()=>({}));if(r.ok&&d.ok)runs=d.runs||d.items||[];}catch{}if(section()?.kind==='run-explorer')renderPanel();}
async function loadArtifact(){if(!isMancer()||loading)return;loading=true;status('Ladataan työtilan aineistoa…');try{const r=await fetch('/api/admin/content?resource=mancer-artifact',{credentials:'same-origin',headers:headers()}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.message||d.error||'Työtilan aineistoa ei voitu ladata.');project=d.state?.data||{};revision=Number(d.state?.revision||0);baseline=JSON.stringify(project);lastRemoved=null;renderShell();await loadRuns();status(`Työtilan aineisto ladattu · revisio ${revision}${d.store?.durable?' · pysyvä säilö':' · palvelinmuisti'}`,'ok');}catch(error){project={};baseline=JSON.stringify(project);renderShell();status(`Työtilan aineisto: ${error.message}`,'error');}finally{loading=false;renderSaveState();}}
async function save(){if(!isMancer()||!project||loading||!dirty())return;loading=true;try{await ensureCsrf();status('Tallennetaan työtilan aineistoa…');const r=await fetch('/api/admin/content?resource=mancer-artifact',{method:'POST',credentials:'same-origin',headers:headers({'Content-Type':'application/json','X-CSRF-Token':csrf}),body:JSON.stringify({data:project,expectedRevision:revision})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){if(r.status===403)csrf='';throw Object.assign(new Error(d.message||d.error||'Tallennus epäonnistui.'),{code:d.error});}project=d.state?.data||project;revision=Number(d.state?.revision||revision+1);baseline=JSON.stringify(project);lastRemoved=null;status(`Tallennettu · revisio ${revision} · koodivarastoa ei muutettu`,'ok');}catch(error){status(error.message,'error');if(error.code==='MANCER_ARTIFACT_REVISION_CONFLICT')await loadArtifact();}finally{loading=false;renderPanel();}}
function selectSection(id){if(!isMancer()||!sections().some(s=>s.id===id))return false;active=id;renderPanel();if(section()?.kind==='run-explorer')loadRuns();window.dispatchEvent(new CustomEvent('anomancer:mancer-section-change',{detail:{section:id}}));refreshDocumentTitle();return true;}
function refreshDocumentTitle(){if(!isMancer())return;const s=section();document.title=`${dirty()?'● ':''}Anomancer Core · ${workspace?.name||template?.name||'Mancer'} · ${s?.label||''}`;}
function applyWorkspace(detail){const next=detail||window.anomancerWorkspaces?.getDetail?.()||{};workspace=next.workspace||null;template=next.template||null;constitution=next.constitution||null;const root=q('#mancerWorkspace');if(!isMancer()){if(root)root.hidden=true;project=null;baseline='';lastRemoved=null;return;}active=template.editorDefinition?.sections?.[0]?.id||'project';loadArtifact();}
q('#mancerSave')?.addEventListener('click',save);
q('#mancerPanel')?.addEventListener('input',event=>{const el=event.target.closest?.('[data-mancer-path]');if(!el||!project)return;const index=el.dataset.mancerIndex,path=el.dataset.mancerPath;if(index!==undefined){const arr=project[active];if(Array.isArray(arr)&&arr[Number(index)])arr[Number(index)][path]=el.value;}else setPath(project,path,el.value);renderSaveState();});
q('#mancerPanel')?.addEventListener('change',event=>{if(event.target.matches?.('[data-mancer-path]'))renderSaveState();});
q('#mancerPanel')?.addEventListener('click',event=>{const add=event.target.closest?.('[data-mancer-add]');if(add){const s=sections().find(x=>x.id===add.dataset.mancerAdd);if(!s)return;if(!Array.isArray(project[s.id]))project[s.id]=[];const item={id:uid(s.id)};for(const f of s.fields||[])item[f.path]=f.type==='select'?(f.options?.[0]?.value||''):'';project[s.id].push(item);lastRemoved=null;renderPanel();return;}const rem=event.target.closest?.('[data-mancer-remove]');if(rem){const arr=project[rem.dataset.mancerRemove],i=Number(rem.dataset.mancerIndex),s=sections().find(x=>x.id===rem.dataset.mancerRemove);if(Array.isArray(arr)&&arr[i]){const [item]=arr.splice(i,1);lastRemoved={sectionId:rem.dataset.mancerRemove,index:i,item:JSON.parse(JSON.stringify(item)),label:removedLabel(item,s)};status('Kohde poistettiin luonnoksesta. Voit kumota poiston ennen tallennusta.','');renderPanel();}return;}if(event.target.closest?.('[data-mancer-undo]')&&lastRemoved){const arr=project[lastRemoved.sectionId];if(Array.isArray(arr)){arr.splice(Math.min(lastRemoved.index,arr.length),0,lastRemoved.item);status('Poisto kumottiin.','ok');lastRemoved=null;renderPanel();}return;}if(event.target.closest?.('[data-mancer-runs-refresh]'))loadRuns();if(event.target.closest?.('[data-mancer-machine]'))window.dispatchEvent(new CustomEvent('anomancer:shell-route',{detail:{route:'machine'}}));});
window.addEventListener('anomancer:workspace-ready',e=>applyWorkspace(e.detail));
window.addEventListener('anomancer:workspace-change',e=>applyWorkspace(e.detail));
window.addEventListener('anomancer:admin-ready',()=>applyWorkspace());
window.anomancerMancer={isActive:isMancer,selectSection,activeSection:()=>active,save,hasUnsavedChanges:dirty,refreshDocumentTitle,load:loadArtifact,getData:()=>project?JSON.parse(JSON.stringify(project)):null};
