const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={csrf:'',posts:[],current:null,filter:'all',authenticated:false,mediaPreviews:{},dirty:false,busy:false,editorLocked:false,workspaceLocked:false,artifact:null,baseline:'',draftInstanceId:''};
const PUBLIC_ORIGIN='https://anomancer.com';
const MAX_SOURCE_BYTES=20*1024*1024;
const MAX_UPLOAD_BYTES=2*1024*1024;
const CATEGORY_LABELS={
  'ai-work':'Tekoäly arjessa ja työssä',
  'info-media':'Tieto, väitteet ja media',
  'work-decisions':'Työ, organisaatiot ja päätöksenteko',
  'money-risk':'Raha, riskit ja mittarit',
  'software-safety':'Ohjelmistot, automaatio ja turvallisuus',
  'language-learning':'Kieli, ajattelu ja oppiminen',
  'creativity-tools':'Luovuus ja työkalut',
  'society-systems':'Yhteiskunta ja järjestelmät'
};
const AUDIENCE_LABELS={all:'Kaikille',employee:'Työntekijälle',entrepreneur:'Yrittäjälle',developer:'Kehittäjälle',teacher:'Opettajalle',creative:'Luovalle tekijälle','decision-maker':'Päättäjälle',investor:'Sijoittajalle'};
const AUDIENCE_DEPTH_LABELS={plain:'Selkokieli',general:'Yleistajuinen',professional:'Ammattilainen',technical:'Syvä tekninen'};
const els={
  login:$('#loginView'),app:$('#appView'),loginForm:$('#loginForm'),password:$('#password'),loginError:$('#loginError'),
  postList:$('#postList'),repoStatus:$('#repoStatus'),newBtn:$('#newBtn'),logout:$('#logoutBtn'),editing:$('#editingLabel'),
  lang:$('#lang'),date:$('#date'),title:$('#title'),category:$('#category'),slug:$('#slug'),pinned:$('#pinned'),audienceDepth:$('#audienceDepth'),description:$('#description'),answer:$('#answer'),sources:$('#sources'),claims:$('#claims'),citationModeChecks:$$('input[name="citationMode"]'),citationPlacements:$('#citationPlacements'),citationStatus:$('#citationStatus'),visualizations:$('#visualizations'),visualizationReview:$('#visualizationReview'),translationKey:$('#translationKey'),
  coverImage:$('#coverImage'),coverAlt:$('#coverAlt'),coverPicker:$('#coverPicker'),coverSelect:$('#coverSelectBtn'),coverRemove:$('#coverRemoveBtn'),coverPreview:$('#coverPreview'),coverPreviewImg:$('#coverPreviewImg'),
  body:$('#body'),bodyImagePicker:$('#bodyImagePicker'),insertImage:$('#insertImageBtn'),mediaStatus:$('#mediaStatus'),
  descCount:$('#descCount'),answerCount:$('#answerCount'),wordCount:$('#wordCount'),preview:$('#preview'),previewBadge:$('#previewBadge'),status:$('#status'),
  saveDraft:$('#saveDraftBtn'),publish:$('#publishBtn'),del:$('#deleteBtn'),live:$('#liveLink'),publicUrl:$('#publicUrl'),publicUrlHint:$('#publicUrlHint'),
  audienceChecks:$$('input[name="audience"]'),sourceReview:$('#sourceReview'),claimReview:$('#claimReview'),evidenceReadiness:$('#evidenceReadiness'),evidenceBlockers:$('#evidenceBlockers'),sourceComposerTitle:$('#sourceComposerTitle'),sourceComposerUrl:$('#sourceComposerUrl'),sourceComposerPublisher:$('#sourceComposerPublisher'),sourceComposerDate:$('#sourceComposerDate'),sourceAdd:$('#sourceAddBtn'),claimAdd:$('#claimAddBtn'),publishDialog:$('#publishDialog'),publishSummary:$('#publishSummary'),publishConfirm:$('#publishConfirmBtn'),sidebar:$('#sidebar'),sidebarToggle:$('#sidebarToggle'),sidebarClose:$('#sidebarClose'),mobileDock:$('#mobileDock'),mobileMore:$('#mobileMoreBtn'),mobileBackdrop:$('#mobileUiBackdrop'),mobileSave:$('#mobileSaveBtn'),mobilePublish:$('#mobilePublishBtn'),mobilePreview:$('#mobilePreviewBtn'),mobilePreviewClose:$('#mobilePreviewClose'),mobileCore:$('#mobileCoreBtn'),mobileSettings:$('#mobileSettingsBtn'),topActions:$('.top-actions'),mobileCommandPortal:$('#mobileCommandPortal')
};

function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function escAttr(s=''){return esc(s);}
function cleanHttpUrl(value=''){try{const url=new URL(String(value||'').trim());return ['http:','https:'].includes(url.protocol)?url.toString():'';}catch{return'';}}

function parseSourcesText(text=''){
  const out=[];const seen=new Set();
  for(const raw of String(text).split('\n')){const line=raw.trim();if(!line)continue;let source={};if(line.startsWith('{')){try{source=JSON.parse(line);}catch{continue;}}else{const parts=line.split('|').map(x=>x.trim());const [title='',url='',publisher='',date='']=parts;source={title,url,publisher,date,origin:'human',verification:'verified'};}const title=String(source.title||'').trim(),url=cleanHttpUrl(source.url);if(!title||!url||seen.has(url))continue;seen.add(url);out.push({...source,title,url,origin:source.origin==='source-agent'?'source-agent':'human',verification:['candidate','verified','rejected'].includes(source.verification)?source.verification:(source.origin==='source-agent'?'candidate':'verified')});}
  return out;
}
function formatSourcesText(items=[]){return (Array.isArray(items)?items:[]).map(x=>JSON.stringify({id:x.id||'',title:x.title||'',url:x.url||'',publisher:x.publisher||'',date:x.date||'',origin:x.origin||'human',verification:x.verification||'verified',retrievedAt:x.retrievedAt||'',why:x.why||'',supports:x.supports||'',challenges:x.challenges||''})).join('\n');}
function parseClaimsText(text=''){
  return String(text).split('\n').map(raw=>{const line=raw.trim();if(!line)return null;const parts=line.split('|').map(x=>x.trim());const status=['supported','interpretation','open'].includes(parts[0])?parts[0]:'open';const text=parts[1]||'';const evidence=(parts[2]||'').split(',').map(x=>x.trim()).filter(Boolean);const note=parts.slice(3).join(' | ').trim();return text?{status,text,evidence,note}:null;}).filter(Boolean);
}
function formatClaimsText(items=[]){return (Array.isArray(items)?items:[]).map(x=>[x.status||'open',x.text||'',(x.evidence||[]).join(', '),x.note||''].join(' | ').replace(/(?:\s*\|\s*)+$/,'')).join('\n');}
function parseJsonArray(text=''){try{const v=JSON.parse(String(text||'[]'));return Array.isArray(v)?v:[];}catch{return [];}}
function selectedCitationMode(){return els.citationModeChecks.find(x=>x.checked)?.value||'inline';}
function setCitationMode(value='inline'){const mode=['inline','sources','both'].includes(value)?value:'inline';els.citationModeChecks.forEach(x=>x.checked=x.value===mode);}
function applyCitationPlacements(body='',placements=[]){let out=String(body||'');for(const p of Array.isArray(placements)?placements:[]){const quote=String(p.quote||''),anchor=String(p.anchorText||''),url=String(p.evidenceUrl||'');if(!quote||!anchor||!url||!quote.includes(anchor))continue;const first=out.indexOf(quote);if(first<0||out.indexOf(quote,first+quote.length)>=0)continue;const linked=quote.replace(anchor,`[${anchor}](${url})`);out=out.slice(0,first)+linked+out.slice(first+quote.length);}return out;}
function chartSvg(chart={},compact=false){const series=Array.isArray(chart.series)?chart.series:[];if(series.length<2)return '';const w=compact?520:760,h=compact?240:320,pad={l:54,r:20,t:34,b:64};const vals=series.map(x=>Number(x.value)).filter(Number.isFinite);if(vals.length<2)return '';let min=Math.min(0,...vals),max=Math.max(0,...vals);if(min===max){min-=1;max+=1;}const y=v=>pad.t+(max-v)/(max-min)*(h-pad.t-pad.b),base=y(0),inner=w-pad.l-pad.r;const escSvg=s=>esc(String(s));let marks='';if(chart.type==='line'){const pts=series.map((p,i)=>`${pad.l+(i/(series.length-1))*inner},${y(Number(p.value))}`).join(' ');marks=`<polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="2"/>`+series.map((p,i)=>`<circle cx="${pad.l+(i/(series.length-1))*inner}" cy="${y(Number(p.value))}" r="4" fill="currentColor"/>`).join('');}else{const gap=inner/series.length,bw=Math.max(8,gap*.58);marks=series.map((p,i)=>{const yy=y(Number(p.value)),x=pad.l+i*gap+(gap-bw)/2,top=Math.min(yy,base),hh=Math.max(1,Math.abs(base-yy));return `<rect x="${x}" y="${top}" width="${bw}" height="${hh}" rx="3" fill="currentColor" opacity=".72"/>`;}).join('');}const labels=series.map((p,i)=>{const x=pad.l+(i+(chart.type==='line'?0:0.5))*inner/(chart.type==='line'?Math.max(1,series.length-1):series.length);return `<text x="${x}" y="${h-26}" text-anchor="middle">${escSvg(String(p.label).slice(0,16))}</text>`;}).join('');return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${escAttr(chart.title||'Kaavio')}"><line x1="${pad.l}" y1="${base}" x2="${w-pad.r}" y2="${base}" stroke="currentColor" opacity=".22"/>${marks}${labels}</svg>`;}
function renderVisualizationReview(){if(!els.visualizationReview)return;const charts=parseJsonArray(els.visualizations?.value);if(!charts.length){els.visualizationReview.innerHTML='<p class="source-empty">Ei hyväksyttyjä kaavioita. Aja tarvittaessa Visualisointivahti ja tarkista ehdotus.</p>';return;}els.visualizationReview.innerHTML=charts.map((c,i)=>`<article class="visualization-card"><div><span>HYVÄKSYTTY · ${esc((c.type||'bar').toUpperCase())}</span><h4>${esc(c.title||`Kaavio ${i+1}`)}</h4>${c.caption?`<p>${esc(c.caption)}</p>`:''}</div>${chartSvg(c,true)}<small>${(c.series||[]).length} datapistettä · jokaisella evidenssijälki</small><button type="button" class="ghost" data-viz-remove="${i}">Poista</button></article>`).join('');}
function slugify(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,90);}
function inline(s=''){let x=esc(s);x=x.replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+|\/[^\s)]*)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/(^|[^*])\*([^*]+)\*/g,'$1<em>$2</em>');return x;}
function imageMarkup(line){
  const m=String(line).match(/^!\[([^\]]*)\]\((https?:\/\/[^\s)]+|\/[^\s)]+)(?:\s+"([^"]*)")?\)$/);
  if(!m)return null;
  const [,alt,url,caption='']=m;const src=state.mediaPreviews[url]||url;
  return `<figure class="md-image"><img src="${escAttr(src)}" alt="${escAttr(alt)}" loading="lazy">${caption?`<figcaption>${esc(caption)}</figcaption>`:''}</figure>`;
}
function markdown(md=''){
  const lines=String(md).replace(/\r\n/g,'\n').split('\n'),out=[];let para=[],list=null,code=false,codeLines=[];
  const fp=()=>{if(para.length){out.push(`<p>${inline(para.join(' '))}</p>`);para=[]}};
  const fl=()=>{if(list){out.push(`<${list.t}>${list.a.map(v=>`<li>${inline(v)}</li>`).join('')}</${list.t}>`);list=null}};
  const fc=()=>{if(code){out.push(`<pre><code>${esc(codeLines.join('\n'))}</code></pre>`);code=false;codeLines=[]}};
  for(const line of lines){
    if(line.startsWith('```')){fp();fl();if(code)fc();else code=true;continue}
    if(code){codeLines.push(line);continue}
    const img=imageMarkup(line.trim());if(img){fp();fl();out.push(img);continue}
    const h=line.match(/^(#{1,3})\s+(.+)/);if(h){fp();fl();out.push(`<h${h[1].length}>${inline(h[2])}</h${h[1].length}>`);continue}
    if(/^>\s?/.test(line)){fp();fl();out.push(`<blockquote>${inline(line.replace(/^>\s?/,''))}</blockquote>`);continue}
    const ul=line.match(/^[-*]\s+(.+)/);const ol=line.match(/^\d+\.\s+(.+)/);if(ul||ol){fp();const t=ul?'ul':'ol';if(!list||list.t!==t){fl();list={t,a:[]}}list.a.push((ul||ol)[1]);continue}
    if(/^---+$/.test(line.trim())){fp();fl();out.push('<hr>');continue}
    if(!line.trim()){fp();fl();continue}
    para.push(line.trim())
  }
  fp();fl();fc();return out.join('');
}

function selectedWorkspaceId(){return window.anomancerWorkspaces?.currentId?.()||localStorage.getItem('anomancer.core.workspace.v16.8')||localStorage.getItem('anomancer.core.workspace.v16.7')||localStorage.getItem('anomancer.core.workspace.v16.6')||localStorage.getItem('anomancer.core.workspace.v16.5')||localStorage.getItem('anomancer.core.workspace.v15.9')||'default';}
async function api(url,opts={}){const{workspaceId=selectedWorkspaceId(),...request}=opts,headers={'Content-Type':'application/json','X-Anomancer-Workspace':workspaceId,...(request.headers||{})};if(state.csrf&&request.method&&request.method!=='GET')headers['X-CSRF-Token']=state.csrf;const r=await fetch(url,{credentials:'same-origin',...request,headers});const data=await r.json().catch(()=>({ok:false,message:`HTTP ${r.status}`}));if(!r.ok||data.ok===false)throw Object.assign(new Error(data.message||data.error||`HTTP ${r.status}`),{data,status:r.status});return data;}
const dirtySources=new Map();
function registerDirtySource(id,label,read){if(!id||typeof read!=='function')return()=>{};dirtySources.set(id,{label:String(label||id),read});return()=>dirtySources.delete(id);}
function getDirtySources(){return[...dirtySources.entries()].flatMap(([id,source])=>{try{return source.read()?[{id,label:source.label}]:[];}catch{return[];}});}
function hasAnyUnsavedChanges(){return getDirtySources().length>0;}
window.anomancerDirty={register:registerDirtySource,sources:getDirtySources,hasAny:hasAnyUnsavedChanges};
registerDirtySource('dispatches','Lähetyskone',()=>state.dirty);
let postsRequestId=0,postsController=null;
function setStatus(text,type=''){els.status.textContent=text;els.status.className=`status ${type}`;window.anomancerFeedback?.report?.(text,type,'Lähetyskone');}
function formatEditorialIssues(error){const message=error?.message||'Tuntematon virhe.';const issues=Array.isArray(error?.data?.issues)?error.data.issues.filter(issue=>issue?.severity==='error'):[];if(error?.data?.error!=='EDITORIAL_QUALITY'||!issues.length)return message;const details=issues.map(issue=>`${issue.code||'EDITORIAL_QUALITY'}${issue.excerpt?` · osuma: “${String(issue.excerpt).slice(0,120)}”`:''}`).join('\n');return `${message}\n${details}`;}
function formatEditorialWarnings(items=[]){const warnings=Array.isArray(items)?items.filter(issue=>issue?.severity==='warning'):[];if(!warnings.length)return '';return warnings.map(issue=>`⚠ ${issue.code||'EDITORIAL_WARNING'}${issue.excerpt?` · osuma: “${String(issue.excerpt).slice(0,120)}”`:''}`).join('\n');}
function neutralizeSourceWorkflowLabels(text=''){return String(text).replace(/\b(?:lähde-ehdokas|kandidaattilähde)\b/giu,m=>/^[A-ZÅÄÖ]/u.test(m)?'Lähde':'lähde').replace(/\b(?:source candidate|candidate source)\b/giu,m=>/^[A-Z]/.test(m)?'Source':'source');}
async function repairEditorialSourceDebt(error){const issues=Array.isArray(error?.data?.issues)?error.data.issues:[];if(error?.data?.error!=='EDITORIAL_QUALITY'||!issues.some(issue=>issue?.code==='EDITORIAL_SOURCE_DEBT'))return false;const before=els.body.value,after=neutralizeSourceWorkflowLabels(before);if(after===before)return false;const hits=issues.filter(issue=>issue?.code==='EDITORIAL_SOURCE_DEBT').map(issue=>issue.excerpt).filter(Boolean).slice(0,4).join(', ');if(!await window.anomancerDialogs.confirm(`Julkaisutekstissä on toimituksen sisäinen lähdestatus${hits?` (${hits})`:''}.`,{title:'Korjaa toimituksen sisäinen lähdekieli?',details:'Workflow-leimat muutetaan neutraaliksi lähdekieleksi editorissa. Julkaisua EI tehdä automaattisesti. Tarkista korjaus ja julkaise sen jälkeen uudelleen.',confirmLabel:'Korjaa editorissa'}))return false;els.body.value=after;els.body.dispatchEvent(new Event('input',{bubbles:true}));selectEditorView('write');els.body.focus();setStatus('✓ Workflow-lähdestatus siirrettiin pois julkaisuproosasta. Tarkista muuttuneet kohdat ja paina Julkaise uudelleen.','ok');return true;}

function setMediaStatus(text,type=''){els.mediaStatus.textContent=text;els.mediaStatus.className=`media-status ${type}`;}
function newDraftInstanceId(){return globalThis.crypto?.randomUUID?.()||`draft-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;}
function emptyPost(){return{lang:'fi',date:new Date().toISOString().slice(0,10),title:'',category:'info-media',audience:['all'],audienceDepth:'general',description:'',answer:'',sources:[],claims:[],citationMode:'inline',citationPlacements:[],visualizations:[],slug:'',translationKey:'',aliases:[],coverImage:'',coverAlt:'',pinned:false,draft:true,body:'',path:'',sha:''};}
function selectedAudience(){const picked=els.audienceChecks.filter(x=>x.checked).map(x=>x.value);return picked.length?picked:['all'];}
function setAudience(values){const set=new Set(Array.isArray(values)&&values.length?values:['all']);els.audienceChecks.forEach(x=>x.checked=set.has(x.value));if(!els.audienceChecks.some(x=>x.checked)){const all=els.audienceChecks.find(x=>x.value==='all');if(all)all.checked=true;}}
function currentForm(draft){const slug=els.slug.value.trim()||slugify(els.title.value);const savedSlug=state.current?.slug||'';const aliases=[...new Set([...(state.current?.aliases||[]),...(state.current?.draft===false&&savedSlug&&savedSlug!==slug?[savedSlug]:[])])].filter(x=>x&&x!==slug);return{lang:els.lang.value,date:els.date.value,title:els.title.value.trim(),category:els.category.value,audience:selectedAudience(),audienceDepth:els.audienceDepth?.value||'general',description:els.description.value.trim(),answer:els.answer.value.trim(),sources:parseSourcesText(els.sources.value),claims:parseClaimsText(els.claims.value),citationMode:selectedCitationMode(),citationPlacements:parseJsonArray(els.citationPlacements?.value),visualizations:parseJsonArray(els.visualizations?.value),slug,translationKey:els.translationKey.value.trim()||slugify(els.slug.value||els.title.value),aliases,coverImage:els.coverImage.value.trim(),coverAlt:els.coverAlt.value.trim(),pinned:Boolean(els.pinned.checked),draft,body:els.body.value};}
function fingerprintPost(post){let hash=2166136261;const raw=JSON.stringify(post);for(const char of raw){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return (hash>>>0).toString(36);}
function updateDirty(){state.dirty=fingerprintPost(currentForm(Boolean(state.current?.draft)))!==state.baseline;document.title=`${state.dirty?'• ':''}Anomancer Core · Lähetyskone`;const indicator=$('#workspaceSaveIndicator');if(indicator&&document.body.dataset.workspaceTemplate!=='narrative-authoring')indicator.textContent=state.dirty?'TALLENTAMATON':'VALMIS';}
async function confirmDiscard(options={}){const sources=getDirtySources();if(!sources.length)return true;const names=sources.map(source=>source.label).join(', ');return window.anomancerDialogs.confirm(`Tallentamattomia muutoksia: ${names}.`,{title:options.title||'Hylätäänkö muutokset?',details:options.details||'Tallentamattomia muutoksia ei voi palauttaa tämän siirtymän jälkeen.',confirmLabel:options.confirmLabel||'Hylkää muutokset',destructive:true});}
function updateCoverPreview(){const url=els.coverImage.value.trim();els.coverPreview.hidden=!url;els.coverRemove.hidden=!url;if(url){els.coverPreviewImg.src=state.mediaPreviews[url]||url;els.coverPreviewImg.alt=els.coverAlt.value.trim()||'';}else{els.coverPreviewImg.removeAttribute('src');}}
function loadForm(p){state.current=p;state.draftInstanceId=p.path?'':newDraftInstanceId();els.lang.disabled=Boolean(p.path);els.lang.value=p.lang||'fi';els.date.value=p.date||new Date().toISOString().slice(0,10);els.title.value=p.title||'';els.category.value=CATEGORY_LABELS[p.category]?p.category:'info-media';setAudience(p.audience);if(els.audienceDepth)els.audienceDepth.value=AUDIENCE_DEPTH_LABELS[p.audienceDepth]?p.audienceDepth:'general';els.description.value=p.description||'';els.answer.value=p.answer||'';els.sources.value=formatSourcesText(p.sources);els.claims.value=formatClaimsText(p.claims);setCitationMode(p.citationMode||'inline');if(els.citationPlacements)els.citationPlacements.value=JSON.stringify(p.citationPlacements||[],null,2);if(els.visualizations)els.visualizations.value=JSON.stringify(p.visualizations||[],null,2);els.slug.value=p.slug||'';els.translationKey.value=p.translationKey||'';els.coverImage.value=p.coverImage||'';els.coverAlt.value=p.coverAlt||'';els.pinned.checked=Boolean(p.pinned);els.body.value=p.body||'';els.editing.textContent=p.path?(p.title||p.path):'Uusi lähetys';els.del.hidden=!p.path;updateCoverPreview();renderLiveLink();refreshPreview();renderList();setStatus('');setMediaStatus('');state.baseline=fingerprintPost(currentForm(Boolean(p.draft)));state.dirty=false;document.title='Anomancer Core · Lähetyskone';const indicator=$('#workspaceSaveIndicator');if(indicator&&document.body.dataset.workspaceTemplate!=='narrative-authoring')indicator.textContent='VALMIS';}
function renderList(){const posts=state.posts.filter(p=>state.filter==='all'||(state.filter==='draft'?p.draft:!p.draft));els.postList.innerHTML=posts.map(p=>`<button class="post-item ${state.current?.path===p.path?'active':''}" data-path="${esc(p.path)}"><strong>${esc(p.title||p.path)}</strong><span>${String(p.lang||'').toUpperCase()} · ${esc(CATEGORY_LABELS[p.category]||p.category||'')} · ${esc(p.date||'')} ${p.pinned?'· PINNATTU ':''}${p.coverImage?'· KUVA ':''}${p.draft?'· LUONNOS':'· JULKAISTU'}</span></button>`).join('')||'<p class="muted">Ei julkaisuja tässä näkymässä.</p>';$$('.post-item').forEach(b=>b.onclick=async()=>{const p=state.posts.find(x=>x.path===b.dataset.path);if(p&&await confirmDiscard()){loadForm(p);closeSidebar();}});}
function publicPath(p){const slug=p.slug||slugify(p.title);const base=p.lang==='en'?'/dispatches':'/lahetykset';return slug?`${base}/${slug}`:`${base}/…`;}
function renderLiveLink(){const p=currentForm(Boolean(state.current?.draft));const slug=p.slug||slugify(p.title);const path=publicPath(p);els.publicUrl.textContent=`${PUBLIC_ORIGIN}${path}`;const savedSlug=state.current?.slug||slugify(state.current?.title||'');const isPublished=Boolean(state.current?.path&&state.current?.draft===false);const isSavedUrl=Boolean(isPublished&&slug&&slug===savedSlug&&p.lang===(state.current?.lang||p.lang));if(isSavedUrl){els.publicUrlHint.textContent='Julkaistu. Tämä on nykyinen julkinen osoite.';els.live.href=`${PUBLIC_ORIGIN}${path}`;els.live.hidden=false;}else{els.live.hidden=true;if(isPublished&&slug){els.publicUrlHint.textContent='URL on muuttunut. Julkaise muutokset, jotta uusi osoite aktivoituu.';}else if(state.current?.path&&state.current?.draft){els.publicUrlHint.textContent='Luonnos. Osoite aktivoituu julkaistaessa.';}else{els.publicUrlHint.textContent='URL muodostuu otsikosta tai URL-tunnuksesta.';}}}
function evidenceSnapshot(){const sources=parseSourcesText(els.sources?.value||''),claims=parseClaimsText(els.claims?.value||''),verified=new Set(sources.filter(source=>source.verification==='verified').map(source=>source.url));const blockers=[];for(const source of sources)if(source.verification!=='verified')blockers.push({type:'source',text:`Lähde odottaa tarkistusta: ${source.title}`});claims.forEach((claim,index)=>{if(claim.status==='supported'&&!claim.evidence.some(url=>verified.has(url)))blockers.push({type:'claim',index,text:`Tuettu väite ${index+1} tarvitsee tarkistetun lähteen.`});});const readyClaims=claims.filter(claim=>claim.status!=='supported'||claim.evidence.some(url=>verified.has(url))).length;return{sources,claims,verified,blockers,readyClaims};}
function renderEvidenceSummary(){const data=evidenceSnapshot();if(els.evidenceReadiness){const checked=data.sources.filter(source=>source.verification==='verified').length;els.evidenceReadiness.innerHTML=`<div><span>Lähteet tarkistettu</span><strong>${checked}/${data.sources.length}</strong></div><div><span>Väitteet julkaisuvalmiina</span><strong>${data.readyClaims}/${data.claims.length}</strong></div><div><span>Julkaisuportti</span><strong data-state="${data.blockers.length?'blocked':'ready'}">${data.blockers.length?`${data.blockers.length} estettä`:'Valmis'}</strong></div>`;}if(els.evidenceBlockers){els.evidenceBlockers.hidden=!data.blockers.length;els.evidenceBlockers.innerHTML=data.blockers.length?`<strong>Korjaa ennen julkaisua</strong><ul>${data.blockers.map(item=>`<li>${esc(item.text)}</li>`).join('')}</ul>`:'';}return data;}
function renderSourceReview(){if(!els.sourceReview)return;const {sources}=evidenceSnapshot();if(!sources.length){els.sourceReview.innerHTML='<p class="source-empty">Ei lähteitä. Lisää ensimmäinen lähde yllä tai aja Lähdeagentti.</p>';return;}els.sourceReview.innerHTML=sources.map((source,index)=>{const status=source.verification||'verified';const label=status==='verified'?'Tarkistettu':status==='rejected'?'Hylätty':'Ehdokas';return `<article class="source-card" data-source-status="${escAttr(status)}"><div class="source-card-head"><span class="source-state">${label}</span><span>L${index+1} · ${source.origin==='source-agent'?'Agenttihaku':'Ihmisen lisäämä'}</span></div><h4>${esc(source.title)}</h4><p class="source-url">${esc(source.url)}</p>${source.publisher||source.date?`<p>${esc([source.publisher,source.date].filter(Boolean).join(' · '))}</p>`:''}${source.why?`<p><strong>Miksi:</strong> ${esc(source.why)}</p>`:''}${source.supports?`<p><strong>Tukee:</strong> ${esc(source.supports)}</p>`:''}${source.challenges?`<p><strong>Haastaa:</strong> ${esc(source.challenges)}</p>`:''}<div class="source-actions"><a href="${escAttr(source.url)}" target="_blank" rel="noopener noreferrer">Avaa lähde ↗</a>${status!=='verified'?`<button type="button" data-source-action="verify" data-source-index="${index}">Merkitse tarkistetuksi</button>`:''}${status==='verified'&&source.origin==='source-agent'?`<button type="button" class="ghost" data-source-action="candidate" data-source-index="${index}">Palauta ehdokkaaksi</button>`:''}<button type="button" class="ghost" data-source-action="remove" data-source-index="${index}">Poista</button></div></article>`;}).join('');}
function renderClaimReview(){if(!els.claimReview)return;const data=evidenceSnapshot();if(!data.claims.length){els.claimReview.innerHTML='<p class="source-empty">Ei väitteitä. Lisää väite korttina tai aja Väitevahti.</p>';return;}els.claimReview.innerHTML=data.claims.map((claim,index)=>{const missing=claim.status==='supported'&&!claim.evidence.some(url=>data.verified.has(url));const sourceChoices=data.sources.length?data.sources.map((source,sourceIndex)=>{const checked=claim.evidence.includes(source.url),candidate=source.verification!=='verified',disabled=claim.status==='supported'&&candidate;return `<label class="claim-source-option${candidate?' candidate':''}${disabled?' disabled':''}"><input type="checkbox" data-claim-source="${index}" data-source-url="${escAttr(source.url)}" ${checked?'checked':''} ${disabled?'disabled':''}><span><strong>L${sourceIndex+1} · ${esc(source.title)}</strong><small>${source.verification==='verified'?'Tarkistettu':'Ehdokas'}${disabled?' · ei kelpaa tuetun väitteen evidenssiksi':''}</small></span></label>`;}).join(''):'<p class="field-help">Lisää ensin lähde.</p>';return `<article class="claim-card${missing?' has-blocker':''}" data-claim-index="${index}"><div class="claim-card-head"><span>VÄITE ${index+1}</span><select aria-label="Väitteen tila" data-claim-field="status" data-claim-index="${index}"><option value="supported" ${claim.status==='supported'?'selected':''}>Tuettu väite</option><option value="interpretation" ${claim.status==='interpretation'?'selected':''}>Tulkinta</option><option value="open" ${claim.status==='open'?'selected':''}>Avoin</option></select></div>${missing?'<p class="claim-blocker">Julkaisueste: tuetulta väitteeltä puuttuu ihmisen tarkistama lähde.</p>':''}<label>Väite<textarea maxlength="600" rows="3" data-claim-field="text" data-claim-index="${index}">${esc(claim.text)}</textarea></label><fieldset class="claim-source-picker"><legend>Evidenssilähteet</legend>${sourceChoices}</fieldset><label>Huomio<textarea maxlength="800" rows="2" data-claim-field="note" data-claim-index="${index}">${esc(claim.note||'')}</textarea></label><button type="button" class="ghost claim-remove" data-claim-remove="${index}">Poista väite</button></article>`;}).join('');}
function renderEvidenceInteraction(){renderEvidenceSummary();renderSourceReview();renderClaimReview();}
function writeSources(items){els.sources.value=formatSourcesText(items);els.sources.dispatchEvent(new Event('input',{bubbles:true}));}
function writeClaims(items){els.claims.value=formatClaimsText(items);els.claims.dispatchEvent(new Event('input',{bubbles:true}));}
function addSourceFromComposer(){const title=String(els.sourceComposerTitle?.value||'').trim(),url=cleanHttpUrl(els.sourceComposerUrl?.value||''),publisher=String(els.sourceComposerPublisher?.value||'').trim(),date=String(els.sourceComposerDate?.value||'').trim();if(!title||!url){setStatus('Lisää lähteelle otsikko ja kelvollinen http/https-osoite.','err');return;}const sources=parseSourcesText(els.sources.value);if(sources.some(source=>source.url===url)){setStatus('Sama lähde on jo evidenssikerroksessa.','err');return;}sources.push({title,url,publisher,date,origin:'human',verification:'verified'});for(const input of [els.sourceComposerTitle,els.sourceComposerUrl,els.sourceComposerPublisher,els.sourceComposerDate])if(input)input.value='';writeSources(sources);setStatus('✓ Lähde lisätty tarkistetuksi ihmisen lisäämänä.','ok');}
function addClaimCard(){const claims=parseClaimsText(els.claims.value);claims.push({status:'open',text:'Uusi väite',evidence:[],note:''});writeClaims(claims);requestAnimationFrame(()=>els.claimReview?.querySelector(`[data-claim-index="${claims.length-1}"] textarea`)?.focus());}
async function updateSource(index,action){const sources=parseSourcesText(els.sources.value),source=sources[index];if(!source)return;if(action==='remove'){const url=source.url;sources.splice(index,1);const claims=parseClaimsText(els.claims.value).map(claim=>({...claim,evidence:claim.evidence.filter(item=>item!==url)}));els.claims.value=formatClaimsText(claims);}else if(action==='verify'){if(!await window.anomancerDialogs.confirm(`Merkitäänkö “${source.title||source.url}” tarkistetuksi?`,{title:'Vahvista lähteen tarkistus',details:'Vahvista vain, jos olet avannut lähteen ja tarkistanut, että sen sisältö, asiayhteys ja väitteeseen kytkentä pitävät.',confirmLabel:'Merkitse tarkistetuksi'}))return;source.verification='verified';}else source.verification='candidate';writeSources(sources);refreshPreview();updateDirty();}
function updateClaimField(index,field,value){const claims=parseClaimsText(els.claims.value),claim=claims[index];if(!claim)return;if(field==='status')claim.status=['supported','interpretation','open'].includes(value)?value:'open';else if(field==='text')claim.text=String(value||'').trim()||'Uusi väite';else if(field==='note')claim.note=String(value||'').trim();writeClaims(claims);}
function toggleClaimSource(index,url,checked){const claims=parseClaimsText(els.claims.value),claim=claims[index];if(!claim)return;const evidence=new Set(claim.evidence||[]);checked?evidence.add(url):evidence.delete(url);claim.evidence=[...evidence];writeClaims(claims);}
function removeClaim(index){const claims=parseClaimsText(els.claims.value);claims.splice(index,1);writeClaims(claims);}
function refreshPreview(){const p=currentForm(Boolean(state.current?.draft));const words=p.body.trim()?p.body.trim().split(/\s+/).length:0;els.wordCount.textContent=`${words} sanaa · ${Math.max(1,Math.ceil(words/220))} min`;els.descCount.textContent=`${p.description.length} / 220`;els.answerCount.textContent=`${p.answer.length} / 1200`;els.previewBadge.textContent=`${p.pinned?'PINNATTU · ':''}${state.current?.draft===false?'JULKAISTU':'LUONNOS'}`;const coverSrc=p.coverImage?(state.mediaPreviews[p.coverImage]||p.coverImage):'';const cover=p.coverImage?`<figure class="preview-cover"><img src="${escAttr(coverSrc)}" alt="${escAttr(p.coverAlt)}"></figure>`:'';const aud=`<div class="preview-audience">${p.audience.map(id=>`<span>${esc(AUDIENCE_LABELS[id]||id)}</span>`).join('')}<span>${esc(AUDIENCE_DEPTH_LABELS[p.audienceDepth]||'Yleistajuinen')}</span></div>`;const answer=p.answer?`<section class="preview-evidence-answer"><strong>Ydinvastaus</strong><p>${esc(p.answer)}</p></section>`:'';const verified=p.sources.filter(x=>x.verification==='verified').length;const ev=(p.sources.length||p.claims.length)?`<p class="preview-evidence-count">Evidenssikerros · ${verified}/${p.sources.length} lähdettä tarkistettu · ${p.claims.length} väitettä · viitteet ${esc(p.citationMode)}</p>`:'';const previewBody=['inline','both'].includes(p.citationMode)?applyCitationPlacements(p.body,p.citationPlacements):p.body;const charts=(p.visualizations||[]).map(c=>`<figure class="preview-chart"><h3>${esc(c.title)}</h3>${chartSvg(c,true)}${c.caption?`<figcaption>${esc(c.caption)}</figcaption>`:''}</figure>`).join('');els.preview.innerHTML=`<p class="kicker">${esc(CATEGORY_LABELS[p.category]||p.category)}</p>${aud}<h1>${esc(p.title||'Otsikko')}</h1><p class="muted">${esc(p.date||'')}</p>${answer}${cover}${markdown(previewBody||'')}${charts}${ev}`;if(els.citationStatus)els.citationStatus.textContent=`${p.citationPlacements.length} hyväksyttyä inline-sijoitusta · tila: ${p.citationMode}`;updateCoverPreview();renderLiveLink();renderEvidenceInteraction();renderVisualizationReview();}

function setBusy(value){state.busy=value;setEditorLocked(state.editorLocked);for(const element of [els.saveDraft,els.publish,els.del,els.newBtn,els.mobileSave,els.mobilePublish])if(element)element.disabled=value||state.editorLocked||state.workspaceLocked;}
function setEditorLocked(value){state.editorLocked=value;const selectors=['#mobileSaveBtn','#mobilePublishBtn','#lang','#date','#title','#category','#slug','#pinned','#audienceDepth','#description','#translationKey','#coverAlt','#body','#answer','#sources','#claims','#citationPlacements','#visualizations','input[name="citationMode"]','#coverSelectBtn','#coverRemoveBtn','#insertImageBtn','#saveDraftBtn','#publishBtn','#deleteBtn','#newBtn','#agentRunBtn','#agentApplyBtn','#agentMoreBtn','.post-item','.source-review button','.claim-review button','.claim-review select','.claim-review textarea','#sourceComposerTitle','#sourceComposerUrl','#sourceComposerPublisher','#sourceComposerDate','#sourceAddBtn','#claimAddBtn'];for(const selector of selectors)for(const element of $$(selector))element.disabled=value||state.busy||state.workspaceLocked;document.body.classList.toggle('editor-locked',value);document.body.classList.toggle('workspace-artifact-locked',state.workspaceLocked);}
function setWorkspaceContext(detail={}){state.artifact=detail.artifact||state.artifact;state.workspaceLocked=Boolean(state.artifact&&!state.artifact.contentReadable);setEditorLocked(state.editorLocked);if(state.workspaceLocked)setStatus(`◈ ${detail.workspace?.name||'Työtila'} on eristetty. Anomancerin sisältöä ei avattu eikä julkaisukohdetta ole sidottu.`);}
function setSidebarOpen(open){const value=Boolean(open);if(value){setMobileMore(false);setMobilePreview(false);}els.sidebarToggle?.setAttribute('aria-expanded',String(value));const overlays=window.anomancerOverlays;if(overlays){value?overlays.open('dispatch-library',els.sidebarToggle):overlays.close('dispatch-library');return;}els.sidebar?.classList.toggle('is-open',value);document.body.classList.toggle('library-open',value);}
function closeSidebar(){setSidebarOpen(false);}
function updateSidebarLabel(){if(els.sidebarToggle)els.sidebarToggle.textContent=`Lähetykset${state.posts.length?` · ${state.posts.length}`:''}`;}
function syncMobileDock(name){$$('[data-mobile-view]').forEach(button=>{const active=button.dataset.mobileView===name;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});}
function setMobileMore(open){const value=Boolean(open);if(window.anomancerShell?.setMobileSheet){window.anomancerShell.setMobileSheet(value,document.activeElement);return;}document.body.classList.toggle('mobile-more-open',value);els.mobileMore?.setAttribute('aria-expanded',String(value));if(value)document.body.classList.remove('mobile-preview-open');}
const mobileCommandMedia=window.matchMedia('(max-width:760px)');
function syncMobileCommandHost(){const actions=els.topActions,portal=els.mobileCommandPortal,topbar=$('.topbar');if(!actions||!portal||!topbar)return;if(mobileCommandMedia.matches){if(actions.parentElement!==portal)portal.append(actions);}else{if(actions.parentElement!==topbar)topbar.append(actions);setMobileMore(false);setMobilePreview(false);}}
function setMobilePreview(open){const value=Boolean(open);if(value){setMobileMore(false);closeSidebar();refreshPreview();}const overlays=window.anomancerOverlays;if(overlays){value?overlays.open('editor-preview',els.mobilePreview||document.activeElement):overlays.close('editor-preview');return;}document.body.classList.toggle('mobile-preview-open',value);}
function selectEditorView(name){$$('[data-editor-tab]').forEach(button=>{const active=button.dataset.editorTab===name;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;});$$('[data-editor-panel]').forEach(panel=>{const active=panel.dataset.editorPanel===name;panel.classList.toggle('active',active);panel.hidden=!active;});syncMobileDock(name);window.dispatchEvent(new CustomEvent('anomancer:editor-view-change',{detail:{view:name}}));}
window.anomancerOverlays?.register?.('dispatch-library',{element:'#sidebar',backdrop:'#sidebarBackdrop',bodyClass:'library-open',focusSelector:'#sidebarClose',inertSelectors:['#coreShell','.workspace','#mobileDock']});
window.anomancerOverlays?.register?.('editor-preview',{element:'.preview-panel',backdrop:'#mobileUiBackdrop',bodyClass:'mobile-preview-open',focusSelector:'#mobilePreviewClose',inertSelectors:['#coreShell','.workspace-context-bar','#workspaceLocalSidebar','.editor-pane','.editor-resizer','#mobileDock']});

function imageDimensions(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{resolve({img,width:img.naturalWidth,height:img.naturalHeight,url})};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Kuvaa ei voitu avata.'))};img.src=url;});}
async function canvasBlob(canvas,type,quality){return await new Promise(resolve=>canvas.toBlob(resolve,type,quality));}
async function prepareImage(file){
  if(!file)throw new Error('Kuva puuttuu.');
  if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Tuettu kuvaformaatti: JPG, PNG tai WebP.');
  if(file.size>MAX_SOURCE_BYTES)throw new Error('Alkuperäinen kuva on liian suuri (max 20 Mt).');
  const decoded=await imageDimensions(file);
  try{
    let max=1600,quality=.84,blob=null;
    for(let attempt=0;attempt<5;attempt++){
      const scale=Math.min(1,max/Math.max(decoded.width,decoded.height));
      const w=Math.max(1,Math.round(decoded.width*scale)),h=Math.max(1,Math.round(decoded.height*scale));
      const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;
      const ctx=canvas.getContext('2d',{alpha:true});ctx.drawImage(decoded.img,0,0,w,h);
      blob=await canvasBlob(canvas,'image/webp',quality);
      if(!blob)blob=await canvasBlob(canvas,'image/jpeg',quality);
      if(blob&&blob.size<=MAX_UPLOAD_BYTES)break;
      max=Math.max(800,Math.round(max*.82));quality=Math.max(.62,quality-.06);
    }
    if(!blob||blob.size>MAX_UPLOAD_BYTES)throw new Error('Kuva ei pienentynyt tarpeeksi. Kokeile pienempää kuvaa.');
    return blob;
  } finally {URL.revokeObjectURL(decoded.url);}
}
function blobDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('Kuvan lukeminen epäonnistui.'));r.readAsDataURL(blob);});}
async function uploadImage(file){const blob=await prepareImage(file);const data=await blobDataUrl(blob);const result=await api('/api/admin/content?resource=media',{method:'POST',body:JSON.stringify({data,name:file.name,date:els.date.value})});return {...result,previewData:data};}
function insertAtCursor(text){const el=els.body,start=el.selectionStart??el.value.length,end=el.selectionEnd??start,before=el.value.slice(0,start),after=el.value.slice(end);const prefix=before&&!before.endsWith('\n')?'\n\n':'';const suffix=after&&!after.startsWith('\n')?'\n\n':'';el.value=before+prefix+text+suffix+after;const pos=(before+prefix+text).length;el.focus();el.setSelectionRange(pos,pos);refreshPreview();updateDirty();}
function cleanMdText(s=''){return String(s).replace(/[\[\]\n\r]/g,' ').trim();}
async function chooseCover(file){try{setMediaStatus('Kansikuvaa pienennetään ja lähetetään GitHubiin…');const r=await uploadImage(file);state.mediaPreviews[r.url]=r.previewData;els.coverImage.value=r.url;els.coverAlt.value=els.coverAlt.value.trim()||els.title.value.trim()||cleanMdText(file.name.replace(/\.[^.]+$/,''));setMediaStatus(`✓ Kansikuva tallennettu: ${r.url}`,'ok');refreshPreview();updateDirty();}catch(e){setMediaStatus(`✗ ${e.message}`,'err');}finally{els.coverPicker.value='';}}
async function chooseBodyImage(file){
  const proposed=els.title.value.trim()?`${els.title.value.trim()} – kuva`:cleanMdText(file.name.replace(/\.[^.]+$/,''));
  const imageMeta=await window.anomancerDialogs.form({title:'Kuvan tiedot',message:'Anna kuvalle saavutettava alt-teksti. Kuvateksti on valinnainen.',confirmLabel:'Jatka kuvan lisäämiseen',fields:[{name:'alt',label:'Alt-teksti',value:proposed,required:true,maxLength:300,hint:'Kuvaile olennainen sisältö tiiviisti.'},{name:'caption',label:'Kuvateksti',value:'',maxLength:500,hint:'Näkyvä kuvateksti artikkelissa. Voit jättää tyhjäksi.'}]});if(!imageMeta){els.bodyImagePicker.value='';return;}
  const {alt,caption}=imageMeta;
  try{setMediaStatus('Kuvaa pienennetään ja lähetetään GitHubiin…');const r=await uploadImage(file);state.mediaPreviews[r.url]=r.previewData;const safeAlt=cleanMdText(alt);const safeCaption=String(caption||'').replace(/["\n\r]/g,' ').trim();insertAtCursor(`![${safeAlt}](${r.url}${safeCaption?` "${safeCaption}"`:''})`);setMediaStatus(`✓ Kuva lisätty tekstiin: ${r.url}`,'ok');}catch(e){setMediaStatus(`✗ ${e.message}`,'err');}finally{els.bodyImagePicker.value='';}
}

async function session(){const d=await api('/api/admin/auth?resource=session',{method:'GET'});state.authenticated=d.authenticated;state.csrf=d.csrf||'';els.login.hidden=state.authenticated;els.app.hidden=!state.authenticated;if(state.authenticated){els.repoStatus.textContent=d.github?.configured?`${d.github.repo} · ${d.github.branch}`:'GitHub-yhteys ei ole vielä konfiguroitu';els.repoStatus.className=`repo-status ${d.github?.configured?'ok':''}`;if(d.github?.configured){try{const st=await api('/api/admin/auth?resource=status',{method:'GET'});if(st.github?.fullName){els.repoStatus.textContent=`✓ ${st.github.fullName} · ${st.github.branch}${st.github.private?' · yksityinen':''}`;els.repoStatus.className='repo-status ok';}}catch(e){els.repoStatus.textContent=`GitHub-yhteys: ${e.message}`;els.repoStatus.className='repo-status';}}await loadPosts();window.dispatchEvent(new CustomEvent('anomancer:admin-ready'));}}
async function loadPosts({workspaceId=selectedWorkspaceId()}={}){const requestId=++postsRequestId;postsController?.abort();const controller=new AbortController();postsController=controller;try{const d=await api('/api/admin/content?resource=posts',{method:'GET',workspaceId,signal:controller.signal});if(requestId!==postsRequestId||selectedWorkspaceId()!==workspaceId)return false;if(d.artifact)setWorkspaceContext({workspace:d.workspace,artifact:d.artifact});state.posts=d.posts||[];updateSidebarLabel();renderList();if(state.current?.path){const fresh=state.posts.find(p=>p.path===state.current.path);if(fresh)loadForm(fresh);else loadForm(emptyPost());}else if(state.workspaceLocked)loadForm(emptyPost());return true;}catch(e){if(e.name==='AbortError'||requestId!==postsRequestId||selectedWorkspaceId()!==workspaceId)return false;els.repoStatus.textContent=e.message;els.repoStatus.className='repo-status';return false;}finally{if(requestId===postsRequestId)postsController=null;}}
async function save(draft){if(state.busy||state.editorLocked)return;if(!navigator.onLine){setStatus('✗ Ei verkkoyhteyttä. Luonnosta tai julkaisua ei lähetetty.','err');return;}setBusy(true);try{setStatus(draft?'Tallennetaan luonnosta…':'Lähetetään eetteriin…');const post=currentForm(draft);const d=await api('/api/admin/content?resource=posts',{method:'POST',body:JSON.stringify({path:state.current?.path||'',sha:state.current?.sha||'',post})});const url=`${PUBLIC_ORIGIN}${publicPath(post)}`;await loadPosts();const fresh=state.posts.find(p=>p.path===d.path);if(fresh)loadForm(fresh);const warningText=draft?'':formatEditorialWarnings(d.editorialWarnings);setStatus(draft?'✓ Luonnos tallennettu GitHubiin.':`✓ Lähetyscommitti tehty. Julkinen osoite: ${url} · Vercel vie sen eetteriin automaattisesti.${warningText?`\n${warningText}`:''}`,'ok');}catch(e){if(!await repairEditorialSourceDebt(e))setStatus(`✗ ${formatEditorialIssues(e)}`,'err');}finally{setBusy(false);}}
async function remove(){if(state.busy||state.editorLocked||!state.current?.path)return;const approved=await window.anomancerDialogs.confirm(`Poistetaanko “${state.current.title}”?`,{title:'Poista lähetys',details:'Tämä tekee poistocommitin GitHubiin. Toiminto ei ole pelkkä paikallinen editorimuutos.',confirmLabel:'Poista GitHubista',destructive:true});if(!approved)return;setBusy(true);try{setStatus('Poistetaan…');await api('/api/admin/content?resource=posts',{method:'DELETE',body:JSON.stringify({path:state.current.path,sha:state.current.sha})});state.current=null;state.dirty=false;await loadPosts();loadForm(emptyPost());setStatus('✓ Poistettu GitHubista.','ok');}catch(e){setStatus(`✗ ${e.message}`,'err');}finally{setBusy(false);}}
function publishReview(){const p=currentForm(false);const verified=new Set(p.sources.filter(x=>x.verification==='verified').map(x=>x.url));const pending=p.sources.filter(x=>x.verification!=='verified');const unsupported=p.claims.filter(claim=>claim.status==='supported'&&!claim.evidence.some(url=>verified.has(url)));const errors=[];if(!p.title)errors.push('Otsikko puuttuu.');if(!p.description)errors.push('SEO-kuvaus puuttuu.');if(pending.length)errors.push(`${pending.length} lähdettä odottaa ihmisen tarkistusta.`);if(unsupported.length)errors.push(`${unsupported.length} tuettua väitettä ilman tarkistettua evidenssiä.`);if(p.coverImage&&!p.coverAlt)errors.push('Kansikuvalta puuttuu alt-teksti.');els.publishSummary.innerHTML=`<dl><div><dt>Otsikko</dt><dd>${esc(p.title||'—')}</dd></div><div><dt>Julkinen URL</dt><dd>${esc(PUBLIC_ORIGIN+publicPath(p))}</dd></div><div><dt>Lähteet</dt><dd>${p.sources.length} · ${verified.size} tarkistettu</dd></div><div><dt>Väitteet</dt><dd>${p.claims.length}</dd></div>${p.aliases.length?`<div><dt>Vanhat osoitteet</dt><dd>${p.aliases.map(esc).join(', ')}</dd></div>`:''}</dl>${errors.length?`<div class="publish-errors" role="alert"><strong>Julkaisu ei ole vielä valmis:</strong><ul>${errors.map(error=>`<li>${esc(error)}</li>`).join('')}</ul></div>`:'<p class="publish-ready">✓ Julkaisun pakolliset tarkistukset läpäisty.</p>'}`;els.publishConfirm.disabled=errors.length>0;els.publishDialog.showModal();}

els.loginForm.onsubmit=async e=>{e.preventDefault();els.loginError.textContent='';try{await api('/api/admin/auth?resource=login',{method:'POST',body:JSON.stringify({password:els.password.value})});els.password.value='';await session();}catch(e){els.loginError.textContent=e.message||'Kirjautuminen epäonnistui.'}};
els.logout.onclick=async()=>{if(!await confirmDiscard({title:'Kirjaudutaanko ulos?',details:'Uloskirjautuminen hylkää kaikkien aktiivisten työtilojen tallentamattomat muutokset.',confirmLabel:'Kirjaudu ulos'}))return;try{await api('/api/admin/auth?resource=logout',{method:'POST',body:'{}'});}catch{}state.csrf='';state.authenticated=false;state.dirty=false;els.app.hidden=true;els.login.hidden=false;};
els.newBtn.onclick=async()=>{if(await confirmDiscard()){loadForm(emptyPost());closeSidebar();}};els.saveDraft.onclick=()=>save(true);els.publish.onclick=publishReview;els.del.onclick=remove;
els.coverSelect.onclick=()=>els.coverPicker.click();els.coverPicker.onchange=()=>{const f=els.coverPicker.files?.[0];if(f)chooseCover(f)};
els.coverRemove.onclick=()=>{els.coverImage.value='';els.coverAlt.value='';setMediaStatus('Kansikuva irrotettu artikkelista. GitHubiin jo tallennettu kuvatiedosto jää talteen.');refreshPreview();updateDirty();};
els.insertImage.onclick=()=>els.bodyImagePicker.click();els.bodyImagePicker.onchange=()=>{const f=els.bodyImagePicker.files?.[0];if(f)chooseBodyImage(f)};
$$('.filters button').forEach(b=>b.onclick=()=>{$$('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderList()});
els.audienceDepth?.addEventListener('change',()=>{refreshPreview();updateDirty();});
els.audienceChecks.forEach(box=>box.addEventListener('change',()=>{
  if(box.value==='all'&&box.checked){els.audienceChecks.forEach(x=>{if(x!==box)x.checked=false});}
  else if(box.checked){const all=els.audienceChecks.find(x=>x.value==='all');if(all)all.checked=false;}
  if(!els.audienceChecks.some(x=>x.checked)){const all=els.audienceChecks.find(x=>x.value==='all');if(all)all.checked=true;}
  refreshPreview();updateDirty();
}));
[els.lang,els.date,els.title,els.category,els.slug,els.description,els.answer,els.sources,els.claims,els.citationPlacements,els.visualizations,els.translationKey,els.coverImage,els.coverAlt,els.body].filter(Boolean).forEach(el=>el.addEventListener('input',()=>{refreshPreview();updateDirty();}));
els.pinned.addEventListener('change',()=>{refreshPreview();updateDirty();});
els.title.addEventListener('blur',()=>{if(!els.slug.value)els.slug.value=slugify(els.title.value);if(!els.translationKey.value)els.translationKey.value=slugify(els.title.value);if(els.coverImage.value&&!els.coverAlt.value)els.coverAlt.value=els.title.value.trim();refreshPreview();updateDirty()});
els.citationModeChecks.forEach(box=>box.addEventListener('change',()=>{refreshPreview();updateDirty();}));
els.visualizationReview?.addEventListener('click',event=>{const b=event.target.closest('[data-viz-remove]');if(!b)return;const charts=parseJsonArray(els.visualizations?.value);charts.splice(Number(b.dataset.vizRemove),1);els.visualizations.value=JSON.stringify(charts,null,2);refreshPreview();updateDirty();});
els.sourceReview?.addEventListener('click',event=>{const button=event.target.closest('[data-source-action]');if(button)updateSource(Number(button.dataset.sourceIndex),button.dataset.sourceAction);});
els.sourceAdd?.addEventListener('click',addSourceFromComposer);
els.claimAdd?.addEventListener('click',addClaimCard);
els.claimReview?.addEventListener('click',event=>{const remove=event.target.closest('[data-claim-remove]');if(remove)removeClaim(Number(remove.dataset.claimRemove));});
els.claimReview?.addEventListener('change',event=>{const field=event.target.closest('[data-claim-field]');if(field){updateClaimField(Number(field.dataset.claimIndex),field.dataset.claimField,field.value);return;}const source=event.target.closest('[data-claim-source]');if(source)toggleClaimSource(Number(source.dataset.claimSource),source.dataset.sourceUrl,source.checked);});
$$('[data-editor-tab]').forEach(button=>button.addEventListener('click',()=>selectEditorView(button.dataset.editorTab)));
$$('[data-editor-tab]').forEach((button,index,tabs)=>button.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();let next=index;if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else next=(index+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();selectEditorView(tabs[next].dataset.editorTab);}));
els.sidebarToggle?.addEventListener('click',()=>setSidebarOpen(!els.sidebar?.classList.contains('is-open')));
els.sidebarClose?.addEventListener('click',closeSidebar);
$('#sidebarBackdrop')?.addEventListener('click',closeSidebar);
$$('[data-mobile-view]').forEach(button=>button.addEventListener('click',()=>{setMobileMore(false);setMobilePreview(false);selectEditorView(button.dataset.mobileView);window.scrollTo({top:0,behavior:'smooth'});}));
els.mobileDock?.querySelector('[data-mobile-action=\"library\"]')?.addEventListener('click',()=>setSidebarOpen(true));
els.mobileMore?.addEventListener('click',()=>setMobileMore(!document.body.classList.contains('mobile-more-open')));
mobileCommandMedia.addEventListener?.('change',syncMobileCommandHost);syncMobileCommandHost();
els.mobileBackdrop?.addEventListener('click',()=>{window.anomancerOverlays?.closeAll?.();setMobileMore(false);setMobilePreview(false);});
els.mobilePreview?.addEventListener('click',()=>setMobilePreview(true));
els.mobilePreviewClose?.addEventListener('click',()=>setMobilePreview(false));
els.mobileSave?.addEventListener('click',()=>{setMobileMore(false);els.saveDraft?.click();});
els.mobilePublish?.addEventListener('click',()=>{setMobileMore(false);els.publish?.click();});
els.mobileCore?.addEventListener('click',()=>{setMobileMore(false);if(window.anomancerShell?.navigate)window.anomancerShell.navigate('machine');else window.dispatchEvent(new CustomEvent('anomancer:shell-route',{detail:{route:'machine'}}));window.scrollTo({top:0,behavior:'smooth'});});
els.mobileSettings?.addEventListener('click',()=>{setMobileMore(false);const dialog=$('#coreSettingsDialog');if(dialog&&!dialog.open)dialog.showModal();});
document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if(document.body.classList.contains('mobile-preview-open'))setMobilePreview(false);else if(document.body.classList.contains('mobile-more-open'))setMobileMore(false);});
window.addEventListener('keydown',event=>{if(event.key==='Escape'&&els.sidebar?.classList.contains('is-open'))closeSidebar();});
els.publishDialog?.addEventListener('close',()=>{if(els.publishDialog.returnValue==='confirm')save(false);});
window.addEventListener('beforeunload',event=>{if(hasAnyUnsavedChanges()){event.preventDefault();event.returnValue='';}});
window.anomancerAdminBridge={getDraftIdentity:()=>({path:state.current?.path||'',sha:state.current?.sha||'',instanceId:state.current?.path?'':state.draftInstanceId,title:els.title.value.trim()}),getPost:()=>currentForm(Boolean(state.current?.draft)),hasUnsavedChanges:()=>state.dirty,hasAnyUnsavedChanges,getUnsavedSources:getDirtySources,confirmDiscard,isBusy:()=>state.busy,setEditorLocked,setWorkspaceContext,selectEditorView:name=>selectEditorView(name),saveDraft:()=>save(true),openPreview:()=>setMobilePreview(true),closePreview:()=>setMobilePreview(false),openPublicationSettings:()=>{selectEditorView('write');const box=$('#publishingSettings');if(box){box.open=true;box.scrollIntoView({behavior:'smooth',block:'start'});}},openDispatchLibrary:()=>setSidebarOpen(true),openOrchestraRun:()=>{selectEditorView('agents');const desk=$('#orchestraDesk');if(desk){desk.scrollIntoView({behavior:'smooth',block:'start'});desk.querySelector('button:not([disabled])')?.focus({preventScroll:true});}},updateSources:sources=>{els.sources.value=formatSourcesText(sources);refreshPreview();updateDirty();},updateCitations:placements=>{els.citationPlacements.value=JSON.stringify(placements||[],null,2);refreshPreview();updateDirty();},updateVisualizations:charts=>{els.visualizations.value=JSON.stringify(charts||[],null,2);refreshPreview();updateDirty();}};
for(const eventName of ['anomancer:workspace-ready','anomancer:workspace-change'])window.addEventListener(eventName,async event=>{const workspaceId=event.detail?.workspace?.id||selectedWorkspaceId();postsController?.abort();postsController=null;postsRequestId++;setWorkspaceContext(event.detail||{});state.current=null;state.posts=[];state.dirty=false;await loadPosts({workspaceId});});

const LAYOUT_KEY='anomancer.admin.layout.v16.0.1';
function clampLayout(value,min,max,fallback){const n=Number(value);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;}
function readLayout(){try{return JSON.parse(localStorage.getItem(LAYOUT_KEY)||'{}')||{};}catch{return {};}}
function writeLayout(next){try{localStorage.setItem(LAYOUT_KEY,JSON.stringify(next));}catch{}}
function initLayoutControls(){
  const grid=$('.editor-grid'),editorWidth=$('#editorWidth'),libraryWidth=$('#libraryWidth'),previewToggle=$('#previewToggle'),editorOut=$('#editorWidthValue'),libraryOut=$('#libraryWidthValue'),reset=$('#layoutReset'),resizer=$('#editorResizer');
  if(!grid||!editorWidth||!libraryWidth||!previewToggle)return;
  let layout={editor:56,library:320,preview:true,...readLayout()};
  const apply=()=>{
    layout.editor=clampLayout(layout.editor,42,72,56);layout.library=clampLayout(layout.library,260,460,320);layout.preview=layout.preview!==false;
    document.documentElement.style.setProperty('--editor-size',`${layout.editor}%`);
    document.documentElement.style.setProperty('--library-width',`${layout.library}px`);
    grid.classList.toggle('preview-hidden',!layout.preview);
    editorWidth.value=String(layout.editor);libraryWidth.value=String(layout.library);previewToggle.checked=layout.preview;
    if(editorOut)editorOut.value=`${layout.editor} %`;if(libraryOut)libraryOut.value=`${layout.library} px`;
    if(resizer)resizer.setAttribute('aria-valuenow',String(layout.editor));
  };
  const save=()=>{apply();writeLayout(layout);};
  editorWidth.addEventListener('input',()=>{layout.editor=Number(editorWidth.value);save();});
  libraryWidth.addEventListener('input',()=>{layout.library=Number(libraryWidth.value);save();});
  previewToggle.addEventListener('change',()=>{layout.preview=previewToggle.checked;save();});
  reset?.addEventListener('click',()=>{layout={editor:56,library:320,preview:true};save();});
  let dragging=false;
  const fromPointer=x=>{const rect=grid.getBoundingClientRect();if(rect.width<1)return;layout.editor=clampLayout(((x-rect.left)/rect.width)*100,42,72,56);save();};
  resizer?.addEventListener('pointerdown',event=>{if(window.matchMedia('(max-width:1100px)').matches)return;dragging=true;resizer.classList.add('is-dragging');resizer.setPointerCapture?.(event.pointerId);fromPointer(event.clientX);});
  resizer?.addEventListener('pointermove',event=>{if(dragging)fromPointer(event.clientX);});
  const stop=event=>{if(!dragging)return;dragging=false;resizer?.classList.remove('is-dragging');try{resizer?.releasePointerCapture?.(event.pointerId);}catch{}};
  resizer?.addEventListener('pointerup',stop);resizer?.addEventListener('pointercancel',stop);
  resizer?.addEventListener('dblclick',()=>{layout.editor=56;save();});
  resizer?.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();if(event.key==='Home')layout.editor=42;else if(event.key==='End')layout.editor=72;else layout.editor+=event.key==='ArrowRight'?2:-2;save();});
  apply();
}

initLayoutControls();
setSidebarOpen(false);
loadForm(emptyPost());session().catch(e=>{els.login.hidden=false;els.loginError.textContent=e.message});
