const q=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=v=>JSON.parse(JSON.stringify(v));
let workspace=null,template=null,constitution=null,project=null,revision=0,csrf='',active='project',baseline='',loading=false,runs=[],lastRemoved=null,conflict=null,workspaceEpoch=0,artifactRequestId=0,runsRequestId=0,artifactController=null,runsController=null;
const activeItems=new Map();
const RUN_STATUS_LABELS={queued:'Jonossa',running:'Käynnissä',paused:'Tauolla',completed:'Valmis',error:'Virhe',failed:'Virhe',cancelled:'Peruttu',canceled:'Peruttu',unknown:'Tuntematon'};
const KIND_LABELS={form:'Lomake',collection:'Kokoelma','run-explorer':'Ajohistoria','code-editor':'Koodityöpöytä','task-board':'Tehtävätaulu','test-run-list':'Testipinta','approval-review':'Hyväksyntätarkistus','release-gate':'Julkaisuportti','document-preview':'Dokumenttityöpöytä'};
const SECTION_RENDERERS=new Map();
function isMancer(){return template?.kind!=='narrative-authoring'&&template?.mancerPackage?.format==='anomancer-mancer-package/v1';}
function headers(extra={}){return headersFor(workspace?.id||'default',extra);}
function headersFor(workspaceId,extra={}){return{...extra,'X-Anomancer-Workspace':workspaceId||'default'};}
function invalidateWorkspaceRequests(){workspaceEpoch++;artifactRequestId++;runsRequestId++;artifactController?.abort();runsController?.abort();artifactController=null;runsController=null;loading=false;}
function artifactContext(){artifactController?.abort();artifactController=new AbortController();return{workspaceId:workspace?.id||'',epoch:workspaceEpoch,requestId:++artifactRequestId,signal:artifactController.signal};}
function artifactCurrent(ctx){return Boolean(ctx)&&ctx.epoch===workspaceEpoch&&ctx.requestId===artifactRequestId&&workspace?.id===ctx.workspaceId;}
function runsContext(){runsController?.abort();runsController=new AbortController();return{workspaceId:workspace?.id||'',epoch:workspaceEpoch,requestId:++runsRequestId,signal:runsController.signal};}
function runsCurrent(ctx){return Boolean(ctx)&&ctx.epoch===workspaceEpoch&&ctx.requestId===runsRequestId&&workspace?.id===ctx.workspaceId;}
async function ensureCsrf(){if(csrf)return csrf;const r=await fetch('/api/admin/auth?resource=session',{credentials:'same-origin'}),d=await r.json().catch(()=>({}));if(!r.ok||!d.authenticated)throw new Error('Admin-istunto puuttuu.');csrf=d.csrf||'';return csrf;}
function sections(){return Array.isArray(template?.editorDefinition?.sections)?template.editorDefinition.sections:[];}
function section(){return sections().find(x=>x.id===active)||sections()[0]||null;}
function rendererId(s=section()){return String(s?.renderer||s?.kind||'form');}
function getPath(obj,path=''){return String(path).split('.').filter(Boolean).reduce((v,k)=>v&&typeof v==='object'?v[k]:undefined,obj);}
function setPath(obj,path='',value){const parts=String(path).split('.').filter(Boolean);if(!parts.length)return;let cur=obj;for(const k of parts.slice(0,-1)){if(!cur[k]||typeof cur[k]!=='object'||Array.isArray(cur[k]))cur[k]={};cur=cur[k];}cur[parts.at(-1)]=value;}
function uid(prefix='item'){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;}
function status(text,tone=''){const el=q('#mancerStatus');if(el){el.textContent=text;el.dataset.tone=tone;}window.anomancerFeedback?.report?.(text,tone,'Mancer');}
function dirty(){return project!==null&&JSON.stringify(project)!==baseline;}
function renderSaveState(){const changed=dirty(),btn=q('#mancerSave'),dirtyEl=q('#mancerDirty'),globalSave=q('#workspaceSaveIndicator');if(btn){btn.textContent=changed?'Tallenna':'Tallennettu';btn.disabled=!changed||loading;}if(dirtyEl){dirtyEl.textContent=changed?'TALLENTAMATON':'TALLENNETTU';dirtyEl.dataset.dirty=changed?'true':'false';}if(globalSave&&isMancer()){globalSave.textContent=loading?'LADATAAN':changed?'TALLENTAMATON':'TALLENNETTU';globalSave.dataset.dirty=changed?'true':'false';}refreshDocumentTitle();}
function fieldInput(field,value,path,index=null,extra=''){const attrs=`data-mancer-path="${esc(path)}"${index!==null?` data-mancer-index="${index}"`:''}${extra?` ${extra}`:''}`;const mono=field.monospace?' mancer-monospace':'';if(field.type==='textarea')return`<textarea ${attrs} class="${mono.trim()}" rows="${Number(field.rows)||6}" maxlength="${Number(field.maxLength)||200000}">${esc(value||'')}</textarea>`;if(field.type==='select')return`<select ${attrs}>${(field.options||[]).map(o=>`<option value="${esc(o.value)}"${String(value??'')===String(o.value)?' selected':''}>${esc(o.label||o.value)}</option>`).join('')}</select>`;return`<input ${attrs} class="${mono.trim()}" type="text" value="${esc(value||'')}" maxlength="${Number(field.maxLength)||200000}">`;}
function fieldLabel(field,value,index=null,extra=''){return`<label><span>${esc(field.label||field.path)}</span>${fieldInput(field,value,field.path,index,extra)}</label>`;}
function renderForm(s){return`<div class="mancer-form">${(s.fields||[]).map(field=>fieldLabel(field,getPath(project,field.path))).join('')}</div>`;}
function removedLabel(item={},s={}){return item.title||item.name||item.path||s.itemLabel||'Kohde';}
function undoBanner(){if(!lastRemoved||lastRemoved.sectionId!==active)return'';return`<div class="mancer-undo" role="status"><span><strong>${esc(lastRemoved.label)}</strong> poistettiin luonnoksesta. Muutosta ei ole vielä tallennettu.</span><button class="ghost" type="button" data-mancer-undo>Kumoa poisto</button></div>`;}
function renderCollection(s){const items=Array.isArray(project?.[s.id])?project[s.id]:[];return`${undoBanner()}<div class="mancer-collection-head"><span>${items.length} ${items.length===1?'kohde':'kohdetta'}</span><button class="secondary" type="button" data-mancer-add="${esc(s.id)}">+ ${esc(s.itemLabel||'Kohde')}</button></div><div class="mancer-collection">${items.length?items.map((item,index)=>`<article class="mancer-item"><header><strong>${esc(removedLabel(item,s)||`${s.itemLabel||'Kohde'} ${index+1}`)}</strong><button class="ghost mancer-remove" type="button" data-mancer-remove="${esc(s.id)}" data-mancer-index="${index}" aria-label="Poista ${esc(removedLabel(item,s))} luonnoksesta">Poista luonnoksesta</button></header><div class="mancer-form">${(s.fields||[]).map(field=>fieldLabel({...field,monospace:field.path===s.monospaceField},item?.[field.path],index)).join('')}</div></article>`).join(''):`<div class="mancer-empty"><strong>Tyhjä näkymä</strong><p>${esc(s.emptyMessage||'Ei kohteita vielä. Lisää ensimmäinen rakenneobjekti.')}</p></div>`}</div>`;}
function runTone(run){return run?.status==='completed'?'ok':['error','failed'].includes(run?.status)?'error':'';}
function runStatus(statusValue){return RUN_STATUS_LABELS[String(statusValue||'unknown').toLowerCase()]||String(statusValue||'Tuntematon');}
function renderRuns(){return`<div class="mancer-run-toolbar"><button class="secondary" type="button" data-mancer-runs-refresh>Päivitä ajot</button><button class="ghost" type="button" data-mancer-machine>Avaa Konehuone</button></div><div class="mancer-runs">${runs.length?runs.map(run=>`<article data-tone="${runTone(run)}"><span>${esc(run.orchestra?.name||run.orchestraId||'Ajo')}</span><strong>${esc(runStatus(run.status))}</strong><small>${esc(run.id||run.orchestraRunId||'')} · ${esc(run.finishedAt||run.startedAt||'')}</small></article>`).join(''):'<div class="mancer-empty"><strong>Ei ajohistoriaa</strong><p>Tässä työtilassa ei ole vielä orkesteri- tai agenttiajoja.</p></div>'}</div>`;}
function sectionItems(s){return Array.isArray(project?.[s.id])?project[s.id]:[];}
function selectedIndex(s,items=sectionItems(s)){let index=Number(activeItems.get(s.id));if(!Number.isInteger(index)||index<0||index>=items.length)index=items.length?0:-1;if(index>=0)activeItems.set(s.id,index);return index;}
function itemTitle(item={},s={},index=0){return item.path||item.title||item.name||`${s.itemLabel||'Kohde'} ${index+1}`;}
function addButton(s,label='Lisää'){return`<button class="secondary" type="button" data-mancer-add="${esc(s.id)}">+ ${esc(label)}</button>`;}
function itemList(s,items,{kind='item',subtitle}={}){const selected=selectedIndex(s,items);return`<div class="mancer-item-index" role="list">${items.map((item,index)=>`<button type="button" role="listitem" data-mancer-select-item="${index}" data-selected="${index===selected?'true':'false'}"><strong>${esc(itemTitle(item,s,index))}</strong>${subtitle?`<small>${esc(subtitle(item,index)||'')}</small>`:''}<span>${esc(kind)}</span></button>`).join('')}</div>`;}
function lineCount(value=''){const text=String(value||'');return text?text.split(/\r?\n/).length:0;}
function renderCodeEditor(s){const items=sectionItems(s),index=selectedIndex(s,items),item=index>=0?items[index]:null;if(!item)return`${undoBanner()}<div class="mancer-workbench-empty">${addButton(s,s.itemLabel||'Tiedosto')}<div class="mancer-empty"><strong>Ei tiedostoja työtilassa</strong><p>${esc(s.emptyMessage||'Lisää ensimmäinen tiedosto tai snippet.')}</p></div></div>`;const pathField=(s.fields||[]).find(f=>f.path==='path')||{path:'path',label:'Polku',type:'text'},languageField=(s.fields||[]).find(f=>f.path==='language')||{path:'language',label:'Kieli',type:'text'},contentField=(s.fields||[]).find(f=>f.path==='content')||{path:'content',label:'Sisältö',type:'textarea',rows:18,monospace:true},notesField=(s.fields||[]).find(f=>f.path==='notes')||{path:'notes',label:'Muutosmuistiinpano',type:'textarea',rows:4};return`${undoBanner()}<div class="mancer-workbench mancer-code-workbench" data-mancer-workbench="code-editor"><aside class="mancer-workbench-nav"><header><div><span>Tiedostot</span><strong>${items.length}</strong></div>${addButton(s,'Tiedosto')}</header>${itemList(s,items,{kind:'tiedosto',subtitle:item=>item.language||''})}</aside><section class="mancer-workbench-main"><header class="mancer-focus-head"><div><span>AKTIIVINEN TIEDOSTO</span><strong>${esc(item.path||'Nimetön tiedosto')}</strong></div><button class="ghost mancer-remove" type="button" data-mancer-remove="${esc(s.id)}" data-mancer-index="${index}" aria-label="Poista ${esc(itemTitle(item,s,index))} luonnoksesta">Poista</button></header><div class="mancer-code-meta">${fieldLabel(pathField,item.path,index)}${fieldLabel(languageField,item.language,index)}</div><label class="mancer-code-editor"><span>${esc(contentField.label||'Sisältö')}</span>${fieldInput({...contentField,monospace:true},item.content,contentField.path,index)}</label>${fieldLabel(notesField,item.notes,index)}</section><aside class="mancer-workbench-inspector"><span class="mancer-inspector-kicker">KONTEKSTI</span><dl><div><dt>Polku</dt><dd>${esc(item.path||'ei määritelty')}</dd></div><div><dt>Kieli</dt><dd>${esc(item.language||'ei määritelty')}</dd></div><div><dt>Rivejä</dt><dd>${lineCount(item.content)}</dd></div><div><dt>Merkkejä</dt><dd>${String(item.content||'').length}</dd></div></dl><p>Tämä editori muokkaa vain työtilan pakettiartefaktia. Repository-write vaatii erillisen hyväksytyn soveltamisvaiheen.</p></aside></div>`;}
function statusOptions(s){return(s.fields||[]).find(field=>field.path==='status')?.options||[];}
function renderTaskBoard(s){const items=sectionItems(s),options=statusOptions(s),columns=options.length?options:[{value:'todo',label:'Avoin'},{value:'doing',label:'Työn alla'},{value:'done',label:'Valmis'},{value:'blocked',label:'Estynyt'}];return`${undoBanner()}<div class="mancer-board-head"><div><strong>${items.length} tehtävää</strong><span>Tilamuutos siirtää kortin sarakkeesta toiseen.</span></div>${addButton(s,s.itemLabel||'Tehtävä')}</div><div class="mancer-task-board" style="--mancer-board-columns:${columns.length}">${columns.map(column=>{const members=items.map((item,index)=>({item,index})).filter(x=>(x.item.status||columns[0].value)===column.value);return`<section class="mancer-task-column" data-status="${esc(column.value)}"><header><strong>${esc(column.label||column.value)}</strong><span>${members.length}</span></header><div>${members.length?members.map(({item,index})=>`<article class="mancer-task-card"><div class="mancer-task-card-head"><span>${esc(item.origin||'human')}</span><button class="ghost mancer-remove" type="button" data-mancer-remove="${esc(s.id)}" data-mancer-index="${index}" aria-label="Poista ${esc(itemTitle(item,s,index))} luonnoksesta">×</button></div>${(s.fields||[]).filter(f=>f.path==='title').map(f=>fieldLabel(f,item[f.path],index)).join('')}<div class="mancer-task-inline">${(s.fields||[]).filter(f=>['status','origin'].includes(f.path)).map(f=>fieldLabel(f,item[f.path],index)).join('')}</div>${(s.fields||[]).filter(f=>f.path==='notes').map(f=>fieldLabel(f,item[f.path],index)).join('')}</article>`).join(''):'<div class="mancer-column-empty">Ei tehtäviä</div>'}</div></section>`;}).join('')}</div>`;}
function testTone(value){return value==='passed'?'ok':value==='failed'?'error':'pending';}
function testLabel(value){return value==='passed'?'LÄPI':value==='failed'?'HYLÄTTY':'EI AJETTU';}
function renderTestRunList(s){const items=sectionItems(s),counts={passed:items.filter(x=>x.status==='passed').length,failed:items.filter(x=>x.status==='failed').length,unknown:items.filter(x=>!['passed','failed'].includes(x.status)).length};return`${undoBanner()}<div class="mancer-test-summary"><div data-tone="ok"><span>Läpi</span><strong>${counts.passed}</strong></div><div data-tone="error"><span>Hylätty</span><strong>${counts.failed}</strong></div><div data-tone="pending"><span>Ei ajettu</span><strong>${counts.unknown}</strong></div>${addButton(s,s.itemLabel||'Testiajo')}</div><div class="mancer-test-list">${items.length?items.map((item,index)=>`<article class="mancer-test-card" data-tone="${testTone(item.status)}"><header><div><span>${testLabel(item.status)}</span><strong>${esc(item.name||`Testi ${index+1}`)}</strong></div><button class="ghost mancer-remove" type="button" data-mancer-remove="${esc(s.id)}" data-mancer-index="${index}" aria-label="Poista ${esc(itemTitle(item,s,index))} luonnoksesta">Poista</button></header><div class="mancer-form mancer-test-fields">${(s.fields||[]).map(field=>fieldLabel({...field,monospace:['command','evidence'].includes(field.path)},item[field.path],index)).join('')}</div></article>`).join(''):`<div class="mancer-empty"><strong>Ei testituloksia</strong><p>${esc(s.emptyMessage||'Kirjaa ajettu testi vasta, kun tulos tai evidenssi on saatavilla.')}</p></div>`}</div>`;}
function diffMarkup(value=''){const lines=String(value||'').split(/\r?\n/);if(!String(value||'').trim())return'<div class="mancer-diff-empty">Ei diffiä kirjattuna.</div>';return`<pre class="mancer-diff-view" aria-label="Diff-esikatselu">${lines.map(line=>{const kind=line.startsWith('+')&&!line.startsWith('+++')?'add':line.startsWith('-')&&!line.startsWith('---')?'remove':line.startsWith('@@')||line.startsWith('diff ')||line.startsWith('index ')?'meta':'context';return`<span data-kind="${kind}">${esc(line)||' '}</span>`;}).join('\n')}</pre>`;}
function testSummary(){const items=Array.isArray(project?.tests)?project.tests:[],passed=items.filter(x=>x.status==='passed').length,failed=items.filter(x=>x.status==='failed').length,unknown=items.length-passed-failed;return{total:items.length,passed,failed,unknown,tone:failed?'error':items.length&&unknown===0?'ok':'pending'};}
function renderApprovalReview(s){const tests=testSummary(),review=project?.review||{},summaryField=(s.fields||[]).find(f=>f.path==='review.summary'),diffField=(s.fields||[]).find(f=>f.path==='review.diff'),testField=(s.fields||[]).find(f=>f.path==='review.testState'),decisionField=(s.fields||[]).find(f=>f.path==='review.decision');return`<div class="mancer-review-grid"><section class="mancer-review-main"><div class="mancer-review-evidence"><div data-tone="${tests.tone}"><span>Kirjatut testit</span><strong>${tests.passed}/${tests.total||0} läpi</strong><small>${tests.failed?`${tests.failed} hylättyä`:tests.unknown?`${tests.unknown} ilman lopputulosta`:'Ei hylättyjä testejä'}</small></div><div data-tone="${review.decision==='approved'?'ok':review.decision==='rejected'?'error':'pending'}"><span>Ihmisen päätös</span><strong>${esc(review.decision||'pending')}</strong><small>Vain ihminen voi hyväksyä soveltamisen.</small></div></div>${summaryField?fieldLabel(summaryField,review.summary):''}${diffField?`<label class="mancer-code-editor"><span>${esc(diffField.label)}</span>${fieldInput({...diffField,monospace:true},review.diff,diffField.path)}</label>`:''}</section><aside class="mancer-review-inspector"><span class="mancer-inspector-kicker">DIFF / EVIDENSSI</span>${diffMarkup(review.diff)}<div class="mancer-review-decisions">${testField?fieldLabel(testField,review.testState):''}${decisionField?fieldLabel(decisionField,review.decision):''}</div></aside></div>`;}
function gateState(ok,fail=false){return fail?'error':ok?'ok':'pending';}
function gateCard(label,tone,detail){return`<div data-tone="${tone}"><span>${esc(label)}</span><strong>${tone==='ok'?'VALMIS':tone==='error'?'ESTE':'ODOTTAA'}</strong><small>${esc(detail)}</small></div>`;}
function renderReleaseGate(s){const tests=testSummary(),review=project?.review||{},release=project?.release||{},gates=[['Testievidenssi',gateState(tests.total>0&&tests.failed===0&&tests.unknown===0,tests.failed>0),tests.total?`${tests.passed}/${tests.total} läpi`:'Ei kirjattuja testejä'],['Diffin tarkistus',gateState(review.decision==='approved',['rejected','changes-requested'].includes(review.decision)),`Päätös: ${review.decision||'pending'}`],['Julkaisutarkistus',gateState(release.check==='passing',release.check==='failing'),`Tila: ${release.check||'not-run'}`],['Ihmisen julkaisupäätös',gateState(release.humanApproval==='approved',release.humanApproval==='rejected'),`Päätös: ${release.humanApproval||'pending'}`]];return`<div class="mancer-release-gates">${gates.map(g=>gateCard(...g)).join('')}</div><div class="mancer-release-layout"><section><div class="mancer-form">${(s.fields||[]).map(field=>fieldLabel(field,getPath(project,field.path))).join('')}</div></section><aside class="mancer-workbench-inspector"><span class="mancer-inspector-kicker">JULKAISURAJA</span><p>Hyväksyntädata ei itsessään tee sivuvaikutusta. Korkean riskin operaatio <code>P3</code> vaatii erillisen suunnitelman, kirjoitetun hyväksynnän ja suoritusvaiheen.</p><p>Tämä hyväksyntäpinta ei suorita Git-pushia. Oletushaaraa ei kirjoiteta suoraan eikä muutospyyntöä yhdistetä automaattisesti.</p></aside></div><section class="mancer-operation-console" id="mancerOperationConsole" aria-label="Repository-, Git-, testi- ja deploy-operaatiot"><div class="mancer-empty"><strong>Operaatioiden hallinta latautuu…</strong><p>Kyvykeportit sidotaan tallennettuun artefaktirevisioon.</p></div></section>`;}
function documentPreview(value=''){const lines=String(value||'').split(/\r?\n/),blocks=[];for(const raw of lines){const line=raw.trimEnd();if(!line.trim()){blocks.push('<div class="mancer-doc-gap"></div>');continue;}const m=line.match(/^(#{1,4})\s+(.+)$/);if(m){const level=Math.min(4,m[1].length+1);blocks.push(`<h${level}>${esc(m[2])}</h${level}>`);continue;}if(/^[-*]\s+/.test(line)){blocks.push(`<p class="mancer-doc-bullet">• ${esc(line.replace(/^[-*]\s+/,''))}</p>`);continue;}blocks.push(`<p>${esc(line)}</p>`);}return blocks.join('')||'<p class="mancer-doc-placeholder">Ei esikatseltavaa sisältöä.</p>';}
function renderDocumentPreview(s){const items=sectionItems(s),index=selectedIndex(s,items),item=index>=0?items[index]:null;if(!item)return`${undoBanner()}<div class="mancer-workbench-empty">${addButton(s,s.itemLabel||'Dokumentti')}<div class="mancer-empty"><strong>Ei dokumentteja</strong><p>${esc(s.emptyMessage||'Lisää ensimmäinen dokumentti.')}</p></div></div>`;const titleField=(s.fields||[]).find(f=>f.path==='title'),kindField=(s.fields||[]).find(f=>f.path==='kind'),bodyField=(s.fields||[]).find(f=>f.path==='body');return`${undoBanner()}<div class="mancer-workbench mancer-document-workbench" data-mancer-workbench="document-preview"><aside class="mancer-workbench-nav"><header><div><span>Dokumentit</span><strong>${items.length}</strong></div>${addButton(s,'Dokumentti')}</header>${itemList(s,items,{kind:'dokumentti',subtitle:item=>item.kind||''})}</aside><section class="mancer-workbench-main"><header class="mancer-focus-head"><div><span>AKTIIVINEN DOKUMENTTI</span><strong>${esc(item.title||'Nimetön dokumentti')}</strong></div><button class="ghost mancer-remove" type="button" data-mancer-remove="${esc(s.id)}" data-mancer-index="${index}" aria-label="Poista ${esc(itemTitle(item,s,index))} luonnoksesta">Poista</button></header><div class="mancer-code-meta">${titleField?fieldLabel(titleField,item.title,index):''}${kindField?fieldLabel(kindField,item.kind,index):''}</div>${bodyField?`<label class="mancer-code-editor"><span>${esc(bodyField.label)}</span>${fieldInput({...bodyField,monospace:true},item.body,bodyField.path,index)}</label>`:''}</section><aside class="mancer-document-preview"><span class="mancer-inspector-kicker">ESIKATSELU</span><article>${documentPreview(item.body)}</article></aside></div>`;}
function registerRenderer(id,renderer){if(typeof id!=='string'||typeof renderer!=='function')return false;SECTION_RENDERERS.set(id,renderer);return true;}
registerRenderer('form',renderForm);
registerRenderer('collection',renderCollection);
registerRenderer('run-explorer',renderRuns);
registerRenderer('code-editor',renderCodeEditor);
registerRenderer('task-board',renderTaskBoard);
registerRenderer('test-run-list',renderTestRunList);
registerRenderer('approval-review',renderApprovalReview);
registerRenderer('release-gate',renderReleaseGate);
registerRenderer('document-preview',renderDocumentPreview);
function renderSectionWork(s){const renderer=SECTION_RENDERERS.get(rendererId(s))||SECTION_RENDERERS.get(s.kind)||SECTION_RENDERERS.get('form');return renderer(s);}
function contractDetails(){const p=template?.mancerPackage||{},approval=p.approvalModel||{},orchestras=p.orchestraRegistry?.orchestras||[],caps=template?.editorDefinition?.rendererCapabilities||[];return`<details class="mancer-contract-details"><summary>Sopimuksen tekniset tiedot</summary><div class="mancer-contract-strip"><div><span>Mancer-paketti</span><strong>${esc(p.id||'mancer')} ${esc(p.version||'')}</strong></div><div><span>Hyväksyntämalli</span><strong>${approval.humanFinalAuthority?'Ihmisellä lopullinen päätösvalta':'Ei määritelty'}</strong></div><div><span>Renderer-capabilityt</span><strong>${caps.length} käytössä</strong></div><div><span>Orkesterirekisteri</span><strong>${orchestras.length} määritelty</strong></div></div></details>`;}
function sectionNotice(s){return s.notice?`<div class="mancer-section-notice" data-tone="${esc(s.noticeTone||'')}"><strong>Toimivaltaraja</strong><span>${esc(s.notice)}</span></div>`:'';}
function conflictRoots(local={},remote={}){return[...new Set([...Object.keys(local||{}),...Object.keys(remote||{})])].filter(key=>JSON.stringify(local?.[key])!==JSON.stringify(remote?.[key]));}
function conflictBanner(){if(!conflict)return'';const roots=conflictRoots(conflict.local,conflict.remote),summary=conflict.remoteAvailable?(roots.length?`${roots.slice(0,6).join(', ')}${roots.length>6?` +${roots.length-6}`:''}`:'ei havaittua sisältöeroa'):'palvelinversio ei ole saatavilla',actions=conflict.remoteAvailable?'<button class="ghost" type="button" data-mancer-conflict="remote">Ota palvelinversio</button><button class="danger" type="button" data-mancer-conflict="local">Säilytä paikallinen</button>':'';return`<section class="mancer-undo" role="alert"><span><strong>Versioristiriita · paikallinen työ säilytettiin.</strong> ${conflict.remoteAvailable?`Palvelimella on revisio ${conflict.remoteRevision}, editori lähetti revision ${conflict.localRevision}.`:'Lataa turvakopio ennen sivulta poistumista.'} Muuttuneet alueet: ${esc(summary)}.</span><div class="mancer-run-toolbar"><button class="ghost" type="button" data-mancer-conflict="backup">Lataa turvakopio</button>${actions}</div></section>`;}
function renderPanel(){const root=q('#mancerPanel'),s=section();if(!root||!s)return;const work=renderSectionWork(s);root.innerHTML=`${conflictBanner()}<header class="mancer-section-head"><div><p class="kicker">${esc(template?.name||'MANCER')} / ${esc(s.label||s.id)}</p><h2 id="mancerSectionTitle">${esc(s.label||s.id)}</h2><p>${esc(s.description||'')}</p></div><div class="mancer-section-meta"><span class="mancer-authority-badge" title="Ihmisellä on lopullinen päätösvalta">Ihminen hyväksyy</span><span class="mancer-section-kind">${esc(KIND_LABELS[rendererId(s)]||KIND_LABELS[s.kind]||'Työtila')}</span></div></header>${sectionNotice(s)}<div class="mancer-work-body" aria-labelledby="mancerSectionTitle">${work}</div>${contractDetails()}`;renderSaveState();if(rendererId(s)==='release-gate')window.anomancerOperations?.mount?.({workspace,project,artifactRevision:revision,dirty:dirty()});}
function renderShell(){if(!isMancer())return;const root=q('#mancerWorkspace');if(root)root.hidden=false;q('#mancerWorkspaceName').textContent=workspace?.name||template?.name||'Mancer';q('#mancerPackageName').textContent=`TYÖMAAILMA / ${template?.name||'Mancer'}`;q('#mancerConstitution').textContent=constitution?.name||'Sopimus + ihmisen hyväksyntä';if(!sections().some(s=>s.id===active))active=sections()[0]?.id||'project';renderPanel();window.anomancerShell?.renderLocalNavigation?.();window.anomancerShell?.renderMobileNavigation?.();}
async function loadRuns(){if(!isMancer())return;const ctx=runsContext();try{const r=await fetch('/api/admin/core?resource=runs&limit=12',{credentials:'same-origin',headers:headersFor(ctx.workspaceId),signal:ctx.signal}),d=await r.json().catch(()=>({}));if(!runsCurrent(ctx))return;if(r.ok&&d.ok)runs=d.runs||d.items||[];else runs=[];}catch(error){if(error.name!=='AbortError'&&runsCurrent(ctx))runs=[];}if(runsCurrent(ctx)&&section()?.kind==='run-explorer')renderPanel();}
async function fetchRemoteArtifact(ctx){const r=await fetch('/api/admin/content?resource=mancer-artifact',{credentials:'same-origin',headers:headersFor(ctx.workspaceId),signal:ctx.signal}),d=await r.json().catch(()=>({}));if(!artifactCurrent(ctx))return null;if(!r.ok||!d.ok)throw new Error(d.message||d.error||'Palvelinversiota ei voitu ladata.');return d;}
async function loadArtifact(){if(!isMancer()||loading)return;const ctx=artifactContext();loading=true;status('Ladataan työtilan aineistoa…');try{const d=await fetchRemoteArtifact(ctx);if(!d||!artifactCurrent(ctx))return;project=d.state?.data||{};revision=Number(d.state?.revision||0);baseline=JSON.stringify(project);lastRemoved=null;conflict=null;activeItems.clear();renderShell();await loadRuns();if(artifactCurrent(ctx))status(`Työtilan aineisto ladattu · revisio ${revision}${d.store?.durable?' · pysyvä säilö':' · palvelinmuisti'}`,'ok');}catch(error){if(error.name==='AbortError'||!artifactCurrent(ctx))return;project={};baseline=JSON.stringify(project);conflict=null;activeItems.clear();renderShell();status(`Työtilan aineisto: ${error.message}`,'error');}finally{if(artifactCurrent(ctx)){loading=false;artifactController=null;renderSaveState();}}}
async function save(){if(!isMancer()||!project||loading||!dirty())return;const ctx=artifactContext(),submitted=clone(project),submittedJson=JSON.stringify(submitted),submittedRevision=revision;loading=true;try{await ensureCsrf();if(!artifactCurrent(ctx))return;status('Tallennetaan työtilan aineistoa…');const r=await fetch('/api/admin/content?resource=mancer-artifact',{method:'POST',credentials:'same-origin',headers:headersFor(ctx.workspaceId,{'Content-Type':'application/json','X-CSRF-Token':csrf}),body:JSON.stringify({data:submitted,expectedRevision:submittedRevision}),signal:ctx.signal}),d=await r.json().catch(()=>({}));if(!artifactCurrent(ctx))return;if(!r.ok||!d.ok){if(r.status===403)csrf='';throw Object.assign(new Error(d.message||d.error||'Tallennus epäonnistui.'),{code:d.error});}const saved=d.state?.data||submitted;revision=Number(d.state?.revision||submittedRevision+1);baseline=JSON.stringify(saved);if(JSON.stringify(project)===submittedJson)project=clone(saved);lastRemoved=null;conflict=null;status(JSON.stringify(project)===baseline?`Tallennettu · revisio ${revision} · koodivarastoa ei muutettu`:`Revisio ${revision} tallennettu · uudemmat paikalliset muutokset odottavat tallennusta`,'ok');}catch(error){if(error.name==='AbortError'||!artifactCurrent(ctx))return;if(error.code==='MANCER_ARTIFACT_REVISION_CONFLICT'){try{const local=clone(project),d=await fetchRemoteArtifact(ctx);if(!d)return;conflict={local,remote:clone(d.state?.data||{}),localRevision:submittedRevision,remoteRevision:Number(d.state?.revision||submittedRevision),remoteAvailable:true,capturedAt:new Date().toISOString()};status('Versioristiriita. Paikallinen työ säilytettiin — valitse konfliktipalkista ratkaisu.','error');}catch(loadError){if(loadError.name!=='AbortError'&&artifactCurrent(ctx)){conflict={local:clone(project),remote:null,localRevision:submittedRevision,remoteRevision:null,remoteAvailable:false,capturedAt:new Date().toISOString()};status(`Versioristiriita. Paikallinen työ säilytettiin, mutta palvelinversio ei auennut: ${loadError.message}`,'error');}}}else status(error.message,'error');}finally{if(artifactCurrent(ctx)){loading=false;artifactController=null;renderPanel();}}}
function downloadConflict(){if(!conflict)return;const payload={format:'anomancer-mancer-conflict-backup/v1',workspaceId:workspace?.id||'',packageId:template?.mancerPackage?.id||'',capturedAt:conflict.capturedAt,localRevision:conflict.localRevision,remoteRevision:conflict.remoteRevision,localData:conflict.local,remoteData:conflict.remote},blob=new Blob([`${JSON.stringify(payload,null,2)}\n`],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${workspace?.id||'mancer'}-conflict-${Date.now()}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Konfliktin paikallinen ja palvelinversio ladattiin turvakopiona.','ok');}
async function resolveConflict(action){if(!conflict)return;if(action==='backup'){downloadConflict();return;}if(!conflict.remoteAvailable){status('Palvelinversio ei ole saatavilla. Lataa paikallinen turvakopio ennen uudelleenlatausta.','error');return;}if(action==='remote'){const approved=await window.anomancerDialogs.confirm('Paikallinen työ korvataan palvelinversiolla.',{title:'Otetaan palvelinversio käyttöön?',details:'Lataa ensin turvakopio, jos haluat säilyttää paikallisen version erillisenä tiedostona.',confirmLabel:'Ota palvelinversio',destructive:true});if(!approved)return;project=clone(conflict.remote);revision=conflict.remoteRevision;baseline=JSON.stringify(project);conflict=null;lastRemoved=null;renderPanel();status(`Palvelinversio otettiin käyttöön · revisio ${revision}`,'ok');return;}if(action==='local'){const approved=await window.anomancerDialogs.confirm('Paikallinen versio säilytetään editorissa uusimman palvelinrevision päällä.',{title:'Säilytetäänkö paikallinen versio?',details:'Seuraava tallennus korvaa palvelimen nykyisen version tällä paikallisella kokonaisuudella. Turvakopion lataamista suositellaan ennen jatkamista.',confirmLabel:'Säilytä paikallinen',destructive:true});if(!approved)return;project=clone(conflict.local);revision=conflict.remoteRevision;baseline=JSON.stringify(conflict.remote);conflict=null;renderPanel();status(`Paikallinen versio säilytettiin. Tarkista muutokset ja tallenna revision ${revision} päälle.`,'ok');}}
function selectSection(id){if(!isMancer()||!sections().some(s=>s.id===id))return false;active=id;renderPanel();if(section()?.kind==='run-explorer')loadRuns();window.dispatchEvent(new CustomEvent('anomancer:mancer-section-change',{detail:{section:id}}));refreshDocumentTitle();return true;}
function sectionFromNavigation(){try{const url=new URL(location.href),workspaceId=url.searchParams.get('workspace'),view=url.searchParams.get('view'),id=url.searchParams.get('section');if(workspaceId===workspace?.id&&(!view||view==='workspace')&&sections().some(s=>s.id===id))return id;}catch{}return'';}
function refreshDocumentTitle(){if(!isMancer())return;const s=section();document.title=`${dirty()?'● ':''}Lighthouse · ${workspace?.name||template?.name||'Mancer'} · ${s?.label||''}`;}
function applyWorkspace(detail){invalidateWorkspaceRequests();const next=detail||window.anomancerWorkspaces?.getDetail?.()||{};workspace=next.workspace||null;template=next.template||null;constitution=next.constitution||null;conflict=null;activeItems.clear();const root=q('#mancerWorkspace');if(!isMancer()){if(root)root.hidden=true;project=null;baseline='';lastRemoved=null;return;}active=sectionFromNavigation()||template.editorDefinition?.sections?.[0]?.id||'project';loadArtifact();}
function addItem(sectionId){const s=sections().find(x=>x.id===sectionId);if(!s||!project)return;if(!Array.isArray(project[s.id]))project[s.id]=[];const item={id:uid(s.id)};for(const f of s.fields||[])item[f.path]=f.type==='select'?(f.options?.[0]?.value||''):'';project[s.id].push(item);activeItems.set(s.id,project[s.id].length-1);lastRemoved=null;renderPanel();}
q('#mancerSave')?.addEventListener('click',save);
q('#mancerPanel')?.addEventListener('input',event=>{const el=event.target.closest?.('[data-mancer-path]');if(!el||!project)return;const index=el.dataset.mancerIndex,path=el.dataset.mancerPath;if(index!==undefined){const arr=project[active];if(Array.isArray(arr)&&arr[Number(index)])arr[Number(index)][path]=el.value;}else setPath(project,path,el.value);renderSaveState();if(rendererId()==='document-preview'&&path==='body'){const preview=q('.mancer-document-preview article');if(preview)preview.innerHTML=documentPreview(el.value);}if(rendererId()==='approval-review'&&path==='review.diff'){const preview=q('.mancer-diff-view,.mancer-diff-empty');if(preview){const holder=preview.parentElement;preview.outerHTML=diffMarkup(el.value);if(holder)holder.scrollTop=holder.scrollTop;}}});
q('#mancerPanel')?.addEventListener('change',event=>{const el=event.target.closest?.('[data-mancer-path]');if(!el)return;renderSaveState();if(['task-board','test-run-list','approval-review','release-gate'].includes(rendererId()))renderPanel();});
q('#mancerPanel')?.addEventListener('click',event=>{const conflictAction=event.target.closest?.('[data-mancer-conflict]');if(conflictAction){resolveConflict(conflictAction.dataset.mancerConflict);return;}const select=event.target.closest?.('[data-mancer-select-item]');if(select){activeItems.set(active,Number(select.dataset.mancerSelectItem));renderPanel();return;}const add=event.target.closest?.('[data-mancer-add]');if(add){addItem(add.dataset.mancerAdd);return;}const rem=event.target.closest?.('[data-mancer-remove]');if(rem){const arr=project[rem.dataset.mancerRemove],i=Number(rem.dataset.mancerIndex),s=sections().find(x=>x.id===rem.dataset.mancerRemove);if(Array.isArray(arr)&&arr[i]){const [item]=arr.splice(i,1);activeItems.set(rem.dataset.mancerRemove,Math.max(0,Math.min(i,arr.length-1)));lastRemoved={sectionId:rem.dataset.mancerRemove,index:i,item:clone(item),label:removedLabel(item,s)};status('Kohde poistettiin luonnoksesta. Voit kumota poiston ennen tallennusta.','');renderPanel();}return;}if(event.target.closest?.('[data-mancer-undo]')&&lastRemoved){const arr=project[lastRemoved.sectionId];if(Array.isArray(arr)){arr.splice(Math.min(lastRemoved.index,arr.length),0,lastRemoved.item);activeItems.set(lastRemoved.sectionId,Math.min(lastRemoved.index,arr.length-1));status('Poisto kumottiin.','ok');lastRemoved=null;renderPanel();}return;}if(event.target.closest?.('[data-mancer-runs-refresh]'))loadRuns();if(event.target.closest?.('[data-mancer-machine]'))window.dispatchEvent(new CustomEvent('anomancer:shell-route',{detail:{route:'machine'}}));});
window.addEventListener('anomancer:workspace-ready',e=>applyWorkspace(e.detail));
window.addEventListener('anomancer:workspace-change',e=>applyWorkspace(e.detail));
window.addEventListener('anomancer:admin-ready',()=>applyWorkspace());
window.anomancerDirty?.register?.('mancer','Mancer-työtila',dirty);
window.anomancerMancer={isActive:isMancer,selectSection,activeSection:()=>active,save,hasUnsavedChanges:dirty,refreshDocumentTitle,load:loadArtifact,getData:()=>project?clone(project):null,registerRenderer,rendererCapabilities:()=>[...SECTION_RENDERERS.keys()]};
if(window.anomancerWorkspaces?.current?.())applyWorkspace(window.anomancerWorkspaces.getDetail?.());
