const q=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let workspace=null,template=null,project=null,revision=0,csrf='',active='project',baseline='',loading=false,runs=[];
function isMancer(){return template?.mancerPackage?.format==='anomancer-mancer-package/v1';}
function headers(extra={}){return{...extra,'X-Anomancer-Workspace':workspace?.id||'default'};}
async function ensureCsrf(){if(csrf)return csrf;const r=await fetch('/api/admin/auth?resource=session',{credentials:'same-origin'}),d=await r.json().catch(()=>({}));if(!r.ok||!d.authenticated)throw new Error('Admin-session puuttuu.');csrf=d.csrf||'';return csrf;}
function sections(){return Array.isArray(template?.editorDefinition?.sections)?template.editorDefinition.sections:[];}
function section(){return sections().find(x=>x.id===active)||sections()[0]||null;}
function getPath(obj,path=''){return String(path).split('.').filter(Boolean).reduce((v,k)=>v&&typeof v==='object'?v[k]:undefined,obj);}
function setPath(obj,path='',value){const parts=String(path).split('.').filter(Boolean);if(!parts.length)return;let cur=obj;for(const k of parts.slice(0,-1)){if(!cur[k]||typeof cur[k]!=='object'||Array.isArray(cur[k]))cur[k]={};cur=cur[k];}cur[parts.at(-1)]=value;}
function uid(prefix='item'){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;}
function status(text,tone=''){const el=q('#mancerStatus');if(el){el.textContent=text;el.dataset.tone=tone;}}
function dirty(){return project!==null&&JSON.stringify(project)!==baseline;}
function renderSaveState(){const btn=q('#mancerSave'),dirtyEl=q('#mancerDirty');if(btn){btn.textContent=dirty()?'Tallenna':'Tallennettu';btn.disabled=!dirty()||loading;}if(dirtyEl){dirtyEl.textContent=dirty()?'TALLENTAMATON':'TALLENNETTU';dirtyEl.dataset.dirty=dirty()?'true':'false';}refreshDocumentTitle();}
function fieldInput(field,value,path,index=null){const attrs=`data-mancer-path="${esc(path)}"${index!==null?` data-mancer-index="${index}"`:''}`;const mono=field.monospace?' mancer-monospace':'';if(field.type==='textarea')return`<textarea ${attrs} class="${mono.trim()}" rows="${Number(field.rows)||6}" maxlength="${Number(field.maxLength)||200000}">${esc(value||'')}</textarea>`;if(field.type==='select')return`<select ${attrs}>${(field.options||[]).map(o=>`<option value="${esc(o.value)}"${String(value??'')===String(o.value)?' selected':''}>${esc(o.label||o.value)}</option>`).join('')}</select>`;return`<input ${attrs} class="${mono.trim()}" type="text" value="${esc(value||'')}" maxlength="${Number(field.maxLength)||200000}">`;}
function renderForm(s){return`<div class="mancer-form">${(s.fields||[]).map(field=>`<label><span>${esc(field.label||field.path)}</span>${fieldInput(field,getPath(project,field.path),field.path)}</label>`).join('')}</div>`;}
function renderCollection(s){const items=Array.isArray(project?.[s.id])?project[s.id]:[];return`<div class="mancer-collection-head"><span>${items.length} kohdetta</span><button class="secondary" type="button" data-mancer-add="${esc(s.id)}">+ ${esc(s.itemLabel||'Kohde')}</button></div><div class="mancer-collection">${items.length?items.map((item,index)=>`<article class="mancer-item"><header><strong>${esc(item.title||item.name||item.path||`${s.itemLabel||'Kohde'} ${index+1}`)}</strong><button class="ghost" type="button" data-mancer-remove="${esc(s.id)}" data-mancer-index="${index}">Poista</button></header><div class="mancer-form">${(s.fields||[]).map(field=>`<label><span>${esc(field.label||field.path)}</span>${fieldInput({...field,monospace:field.path===s.monospaceField},item?.[field.path],field.path,index)}</label>`).join('')}</div></article>`).join(''):'<div class="mancer-empty">Ei kohteita vielä. Lisää ensimmäinen rakenneobjekti.</div>'}</div>`;}
function runTone(run){return run?.status==='completed'?'ok':run?.status==='error'?'error':'';}
function renderRuns(){return`<div class="mancer-run-toolbar"><button class="secondary" type="button" data-mancer-runs-refresh>Päivitä ajot</button><button class="ghost" type="button" data-mancer-machine>Avaa Konehuone</button></div><div class="mancer-runs">${runs.length?runs.map(run=>`<article data-tone="${runTone(run)}"><span>${esc(run.orchestra?.name||run.orchestraId||'Ajo')}</span><strong>${esc(run.status||'unknown')}</strong><small>${esc(run.id||run.orchestraRunId||'')} · ${esc(run.finishedAt||run.startedAt||'')}</small></article>`).join(''):'<div class="mancer-empty">Tässä työtilassa ei ole vielä ajohistoriaa.</div>'}</div>`;}
function contractStrip(){const p=template?.mancerPackage||{},approval=p.approvalModel||{},orchestras=p.orchestraRegistry?.orchestras||[];return`<aside class="mancer-contract-strip"><div><span>Package</span><strong>${esc(p.id||'mancer')} ${esc(p.version||'')}</strong></div><div><span>Approval</span><strong>${approval.humanFinalAuthority?'Human final authority':'—'}</strong></div><div><span>Orchestra Registry</span><strong>${orchestras.length} määritelty</strong></div><div><span>Archive</span><strong>${p.archivePolicy?.automaticModelMemory===false?'Ei automaattista mallimuistia':'—'}</strong></div></aside>`;}
function renderPanel(){const root=q('#mancerPanel'),s=section();if(!root||!s)return;root.innerHTML=`<header class="mancer-section-head"><div><p class="kicker">${esc(template?.name||'MANCER')} / ${esc(s.id.toUpperCase())}</p><h2>${esc(s.label||s.id)}</h2><p>${esc(s.description||'')}</p></div><span>${esc(s.kind||'section')}</span></header>${contractStrip()}${s.kind==='collection'?renderCollection(s):s.kind==='run-explorer'?renderRuns():renderForm(s)}`;renderSaveState();}
function renderShell(){if(!isMancer())return;const root=q('#mancerWorkspace');if(root)root.hidden=false;q('#mancerWorkspaceName').textContent=workspace?.name||template?.name||'Mancer';q('#mancerPackageName').textContent=`${template?.name||'Mancer'} · package ${template?.mancerPackage?.version||''}`;q('#mancerConstitution').textContent=template?.mancerPackage?.approvalModel?.humanFinalAuthority?'Constitution + human approval':'Package contract';if(!sections().some(s=>s.id===active))active=sections()[0]?.id||'project';renderPanel();}
async function loadRuns(){if(!isMancer())return;runs=[];try{const r=await fetch('/api/admin/core?resource=runs&limit=12',{credentials:'same-origin',headers:headers()}),d=await r.json().catch(()=>({}));if(r.ok&&d.ok)runs=d.runs||d.items||[];}catch{}if(section()?.kind==='run-explorer')renderPanel();}
async function loadArtifact(){if(!isMancer()||loading)return;loading=true;status('Ladataan Mancer Artifact Storea…');try{const r=await fetch('/api/admin/content?resource=mancer-artifact',{credentials:'same-origin',headers:headers()}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.message||d.error||'Mancer-artefaktia ei voitu ladata.');project=d.state?.data||{};revision=Number(d.state?.revision||0);baseline=JSON.stringify(project);renderShell();await loadRuns();status(`Mancer Artifact Store · revisio ${revision}${d.store?.durable?' · pysyvä':' · palvelinmuisti'}`,'ok');}catch(error){project={};baseline=JSON.stringify(project);renderShell();status(`Mancer Artifact Store: ${error.message}`,'error');}finally{loading=false;renderSaveState();}}
async function save(){if(!isMancer()||!project||loading||!dirty())return;loading=true;try{await ensureCsrf();status('Tallennetaan package-artefaktia…');const r=await fetch('/api/admin/content?resource=mancer-artifact',{method:'POST',credentials:'same-origin',headers:headers({'Content-Type':'application/json','X-CSRF-Token':csrf}),body:JSON.stringify({data:project,expectedRevision:revision})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){if(r.status===403)csrf='';throw Object.assign(new Error(d.message||d.error||'Tallennus epäonnistui.'),{code:d.error});}project=d.state?.data||project;revision=Number(d.state?.revision||revision+1);baseline=JSON.stringify(project);status(`Tallennettu · revisio ${revision} · ei sovellettu repositoryyn`,'ok');}catch(error){status(error.message,'error');if(error.code==='MANCER_ARTIFACT_REVISION_CONFLICT')await loadArtifact();}finally{loading=false;renderPanel();}}
function selectSection(id){if(!isMancer()||!sections().some(s=>s.id===id))return false;active=id;renderPanel();if(section()?.kind==='run-explorer')loadRuns();window.dispatchEvent(new CustomEvent('anomancer:mancer-section-change',{detail:{section:id}}));refreshDocumentTitle();return true;}
function refreshDocumentTitle(){if(!isMancer())return;const s=section();document.title=`${dirty()?'● ':''}Anomancer Core · ${workspace?.name||template?.name||'Mancer'} · ${s?.label||''}`;}
function applyWorkspace(detail){const next=detail||window.anomancerWorkspaces?.getDetail?.()||{};workspace=next.workspace||null;template=next.template||null;const root=q('#mancerWorkspace');if(!isMancer()){if(root)root.hidden=true;project=null;baseline='';return;}active=template.editorDefinition?.sections?.[0]?.id||'project';loadArtifact();}
q('#mancerSave')?.addEventListener('click',save);
q('#mancerPanel')?.addEventListener('input',event=>{const el=event.target.closest?.('[data-mancer-path]');if(!el||!project)return;const index=el.dataset.mancerIndex,path=el.dataset.mancerPath;if(index!==undefined){const arr=project[active];if(Array.isArray(arr)&&arr[Number(index)])arr[Number(index)][path]=el.value;}else setPath(project,path,el.value);renderSaveState();});
q('#mancerPanel')?.addEventListener('change',event=>{if(event.target.matches?.('[data-mancer-path]'))renderSaveState();});
q('#mancerPanel')?.addEventListener('click',event=>{const add=event.target.closest?.('[data-mancer-add]');if(add){const s=sections().find(x=>x.id===add.dataset.mancerAdd);if(!s)return;if(!Array.isArray(project[s.id]))project[s.id]=[];const item={id:uid(s.id)};for(const f of s.fields||[])item[f.path]=f.type==='select'?(f.options?.[0]?.value||''):'';project[s.id].push(item);renderPanel();return;}const rem=event.target.closest?.('[data-mancer-remove]');if(rem){const arr=project[rem.dataset.mancerRemove],i=Number(rem.dataset.mancerIndex);if(Array.isArray(arr)&&arr[i]){arr.splice(i,1);renderPanel();}return;}if(event.target.closest?.('[data-mancer-runs-refresh]'))loadRuns();if(event.target.closest?.('[data-mancer-machine]'))window.dispatchEvent(new CustomEvent('anomancer:shell-route',{detail:{route:'machine'}}));});
window.addEventListener('anomancer:workspace-ready',e=>applyWorkspace(e.detail));
window.addEventListener('anomancer:workspace-change',e=>applyWorkspace(e.detail));
window.addEventListener('anomancer:admin-ready',()=>applyWorkspace());
window.anomancerMancer={isActive:isMancer,selectSection,activeSection:()=>active,save,hasUnsavedChanges:dirty,refreshDocumentTitle,load:loadArtifact,getData:()=>project?JSON.parse(JSON.stringify(project)):null};
