const q=s=>document.querySelector(s);
const panel=q('#corePanel');
const LEDGER_PREFIX='anomancer.core.run-ledger.v15.9';
const POLICY_PREFIX='anomancer.core.policy-log.v15.9';
let snapshot=null,openAgentId='',runtimeState={format:'anomancer-runtime-store/v3',workspaceId:'default',revision:0,updatedAt:'',profiles:{}},runtimeStore=null,csrf='',runData={runs:[],usage:null,chainOk:true,store:null},openRun=null;
function workspaceId(){return window.anomancerWorkspaces?.currentId?.()||'default';}
function wsHeaders(extra={}){return window.anomancerWorkspaces?.headers?.(extra)||{...extra,'X-Anomancer-Workspace':workspaceId()};}
function ledgerKey(){return `${LEDGER_PREFIX}.${workspaceId()}`;}
function policyKey(){return `${POLICY_PREFIX}.${workspaceId()}`;}

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function stable(value){if(Array.isArray(value))return `[${value.map(stable).join(',')}]`;if(value&&typeof value==='object')return `{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k])}`).join(',')}}`;return JSON.stringify(value);}
async function sha256(value){const bytes=new TextEncoder().encode(String(value));const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function readLedger(){try{const v=JSON.parse(localStorage.getItem(ledgerKey())||'{"format":"anomancer-run-ledger/v1","entries":[]}');return v&&Array.isArray(v.entries)?v:{format:'anomancer-run-ledger/v1',entries:[]};}catch{return{format:'anomancer-run-ledger/v1',entries:[]};}}
async function verifyLedger(ledger=readLedger()){
  let previous='GENESIS';
  for(const entry of ledger.entries){const payload={previousHash:previous,receipt:entry.receipt};const expected=await sha256(stable(payload));if(entry.previousHash!==previous||entry.entryHash!==expected)return false;previous=entry.entryHash;}
  return true;
}
async function appendReceipt(receipt){
  if(!receipt?.id)return;
  const ledger=readLedger();if(ledger.entries.some(entry=>entry.receipt?.id===receipt.id))return;
  const previousHash=ledger.entries.at(-1)?.entryHash||'GENESIS';const entryHash=await sha256(stable({previousHash,receipt}));
  ledger.entries.push({previousHash,entryHash,receipt});localStorage.setItem(ledgerKey(),JSON.stringify(ledger));await render();
}

function readPolicyStore(){try{const value=JSON.parse(localStorage.getItem(policyKey())||'{"format":"anomancer-policy-log/v1","entries":[]}');return value&&Array.isArray(value.entries)?value:{format:'anomancer-policy-log/v1',entries:[]};}catch{return{format:'anomancer-policy-log/v1',entries:[]};}}
function appendPolicyDecision(decision){if(!decision?.decisionId)return;const store=readPolicyStore();if(store.entries.some(item=>item?.decisionId===decision.decisionId))return;store.entries.push(decision);store.entries=store.entries.slice(-100);localStorage.setItem(policyKey(),JSON.stringify(store));render();}
function policyEvents(receipts=[]){const fromRuns=receipts.flatMap(receipt=>Array.isArray(receipt?.toolPolicy)?receipt.toolPolicy:[]);const blocked=readPolicyStore().entries||[];const map=new Map();for(const item of [...fromRuns,...blocked])if(item?.decisionId)map.set(item.decisionId,item);return [...map.values()].sort((a,b)=>String(b.decidedAt||'').localeCompare(String(a.decidedAt||'')));}

function storeModeFi(value){return({memory:'muisti',"github-tag":'GitHub-tagi',unavailable:'ei saatavilla'}[String(value||'').toLowerCase()]||'palvelin');}
function statusFi(value){return({completed:'Valmis',degraded:'Heikentynyt',failed:'Epäonnistui',aborted:'Keskeytetty',stopped:'Pysäytetty',checkpoint:'Tarkistuspiste',running:'Ajossa',pending:'Odottaa',approved:'Hyväksytty',rejected:'Hylätty'}[String(value||'').toLowerCase()]||String(value||'—'));}
function outcomeFi(value){return({allow:'SALLI',deny:'ESTÄ',human_required:'IHMINEN VAADITAAN'}[String(value||'').toLowerCase()]||String(value||'').toUpperCase());}
function actorFi(value){return value==='human'?'ihminen':'agentti';}
function riskFi(value){return({low:'matala',medium:'keskitaso',high:'korkea',critical:'kriittinen',unknown:'tuntematon'}[String(value||'').toLowerCase()]||String(value||'tuntematon'));}

function toolStateForAgent(agent,tool){if(tool?.actor==='human')return{label:'VAIN IHMINEN',kind:'gate'};if((agent?.tools||[]).includes(tool?.id))return{label:'SALLI',kind:'allow'};return{label:'ESTÄ',kind:'deny'};}
function modelRouteFor(agent){return (snapshot?.modelRoutes||[]).find(route=>route.id===agent?.modelRoute)||null;}
function modelTargetById(id){return (snapshot?.modelRouter?.targets||[]).find(target=>target.id===id)||null;}
function providerById(id){return (snapshot?.modelRouter?.providers||[]).find(provider=>provider.id===id)||null;}
function renderTools(){const root=q('#coreTools');if(!root||!snapshot)return;const users=new Map();for(const agent of snapshot.agents||[])for(const tool of agent.tools||[]){const list=users.get(tool)||[];list.push(agent.label||agent.id);users.set(tool,list);}root.innerHTML=(snapshot.tools||[]).map(tool=>`<article data-risk="${esc(tool.risk||'unknown')}"><div><span>${esc(tool.id)}</span><strong>${esc(tool.label||tool.id)}</strong></div><p>${esc(tool.description||'')}</p><dl><div><dt>Riski</dt><dd>${esc(riskFi(tool.risk))}</dd></div><div><dt>Toimija</dt><dd>${esc(actorFi(tool.actor))}</dd></div><div><dt>Agentit</dt><dd>${esc((users.get(tool.id)||[]).join(', ')||'ei agentteja')}</dd></div><div><dt>Portti</dt><dd>${tool.humanApproval?'IHMINEN':'VÄLITTÄJÄ'}</dd></div></dl><code>${esc(String(tool.toolHash||'').slice(0,16))}…</code></article>`).join('');}
function renderPolicyLog(events=[]){const root=q('#corePolicyLog');if(!root)return;root.innerHTML=events.length?events.slice(0,20).map(item=>`<article data-outcome="${esc(item.outcome||'deny')}"><div><strong>${esc(item.toolId||'työkalu')}</strong><span>${esc(item.agentId||'')}</span></div><div><span>${esc(outcomeFi(item.outcome))}</span><span>${esc(item.reason||'')}</span><time>${item.decidedAt?esc(new Date(item.decidedAt).toLocaleString('fi-FI')):'—'}</time></div></article>`).join(''):'<p class="core-empty">Ei käytäntöpäätöksiä vielä. Ensimmäinen oikea työkalupyyntö avaa lokin.</p>';}

function renderModelRouter(){const root=q('#coreModelRouter');if(!root||!snapshot)return;const providers=snapshot.modelRouter?.providers||[];const routes=snapshot.modelRoutes||[];root.innerHTML=`<div class="core-router-providers">${providers.map(provider=>`<article data-configured="${provider.configured?'yes':'no'}"><div><strong>${esc(provider.label||provider.id)}</strong><span>${provider.configured?'KONFIGUROITU':'POIS KÄYTÖSTÄ'}</span></div><small>${esc((provider.supports||[]).join(' · '))}</small></article>`).join('')}</div><div class="core-router-routes">${routes.map(route=>`<article><div><strong>${esc(route.id)}</strong><span>${esc(route.defaultTarget)}</span></div><p>${(route.allowedTargets||[]).map(id=>{const target=modelTargetById(id);return `<span data-configured="${target?.configured?'yes':'no'}">${esc(id)}${target?.model?` · ${esc(target.model)}`:''}</span>`;}).join('')}</p></article>`).join('')}</div>`;}
function budget(agent){const n=Number(agent?.budget?.maxOutputTokens||0);return n?`${n.toLocaleString('fi-FI')} tok`:'—';}
function fallbackRuntime(agent){
  if(!agent)return null;const policy=agent.runtimePolicy||{};const route=modelRouteFor(agent),allowed=[...(route?.allowedTargets||[])],min=Math.max(1,Number(policy.minOutputTokens||1000)),max=Math.max(min,Number(policy.maxOutputTokens||agent.budget?.maxOutputTokens||min));
  return {format:'anomancer-agent-runtime/v1',agentId:agent.id,contractHash:agent.contractHash,active:true,maxOutputTokens:Number(agent.budget?.maxOutputTokens||min),modelTarget:route?.defaultTarget||allowed[0]||'',limits:{minOutputTokens:min,maxOutputTokens:max,modelTargets:allowed}};
}
function runtimeForAgent(id){const agent=snapshot?.agents?.find(item=>item.id===id);return runtimeState?.profiles?.[id]||fallbackRuntime(agent);}
function getRuntimeProfiles(){if(!snapshot)return {...(runtimeState?.profiles||{})};return Object.fromEntries(snapshot.agents.map(agent=>[agent.id,runtimeForAgent(agent.id)]));}
async function ensureCsrf(){if(csrf)return csrf;const r=await fetch('/api/admin/auth?resource=session',{credentials:'same-origin'}),d=await r.json().catch(()=>({}));if(!r.ok||!d.authenticated)throw new Error('Admin-session puuttuu.');csrf=d.csrf||'';return csrf;}
async function loadRuntime(){
  const r=await fetch('/api/admin/core?resource=runtime',{credentials:'same-origin',headers:wsHeaders()}),d=await r.json().catch(()=>({}));
  if(!r.ok||!d.ok)throw Object.assign(new Error(d.message||'Palvelinpuolen ajoprofiili ei auennut.'),{code:d.error||'RUNTIME_LOAD'});
  runtimeState=d.runtime||runtimeState;runtimeStore=d.store||null;return runtimeState;
}
async function saveRuntimeProfile(id,patch={}){
  await ensureCsrf();const r=await fetch('/api/admin/core?resource=runtime',{method:'PUT',credentials:'same-origin',headers:wsHeaders({'Content-Type':'application/json','X-CSRF-Token':csrf}),body:JSON.stringify({agentId:id,profile:patch,expectedRevision:runtimeState.revision})});
  const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){if(r.status===403)csrf='';throw Object.assign(new Error(d.message||'Ajoprofiilin tallennus epäonnistui.'),{code:d.error||'RUNTIME_SAVE'});}
  runtimeState=d.runtime;runtimeStore=d.store||runtimeStore;const next=runtimeForAgent(id);window.dispatchEvent(new CustomEvent('anomancer:agent-runtime-change',{detail:{agentId:id,profile:next,profiles:getRuntimeProfiles(),revision:runtimeState.revision}}));return next;
}
async function resetRuntimeProfile(id){
  await ensureCsrf();const r=await fetch('/api/admin/core?resource=runtime',{method:'DELETE',credentials:'same-origin',headers:wsHeaders({'Content-Type':'application/json','X-CSRF-Token':csrf}),body:JSON.stringify({agentId:id,expectedRevision:runtimeState.revision})});
  const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){if(r.status===403)csrf='';throw Object.assign(new Error(d.message||'Ajoprofiilin palautus epäonnistui.'),{code:d.error||'RUNTIME_RESET'});}
  runtimeState=d.runtime;runtimeStore=d.store||runtimeStore;const next=runtimeForAgent(id);window.dispatchEvent(new CustomEvent('anomancer:agent-runtime-change',{detail:{agentId:id,profile:next,profiles:getRuntimeProfiles(),revision:runtimeState.revision}}));return next;
}
async function createRuntimeSnapshot(orchestraRunId,orchestraId='editorial'){
  await ensureCsrf();const r=await fetch('/api/admin/core?resource=runtime',{method:'POST',credentials:'same-origin',headers:wsHeaders({'Content-Type':'application/json','X-CSRF-Token':csrf}),body:JSON.stringify({action:'snapshot',orchestraRunId,orchestraId})});
  const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){if(r.status===403)csrf='';throw Object.assign(new Error(d.message||'Ajoprofiilin tilannekuvan luonti epäonnistui.'),{code:d.error||'RUNTIME_SNAPSHOT'});}
  return d;
}
async function loadRuns(){
  const params=new URLSearchParams({limit:'40'});const status=q('#coreRunFilterStatus')?.value||'',agent=q('#coreRunFilterAgent')?.value||'',provider=q('#coreRunFilterProvider')?.value||'',orchestra=q('#coreRunFilterOrchestra')?.value||'';if(status)params.set('status',status);if(agent)params.set('agent',agent);if(provider)params.set('provider',provider);if(orchestra)params.set('orchestra',orchestra);
  const r=await fetch(`/api/admin/core?resource=runs&${params}`,{credentials:'same-origin',headers:wsHeaders()}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw Object.assign(new Error(d.message||'Ajojen tarkastelu ei auennut.'),{code:d.error||'RUN_LOAD'});runData={runs:d.runs||[],usage:d.usage||null,chainOk:d.chainOk!==false,store:d.store||null};return runData;
}
async function loadRunDetail(id){const r=await fetch(`/api/admin/core?resource=runs&id=${encodeURIComponent(id)}`,{credentials:'same-origin',headers:wsHeaders()}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.message||'Ajon tietoja ei löytynyt.');return d.run;}
function fmtCost(usage){const priced=Number(usage?.pricedReceipts||0);return priced?`${Number(usage?.estimatedCostEuro||0).toFixed(4)} €`:'—';}
function populateRunFilters(){if(!snapshot)return;const agent=q('#coreRunFilterAgent'),provider=q('#coreRunFilterProvider'),orch=q('#coreRunFilterOrchestra');if(agent&&agent.options.length<=1)agent.insertAdjacentHTML('beforeend',(snapshot.agents||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.label||x.id)}</option>`).join(''));if(provider&&provider.options.length<=1)provider.insertAdjacentHTML('beforeend',(snapshot.modelRouter?.providers||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.label||x.id)}</option>`).join(''));if(orch&&orch.options.length<=1)orch.insertAdjacentHTML('beforeend',(snapshot.orchestras||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.name||x.id)}</option>`).join(''));}
function renderRunExplorer(){const list=q('#coreRuns'),usage=runData.usage?.lifetime||{},rows=runData.runs||[];if(!list)return;q('#coreUsageRuns').textContent=Number(usage.runs||0).toLocaleString('fi-FI');q('#coreUsageTokens').textContent=Number(usage.totalTokens||0).toLocaleString('fi-FI');q('#coreUsageCost').textContent=fmtCost(usage);q('#coreUsageFallbacks').textContent=Number(usage.fallbacks||0).toLocaleString('fi-FI');q('#coreUsageDenies').textContent=Number(usage.toolDenies||0).toLocaleString('fi-FI');q('#coreRunStoreState').textContent=runData.store?`${runData.store.durable?'pysyvä':'palvelin'} · ${storeModeFi(runData.store.mode)} · historia ${runData.usage?.historySize||0}/${runData.usage?.historyLimit||0}`:'palvelinpuoli';q('#coreRunCount').textContent=Number(usage.runs||0).toLocaleString('fi-FI');q('#coreTokenCount').textContent=Number(usage.totalTokens||0).toLocaleString('fi-FI');q('#coreOutputCount').textContent=Number(usage.outputTokens||0).toLocaleString('fi-FI');q('#coreLedgerState').textContent=runData.chainOk?'KETJU OK':'KETJU RIKKI';q('#coreLedgerState').dataset.state=runData.chainOk?'ok':'broken';
  list.innerHTML=rows.length?rows.map(r=>`<article class="core-run-row" data-run-open="${esc(r.id)}" data-status="${esc(r.status)}" tabindex="0" role="button" aria-label="Avaa ajo ${esc(r.id)}"><div><strong>${esc(r.orchestra?.name||r.orchestra?.id||'Orkesteriajo')}</strong><span class="core-run-status">${esc(statusFi(r.status))}</span><span>${esc(r.id)}</span></div><div><span>${Number(r.receiptCount||0)} kuittia</span><span>${Number(r.usage?.totalTokens||0).toLocaleString('fi-FI')} tok</span><span>${fmtCost(r.usage)}</span><time>${r.finishedAt?esc(new Date(r.finishedAt).toLocaleString('fi-FI')):'käynnissä'}</time></div></article>`).join(''):'<p class="core-empty">Ei ajoja näillä suodattimilla.</p>';
}
function renderRunDetail(run){openRun=run;const root=q('#coreRunDetail');if(!root)return;q('#coreRunDialogTitle').textContent=run.orchestra?.name||'Orkesteriajo';q('#coreRunDialogId').textContent=`${run.workspaceId||workspaceId()} · ${run.id} · ${statusFi(run.status)}`;const u=run.usage||{},receipts=[...(run.receipts||[])].sort((a,b)=>(a.stageIndex??999)-(b.stageIndex??999));root.innerHTML=`<div class="core-run-detail-grid"><article><span>Tila</span><strong>${esc(statusFi(run.status))}</strong></article><article><span>Tokenit</span><strong>${Number(u.totalTokens||0).toLocaleString('fi-FI')}</strong></article><article><span>Arvioitu kustannus</span><strong>${fmtCost(u)}</strong></article><article><span>Ihmisen päätös</span><strong>${esc(statusFi(run.humanApproval?.status||'pending'))}</strong></article><article><span>Aloitettu</span><strong>${run.startedAt?esc(new Date(run.startedAt).toLocaleString('fi-FI')):'—'}</strong></article><article><span>Valmistui</span><strong>${run.finishedAt?esc(new Date(run.finishedAt).toLocaleString('fi-FI')):'—'}</strong></article><article><span>Varareitit</span><strong>${Number(u.fallbacks||0)}</strong></article><article><span>Estetyt työkalut</span><strong>${Number(u.toolDenies||0)}</strong></article></div><div class="core-run-hashes"><code>orchestra ${esc(run.orchestra?.orchestraHash||'—')}</code><code>previous ${esc(run.previousRunHash||'—')}</code><code>run ${esc(run.runHash||'—')}</code></div><div class="core-run-timeline"><h4>Vaiheaikajana</h4>${receipts.map(r=>{const denies=(r.toolPolicy||[]).filter(x=>x.outcome==='deny'||x.outcome==='human_required').length;return `<article class="core-run-stage"><b>${Number.isInteger(r.stageIndex)?String(r.stageIndex+1).padStart(2,'0'):'—'}</b><div><strong>${esc(r.agent?.label||r.agent?.id||'agentti')}</strong><small>${esc(r.agent?.contractHash||'')}</small></div><div class="core-run-stage-meta"><span>${esc(r.model?.provider||'')} · ${esc(r.model?.model||'')}</span><span>${Number(r.usage?.inputTokens||0).toLocaleString('fi-FI')} syöte · ${Number(r.usage?.outputTokens||0).toLocaleString('fi-FI')} tuloste · ${Number(r.durationMs||0)} ms</span></div><div class="core-run-stage-flags">${r.routing?.fallbackUsed?'<i data-kind="fallback">VARAREITTI</i>':''}${denies?`<i data-kind="deny">KÄYTÄNTÖ ${denies}</i>`:''}${(r.tools||[]).map(t=>`<i>${esc(t)}</i>`).join('')}</div></article>`;}).join('')||'<p class="core-empty">Ei vaihekuittia.</p>'}</div><div class="core-run-replay">Uudelleenajon metatiedot ovat tallessa: orkesterin hajautus, agenttisopimusten hajautukset, palveluntarjoaja- ja mallikohteet, tokenbudjetit sekä syöte- ja tulostehajautukset. Automaattinen uudelleenajo ei ole vielä käytössä.</div>`;}
async function openRunDialog(id){try{const run=await loadRunDetail(id);renderRunDetail(run);q('#coreRunDialog')?.showModal();}catch(error){alert(error.message);}}
function routeLabel(agent){const runtime=runtimeForAgent(agent?.id),target=modelTargetById(runtime?.modelTarget),provider=providerById(target?.provider);return target?`${provider?.label||target.provider} · ${target.model||target.id}`:agent?.modelRoute||'—';}
function chips(items=[],kind=''){return items.length?items.map(item=>`<span class="core-chip${kind?` ${kind}`:''}">${esc(item)}</span>`).join(''):'<span class="core-chip muted">ei määritelty</span>';}
function renderAgents(){
  const el=q('#coreAgents');if(!el||!snapshot)return;
  el.innerHTML=snapshot.agents.map(agent=>{const runtime=runtimeForAgent(agent.id);return `<article class="core-agent-card" data-agent-id="${esc(agent.id)}" data-runtime-state="${runtime?.active?'active':'disabled'}"><div class="core-agent-title"><div><span>${esc(agent.id)}</span><strong>${esc(agent.label)}</strong></div><span class="core-runtime-badge" data-state="${runtime?.active?'active':'disabled'}">${runtime?.active?'AKTIIVINEN':'POIS'}</span></div><p>${esc(agent.description)}</p><dl><div><dt>Rooli</dt><dd>${esc(agent.role)}</dd></div><div><dt>Malli</dt><dd>${esc(routeLabel(agent))}</dd></div><div><dt>Ajoprofiilin tulostekatto</dt><dd>${Number(runtime?.maxOutputTokens||0).toLocaleString('fi-FI')} tok</dd></div><div><dt>Sopimus</dt><dd>${budget(agent)}</dd></div></dl><div class="core-agent-foot"><code>${esc(agent.contractHash.slice(0,16))}…</code><button type="button" class="ghost core-agent-open" data-agent-open="${esc(agent.id)}">Hallinnoi</button></div></article>`;}).join('');
}
function renderOrchestras(){const el=q('#coreOrchestras');if(!el||!snapshot)return;el.innerHTML=snapshot.orchestras.map(o=>`<article class="core-orchestra-card"><div class="core-orchestra-head"><div><span>${esc(o.id)}</span><strong>${esc(o.name)} ${esc(o.version)}</strong></div><code>${esc(o.orchestraHash.slice(0,16))}…</code></div><p>${esc(o.description)}</p><div class="core-stage-line">${o.stages.map((id,i)=>{const runtime=runtimeForAgent(id);return `<span data-runtime-state="${runtime?.active?'active':'disabled'}"><b>${String(i+1).padStart(2,'0')}</b>${esc(snapshot.agents.find(a=>a.id===id)?.label||id)}${runtime?.active?'':' · POIS'}</span>`;}).join('')}</div></article>`).join('');}
function renderAgentDialog(id=openAgentId){
  const dialog=q('#coreAgentDialog');const agent=snapshot?.agents?.find(item=>item.id===id);if(!dialog||!agent)return;openAgentId=id;const runtime=runtimeForAgent(id);const policy=agent.runtimePolicy||{};
  q('#coreAgentDialogTitle').textContent=agent.label;q('#coreAgentDialogId').textContent=`${agent.id} · ${agent.role}`;q('#coreAgentDialogDescription').textContent=agent.description;
  q('#coreAgentActive').checked=runtime.active;q('#coreAgentTokens').min=String(runtime.limits.minOutputTokens);q('#coreAgentTokens').max=String(runtime.limits.maxOutputTokens);q('#coreAgentTokens').value=String(runtime.maxOutputTokens);q('#coreAgentTokenRange').textContent=`Sallittu ${runtime.limits.minOutputTokens.toLocaleString('fi-FI')}–${runtime.limits.maxOutputTokens.toLocaleString('fi-FI')} · sopimuksen oletus ${Number(agent.budget?.maxOutputTokens||0).toLocaleString('fi-FI')}`;
  const modelSelect=q('#coreAgentModelTarget');if(modelSelect){modelSelect.innerHTML=(runtime.limits.modelTargets||[]).map(id=>{const target=modelTargetById(id),provider=providerById(target?.provider);const label=`${provider?.label||target?.provider||id} · ${target?.model||id}${target?.configured?'':' · POIS KÄYTÖSTÄ'}`;return `<option value="${esc(id)}"${id===runtime.modelTarget?' selected':''}>${esc(label)}</option>`;}).join('');}
  q('#coreAgentModel').textContent=routeLabel(agent);q('#coreAgentTools').innerHTML=(snapshot.tools||[]).map(tool=>{const state=toolStateForAgent(agent,tool);return `<span class="core-chip ${state.kind}">${esc(tool.id)} · ${state.label}</span>`;}).join('')||chips([]);q('#coreAgentCapabilities').innerHTML=chips(agent.capabilities||[]);q('#coreAgentRead').innerHTML=chips(agent.authority?.read||[]);q('#coreAgentWrite').innerHTML=chips(agent.authority?.write||[],'allow');q('#coreAgentDeny').innerHTML=chips(agent.authority?.deny||[],'deny');q('#coreAgentApproval').innerHTML=chips(agent.humanApproval||[],'gate');q('#coreAgentHash').textContent=agent.contractHash;
  q('#coreAgentRuntimeNotice').textContent=`Työtila ${workspaceId()} · Ajoprofiili on palvelimen hallitsema ja pysyvä (${runtimeStore?.durable?'pysyvä':'palvelin'} · versio ${runtimeState.revision}). Mallikohteen voi vaihtaa vain sopimuksen loogisen reitin sallimiin kohteisiin; työkalu- ja toimivaltarajat pysyvät muuttumattomina (${(policy.immutable||[]).length} lukittua kenttää).`;
}
function openAgentDialog(id){const dialog=q('#coreAgentDialog');renderAgentDialog(id);if(dialog&&!dialog.open)dialog.showModal();}
async function render(){
  if(!panel||!snapshot)return;const ledger=readLedger(),receipts=ledger.entries.map(e=>e.receipt),events=policyEvents(receipts);const active=snapshot.agents.filter(agent=>runtimeForAgent(agent.id)?.active).length;
  q('#coreAgentCount').textContent=`${active}/${snapshot.agents.length}`;q('#corePolicyCount').textContent=String(events.length);renderRunExplorer();renderAgents();renderTools();renderModelRouter();renderPolicyLog(events);renderOrchestras();if(q('#coreAgentDialog')?.open&&openAgentId)renderAgentDialog(openAgentId);
}
async function loadCore(){try{const r=await fetch('/api/admin/core',{credentials:'same-origin'});if(!r.ok)return;const d=await r.json();snapshot=d.core;try{await loadRuntime();}catch(error){runtimeState={format:'anomancer-runtime-store/v3',workspaceId:workspaceId(),revision:0,updatedAt:'',profiles:Object.fromEntries((snapshot.agents||[]).map(agent=>[agent.id,fallbackRuntime(agent)]))};runtimeStore={mode:'unavailable',durable:false,error:error.message};}populateRunFilters();try{await loadRuns();}catch(error){runData={runs:[],usage:null,chainOk:false,store:{mode:'unavailable',error:error.message}};}q('#coreVersion').textContent=`CORE ${snapshot.version} / WS 16.7`;q('#coreOrchestraCount').textContent=String(snapshot.orchestras.length);await render();window.dispatchEvent(new CustomEvent('anomancer:core-ready',{detail:snapshot}));}catch{}}

panel?.addEventListener('click',event=>{const btn=event.target.closest?.('[data-agent-open]');if(btn)openAgentDialog(btn.dataset.agentOpen);});
q('#coreAgentClose')?.addEventListener('click',()=>q('#coreAgentDialog')?.close());
q('#coreAgentCancel')?.addEventListener('click',()=>q('#coreAgentDialog')?.close());
q('#coreAgentSave')?.addEventListener('click',async()=>{if(!openAgentId)return;try{await saveRuntimeProfile(openAgentId,{active:q('#coreAgentActive')?.checked!==false,maxOutputTokens:Number(q('#coreAgentTokens')?.value),modelTarget:q('#coreAgentModelTarget')?.value});await render();q('#coreAgentDialog')?.close();}catch(error){alert(error.message);if(error.code==='RUNTIME_REVISION_CONFLICT')await loadCore();}});
q('#coreAgentReset')?.addEventListener('click',async()=>{if(!openAgentId)return;try{await resetRuntimeProfile(openAgentId);await render();renderAgentDialog(openAgentId);}catch(error){alert(error.message);if(error.code==='RUNTIME_REVISION_CONFLICT')await loadCore();}});
q('#coreAgentDialog')?.addEventListener('click',event=>{if(event.target===q('#coreAgentDialog'))q('#coreAgentDialog').close();});
q('#coreRunRefresh')?.addEventListener('click',async()=>{try{await loadRuns();renderRunExplorer();}catch(error){alert(error.message);}});
for(const id of ['#coreRunFilterStatus','#coreRunFilterAgent','#coreRunFilterProvider','#coreRunFilterOrchestra'])q(id)?.addEventListener('change',async()=>{try{await loadRuns();renderRunExplorer();}catch{}});
q('#coreRuns')?.addEventListener('click',event=>{const row=event.target.closest?.('[data-run-open]');if(row)openRunDialog(row.dataset.runOpen);});
q('#coreRuns')?.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target?.dataset?.runOpen){event.preventDefault();openRunDialog(event.target.dataset.runOpen);}});
q('#coreRunClose')?.addEventListener('click',()=>q('#coreRunDialog')?.close());q('#coreRunDone')?.addEventListener('click',()=>q('#coreRunDialog')?.close());q('#coreRunDialog')?.addEventListener('click',event=>{if(event.target===q('#coreRunDialog'))q('#coreRunDialog').close();});
q('#coreRunCopy')?.addEventListener('click',async()=>{if(!openRun)return;const replay={workspaceId:openRun.workspaceId||workspaceId(),runId:openRun.id,orchestra:openRun.orchestra,status:openRun.status,startedAt:openRun.startedAt,finishedAt:openRun.finishedAt,runHash:openRun.runHash,previousRunHash:openRun.previousRunHash,receipts:(openRun.receipts||[]).map(r=>({stageIndex:r.stageIndex,agent:r.agent,model:r.model,routing:r.routing,runtime:r.runtime,inputHash:r.inputHash,outputHash:r.outputHash,usage:r.usage}))};try{await navigator.clipboard.writeText(JSON.stringify(replay,null,2));}catch{}});
window.addEventListener('anomancer:runs-changed',async()=>{try{await loadRuns();renderRunExplorer();}catch{}});
window.anomancerCore={appendReceipt,appendPolicyDecision,readLedger,readPolicyStore,verifyLedger,getSnapshot:()=>snapshot,getRuntimeProfile:runtimeForAgent,getRuntimeProfiles,saveRuntimeProfile,resetRuntimeProfile,createRuntimeSnapshot,refresh:loadCore,refreshRuns:async()=>{await loadRuns();renderRunExplorer();}};
window.addEventListener('anomancer:admin-ready',loadCore);
window.addEventListener('storage',event=>{if(String(event.key||'').startsWith(LEDGER_PREFIX)||String(event.key||'').startsWith(POLICY_PREFIX))render();});
window.addEventListener('anomancer:workspace-change',async()=>{openRun=null;runtimeState={format:'anomancer-runtime-store/v3',workspaceId:workspaceId(),revision:0,updatedAt:'',profiles:{}};runtimeStore=null;runData={runs:[],usage:null,chainOk:true,store:null};const orch=q('#coreRunFilterOrchestra');if(orch){orch.value='';while(orch.options.length>1)orch.remove(1);}await loadCore();});
loadCore();
