import crypto from 'node:crypto';
import { CORE_VERSION, digest } from './core-registry.js';

export const RUN_STORE_FORMAT='anomancer-run-store/v1';
export const RUN_RECORD_FORMAT='anomancer-run-record/v1';
const DEFAULT_TAG='anomancer-run-state';
const DEFAULT_PATH='.anomancer/run-history.json';
const HISTORY_LIMIT=60;
const CACHE_TTL_MS=3000;
const clone=v=>JSON.parse(JSON.stringify(v));
const clean=v=>String(v??'').trim();
let cache=null,memoryState=null;

function mode(){const forced=clean(process.env.ANOMANCER_RUN_STORE).toLowerCase();if(forced==='memory')return'memory';if(forced==='github-tag')return'github-tag';if(process.env.GITHUB_CONTENT_TOKEN&&process.env.GITHUB_REPO?.includes('/'))return'github-tag';return'unconfigured';}
function cfg(){const token=process.env.GITHUB_CONTENT_TOKEN,repo=process.env.GITHUB_REPO,branch=process.env.GITHUB_BRANCH||'master';if(!token||!repo?.includes('/'))throw Object.assign(new Error('Run Store ei ole konfiguroitu.'),{statusCode:503,code:'RUN_STORE_UNCONFIGURED'});return{token,repo,branch,tag:clean(process.env.ANOMANCER_RUN_TAG)||DEFAULT_TAG,path:clean(process.env.ANOMANCER_RUN_PATH)||DEFAULT_PATH};}
export function runStoreStatus(){const m=mode(),base={format:RUN_STORE_FORMAT,coreVersion:CORE_VERSION,mode:m,durable:m==='github-tag',serverAuthoritative:true,containsRawPrompt:false,containsRawOutput:false,historyLimit:HISTORY_LIMIT,secretsExposed:false};if(m==='github-tag'){const c=cfg();return{...base,configured:true,ref:`refs/tags/${c.tag}`,path:c.path};}return{...base,configured:m==='memory'};}
function emptyUsage(){return{runs:0,inputTokens:0,outputTokens:0,totalTokens:0,reasoningTokens:0,durationMs:0,estimatedCostEuro:0,pricedReceipts:0,fallbacks:0,toolAllows:0,toolDenies:0,toolHumanRequired:0,providers:{},agents:{},orchestras:{}};}
function defaultState(){return{format:RUN_STORE_FORMAT,coreVersion:CORE_VERSION,revision:0,updatedAt:'',chainHead:'GENESIS',runs:[],lifetime:emptyUsage()};}
function compactReceipt(r={}){const estimated=estimateReceiptCost(r);return{format:r.format||'',id:clean(r.id),orchestraRunId:clean(r.orchestraRunId),stageIndex:Number.isInteger(r.stageIndex)?r.stageIndex:null,agent:r.agent||null,model:r.model||null,routing:r.routing||null,runtime:r.runtime||null,usage:{...(r.usage||{}),costEuro:estimated},tools:Array.isArray(r.tools)?r.tools:[],toolPolicy:Array.isArray(r.toolPolicy)?r.toolPolicy:[],status:clean(r.status)||'completed',inputHash:clean(r.inputHash),outputHash:clean(r.outputHash),startedAt:clean(r.startedAt),finishedAt:clean(r.finishedAt),durationMs:Number(r.durationMs)||0,humanApprovalRequired:r.humanApprovalRequired!==false};}
function usageOfReceipts(receipts=[]){const u=emptyUsage();for(const r of receipts){const x=r.usage||{};u.inputTokens+=Number(x.inputTokens)||0;u.outputTokens+=Number(x.outputTokens)||0;u.totalTokens+=Number(x.totalTokens)||0;u.reasoningTokens+=Number(x.reasoningTokens)||0;u.durationMs+=Number(r.durationMs)||0;const p=clean(r.model?.provider)||'unknown';u.providers[p]=(u.providers[p]||0)+(Number(x.totalTokens)||0);const a=clean(r.agent?.id)||'unknown';u.agents[a]=(u.agents[a]||0)+(Number(x.totalTokens)||0);if(r.routing?.fallbackUsed)u.fallbacks++;for(const d of r.toolPolicy||[]){if(d.outcome==='allow')u.toolAllows++;else if(d.outcome==='human_required')u.toolHumanRequired++;else u.toolDenies++;}const c=x.costEuro===null||x.costEuro===undefined?null:Number(x.costEuro);if(c!==null&&Number.isFinite(c)){u.estimatedCostEuro+=c;u.pricedReceipts++;}}return u;}
function mergeUsage(a,b){const out=emptyUsage();for(const k of ['runs','inputTokens','outputTokens','totalTokens','reasoningTokens','durationMs','estimatedCostEuro','pricedReceipts','fallbacks','toolAllows','toolDenies','toolHumanRequired'])out[k]=(Number(a?.[k])||0)+(Number(b?.[k])||0);for(const key of ['providers','agents','orchestras'])for(const [id,n] of Object.entries({...a?.[key],...b?.[key]}))out[key][id]=(Number(a?.[key]?.[id])||0)+(Number(b?.[key]?.[id])||0);return out;}
function normalizeRun(raw={}){const receipts=(Array.isArray(raw.receipts)?raw.receipts:[]).map(compactReceipt).filter(x=>x.id);const usage=usageOfReceipts(receipts);return{format:RUN_RECORD_FORMAT,coreVersion:CORE_VERSION,id:clean(raw.id||raw.orchestraRunId).slice(0,120),orchestraRunId:clean(raw.orchestraRunId||raw.id).slice(0,120),orchestra:raw.orchestra?{id:clean(raw.orchestra.id),name:clean(raw.orchestra.name),orchestraHash:clean(raw.orchestra.orchestraHash)}:null,status:['running','checkpoint','stopped','completed','degraded','failed','aborted'].includes(raw.status)?raw.status:'running',humanApproval:{required:true,status:['pending','editor_applied'].includes(raw.humanApproval?.status)?raw.humanApproval.status:'pending',appliedAt:clean(raw.humanApproval?.appliedAt)},startedAt:clean(raw.startedAt)||receipts[0]?.startedAt||'',finishedAt:clean(raw.finishedAt),updatedAt:clean(raw.updatedAt),degradedStages:Array.isArray(raw.degradedStages)?raw.degradedStages.map(clean).filter(Boolean):[],disabledStages:Array.isArray(raw.disabledStages)?raw.disabledStages.map(clean).filter(Boolean):[],error:raw.error?{code:clean(raw.error.code),message:clean(raw.error.message).slice(0,500)}:null,receipts,usage,receiptCount:receipts.length,previousRunHash:clean(raw.previousRunHash)||'',runHash:clean(raw.runHash)||'',counted:Boolean(raw.counted)};}
function normalizeState(raw={}){const runs=(Array.isArray(raw.runs)?raw.runs:[]).map(normalizeRun).filter(r=>r.id).slice(-HISTORY_LIMIT);return{format:RUN_STORE_FORMAT,coreVersion:CORE_VERSION,revision:Math.max(0,Number(raw.revision)||0),updatedAt:clean(raw.updatedAt),chainHead:clean(raw.chainHead)||'GENESIS',runs,lifetime:{...emptyUsage(),...(raw.lifetime||{})}};}
function rateEnv(provider,kind){const key=`ANOMANCER_COST_${String(provider||'').toUpperCase().replace(/[^A-Z0-9]/g,'_')}_${kind}_EUR_PER_M`;const n=Number(process.env[key]);return Number.isFinite(n)&&n>=0?n:null;}
export function estimateReceiptCost(receipt={}){const provider=clean(receipt.model?.provider);const input=rateEnv(provider,'INPUT'),output=rateEnv(provider,'OUTPUT');if(input===null||output===null)return null;const u=receipt.usage||{};return ((Number(u.inputTokens)||0)*input+(Number(u.outputTokens)||0)*output)/1_000_000;}
async function gh(path,options={}){const {token}=cfg();const r=await fetch(`https://api.github.com${path}`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'anomancer-core-runs-v15.8',...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null;}catch{data={message:text};}if(!r.ok)throw Object.assign(new Error(data?.message||`GitHub ${r.status}`),{statusCode:r.status===404?404:(r.status===409||r.status===422?409:502),code:`RUN_GITHUB_${r.status}`});return data;}
async function tagRef(){const {repo,tag}=cfg();try{const d=await gh(`/repos/${repo}/git/ref/tags/${encodeURIComponent(tag)}`);return clean(d?.object?.sha)||null;}catch(e){if(e.statusCode===404)return null;throw e;}}
async function readTag(){const {repo,tag,path}=cfg();try{const d=await gh(`/repos/${repo}/contents/${encodeURI(path)}?ref=${encodeURIComponent(tag)}`);return normalizeState(JSON.parse(Buffer.from(String(d?.content||'').replace(/\n/g,''),'base64').toString('utf8')));}catch(e){if(e.statusCode===404)return defaultState();throw e;}}
async function branchHead(){const {repo,branch}=cfg();return clean((await gh(`/repos/${repo}/git/ref/heads/${encodeURI(branch)}`))?.object?.sha);}
async function commitTree(sha){const {repo}=cfg();return clean((await gh(`/repos/${repo}/git/commits/${sha}`))?.tree?.sha);}
async function write(state,{parentSha,create=false}={}){const {repo,tag,path}=cfg(),base=await commitTree(parentSha);const blob=await gh(`/repos/${repo}/git/blobs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:`${JSON.stringify(state,null,2)}\n`,encoding:'utf-8'})});const tree=await gh(`/repos/${repo}/git/trees`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({base_tree:base,tree:[{path,mode:'100644',type:'blob',sha:blob.sha}]})});const commit=await gh(`/repos/${repo}/git/commits`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`core runs: revision ${state.revision}`,tree:tree.sha,parents:[parentSha]})});if(create)await gh(`/repos/${repo}/git/refs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:`refs/tags/${tag}`,sha:commit.sha})});else await gh(`/repos/${repo}/git/refs/tags/${encodeURIComponent(tag)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({sha:commit.sha,force:false})});}
export async function loadRunState({force=false}={}){const m=mode();if(m==='memory'){if(!memoryState)memoryState=defaultState();return clone(memoryState);}if(m==='unconfigured')throw Object.assign(new Error('Run Store ei ole konfiguroitu.'),{statusCode:503,code:'RUN_STORE_UNCONFIGURED'});if(!force&&cache&&cache.expiresAt>Date.now())return clone(cache.state);const ref=await tagRef(),state=ref?await readTag():defaultState();cache={state:normalizeState(state),refSha:ref,expiresAt:Date.now()+CACHE_TTL_MS};return clone(cache.state);}
async function mutate(fn){const m=mode();if(m==='memory'){const current=await loadRunState({force:true}),next=normalizeState(fn(clone(current)));next.revision=current.revision+1;next.updatedAt=new Date().toISOString();memoryState=next;return clone(next);}if(m==='unconfigured')throw Object.assign(new Error('Run Store ei ole konfiguroitu.'),{statusCode:503,code:'RUN_STORE_UNCONFIGURED'});for(let a=0;a<3;a++){cache=null;const current=await loadRunState({force:true}),ref=cache?.refSha||await tagRef(),next=normalizeState(fn(clone(current)));next.revision=current.revision+1;next.updatedAt=new Date().toISOString();try{await write(next,{parentSha:ref||await branchHead(),create:!ref});cache={state:next,refSha:null,expiresAt:Date.now()+CACHE_TTL_MS};return clone(next);}catch(e){if(e.statusCode===409&&a<2)continue;throw e;}}throw Object.assign(new Error('Run Storen rinnakkaisuuskonflikti.'),{statusCode:409,code:'RUN_WRITE_CONFLICT'});}
function finalizeHash(run,previous){const u=run.usage||{};const usage={inputTokens:u.inputTokens||0,outputTokens:u.outputTokens||0,totalTokens:u.totalTokens||0,reasoningTokens:u.reasoningTokens||0,fallbacks:u.fallbacks||0,toolAllows:u.toolAllows||0,toolDenies:u.toolDenies||0,toolHumanRequired:u.toolHumanRequired||0,providers:u.providers||{},agents:u.agents||{}};const payload={id:run.id,orchestra:run.orchestra,status:run.status,startedAt:run.startedAt,finishedAt:run.finishedAt,receiptIds:run.receipts.map(r=>r.id),receiptHashes:run.receipts.map(r=>r.outputHash),usage,previousRunHash:previous};return digest(payload);}
export async function appendRunReceipt(receipt){if(!receipt?.id||!receipt?.orchestraRunId)return null;const state=await mutate(s=>{let run=s.runs.find(r=>r.id===receipt.orchestraRunId);if(!run){run=normalizeRun({id:receipt.orchestraRunId,orchestraRunId:receipt.orchestraRunId,orchestra:receipt.orchestra,status:'running',startedAt:receipt.startedAt,receipts:[]});s.runs.push(run);}if(!run.receipts.some(r=>r.id===receipt.id))run.receipts.push(compactReceipt(receipt));run.updatedAt=new Date().toISOString();return s;});return state.runs.find(r=>r.id===receipt.orchestraRunId)||null;}
export async function checkpointRun(id,patch={}){const key=clean(id);const state=await mutate(s=>{let run=s.runs.find(r=>r.id===key);if(!run){run=normalizeRun({id:key,orchestraRunId:key,orchestra:patch.orchestra,status:'running',startedAt:patch.startedAt||new Date().toISOString()});s.runs.push(run);}run.status=patch.status==='stopped'?'stopped':'checkpoint';run.degradedStages=Array.isArray(patch.degradedStages)?patch.degradedStages.map(clean).filter(Boolean):run.degradedStages;run.disabledStages=Array.isArray(patch.disabledStages)?patch.disabledStages.map(clean).filter(Boolean):run.disabledStages;run.error=patch.error?{code:clean(patch.error.code),message:clean(patch.error.message).slice(0,500)}:null;run.orchestra=run.orchestra||patch.orchestra||null;run.updatedAt=new Date().toISOString();return s;});return state.runs.find(r=>r.id===key)||null;}
export async function finalizeRun(id,patch={}){const key=clean(id);const state=await mutate(s=>{let run=s.runs.find(r=>r.id===key);if(!run){run=normalizeRun({id:key,orchestraRunId:key,orchestra:patch.orchestra,status:'running',startedAt:patch.startedAt||new Date().toISOString()});s.runs.push(run);}run.status=['completed','degraded','failed','aborted'].includes(patch.status)?patch.status:run.status;run.finishedAt=clean(patch.finishedAt)||new Date().toISOString();run.degradedStages=Array.isArray(patch.degradedStages)?patch.degradedStages.map(clean).filter(Boolean):run.degradedStages;run.disabledStages=Array.isArray(patch.disabledStages)?patch.disabledStages.map(clean).filter(Boolean):run.disabledStages;run.error=patch.error?{code:clean(patch.error.code),message:clean(patch.error.message).slice(0,500)}:run.error;run.orchestra=run.orchestra||patch.orchestra||null;run.updatedAt=new Date().toISOString();run.usage=usageOfReceipts(run.receipts);if(!run.runHash){run.previousRunHash=s.chainHead||'GENESIS';run.runHash=finalizeHash(run,run.previousRunHash);s.chainHead=run.runHash;}if(!run.counted){const add={...run.usage,runs:1,orchestras:{[run.orchestra?.id||'unknown']:1}};s.lifetime=mergeUsage(s.lifetime,add);run.counted=true;}return s;});return state.runs.find(r=>r.id===key)||null;}
export async function markRunApplied(id){const key=clean(id);const state=await mutate(s=>{const run=s.runs.find(r=>r.id===key);if(!run)throw Object.assign(new Error('Ajoa ei löytynyt.'),{statusCode:404,code:'RUN_NOT_FOUND'});run.humanApproval={required:true,status:'editor_applied',appliedAt:new Date().toISOString()};run.updatedAt=new Date().toISOString();return s;});return state.runs.find(r=>r.id===key);}
export async function listRuns({limit=30,status='',agent='',provider='',orchestra=''}={}){const s=await loadRunState();let rows=[...s.runs].reverse();if(status)rows=rows.filter(r=>r.status===status);if(orchestra)rows=rows.filter(r=>r.orchestra?.id===orchestra);if(agent)rows=rows.filter(r=>r.receipts.some(x=>x.agent?.id===agent));if(provider)rows=rows.filter(r=>r.receipts.some(x=>x.model?.provider===provider));return{runs:rows.slice(0,Math.max(1,Math.min(60,Number(limit)||30))).map(runSummary),usage:usageSnapshotFromState(s),chainOk:verifyRunChain(s.runs),store:runStoreStatus()};}
function runSummary(r){return{id:r.id,orchestraRunId:r.orchestraRunId,orchestra:r.orchestra,status:r.status,humanApproval:r.humanApproval,startedAt:r.startedAt,finishedAt:r.finishedAt,updatedAt:r.updatedAt,degradedStages:r.degradedStages,disabledStages:r.disabledStages,error:r.error,receiptCount:r.receiptCount||r.receipts.length,usage:r.usage,previousRunHash:r.previousRunHash,runHash:r.runHash};}
export async function getRun(id){const s=await loadRunState();const r=s.runs.find(x=>x.id===clean(id));return r?clone(r):null;}
function usageSnapshotFromState(s){const recent=s.runs.reduce((acc,r)=>{const final=['completed','degraded','failed','aborted'].includes(r.status);return mergeUsage(acc,{...r.usage,runs:final?1:0,orchestras:final?{[r.orchestra?.id||'unknown']:1}:{}});},emptyUsage());return{recent,lifetime:s.lifetime,chainHead:s.chainHead,historySize:s.runs.length,historyLimit:HISTORY_LIMIT};}
export async function usageSnapshot(){return usageSnapshotFromState(await loadRunState());}
export function verifyRunChain(runs=[]){const ordered=[...runs].filter(x=>x.runHash).sort((a,b)=>String(a.finishedAt).localeCompare(String(b.finishedAt)));let previous=ordered[0]?.previousRunHash||'GENESIS';for(const r of ordered){if(r.previousRunHash!==previous)return false;if(finalizeHash(r,previous)!==r.runHash)return false;previous=r.runHash;}return true;}
export function __resetRunStoreForTests(){cache=null;memoryState=null;}
