import { spawnSync } from 'node:child_process';

const STEPS = [
  [
    "tests/integrity-security/frontend-runtime-boundary.mjs"
  ],
  [
    "tests/integrity-security/build-source-boundary.mjs"
  ],
  [
    "tests/integrity-security/pr-governance.mjs"
  ],
  [
    "tests/operations-release/live-path-verification.mjs"
  ],
  [
    "tests/operations-release/live-path-ui.mjs"
  ],
  [
    "tests/operations-release/capability-wiring.mjs"
  ],
  [
    "tests/operations-release/operation-ui.mjs"
  ],
  [
    "tests/integrity-security/workspace-integrity.mjs"
  ],
  [
    "tests/mancer-codemancer/visual-contract.mjs"
  ],
  [
    "tests/ui-browser/interaction-navigation.mjs"
  ],
  [
    "tests/mancer-codemancer/codemancer-workbench.mjs"
  ],
  [
    "tests/mancer-codemancer/codemancer-workbench-ui.mjs"
  ],
  [
    "tests/ui-browser/interaction-pwa-regression.mjs"
  ],
  [
    "tests/full-app-e2e/admin-workspace-story.mjs"
  ],
  [
    "tests/ui-browser/app-split-pwa.mjs"
  ],
  [
    "tests/ui-browser/machine-room.mjs"
  ],
  [
    "tests/integrity-security/security-ui-invariants.mjs"
  ],
  [
    "tests/content-editorial/editorial-quality.mjs"
  ],
  [
    "tests/content-editorial/editorial-gate-calibration.mjs"
  ],
  [
    "tests/content-editorial/evidence-boundary-hygiene.mjs"
  ],
  [
    "tests/ui-browser/mobile-workspace.mjs"
  ],
  [
    "tests/ui-browser/mobile-control-plane-reflow.mjs"
  ],
  [
    "tests/public-api-boundary/public-boundary.mjs"
  ],
  [
    "tests/public-api-boundary/api-surface.mjs"
  ],
  [
    "tests/content-editorial/evidence-presentation.mjs"
  ],
  [
    "tests/content-editorial/admin.mjs"
  ],
  [
    "tests/content-editorial/contact.mjs"
  ],
  [
    "tests/content-editorial/public-ui.mjs"
  ],
  [
    "tests/public-api-boundary/public-core.mjs"
  ],
  [
    "tests/core-runtime/agent-contracts.mjs"
  ],
  [
    "tests/ui-browser/ui-semantics.mjs"
  ],
  [
    "tests/ui-browser/legacy-layout-invariants.mjs"
  ],
  [
    "tests/ui-browser/filter-layout-invariants.mjs"
  ],
  [
    "tests/ui-browser/orchestra-flow.mjs"
  ],
  [
    "scripts/build-blog.mjs",
    "--check"
  ],
  [
    "tests/content-editorial/public-clarity.mjs"
  ],
  [
    "tests/content-editorial/language-boundaries.mjs"
  ],
  [
    "tests/content-editorial/entity-core.mjs"
  ],
  [
    "tests/content-editorial/evidence-layer.mjs"
  ],
  [
    "tests/content-editorial/discovery-layer.mjs"
  ],
  [
    "tests/core-runtime/core-foundation.mjs"
  ],
  [
    "tests/core-runtime/runtime-profiles.mjs"
  ],
  [
    "tests/core-runtime/custom-orchestras.mjs"
  ],
  [
    "tests/core-runtime/run-explorer.mjs"
  ],
  [
    "tests/core-runtime/workspace-foundation.mjs"
  ],
  [
    "tests/archive-capabilities/archive-core.mjs"
  ],
  [
    "tests/archive-capabilities/archive-ui.mjs"
  ],
  [
    "tests/archive-capabilities/nanomancer.mjs"
  ],
  [
    "tests/archive-capabilities/nanomancer-ui.mjs"
  ],
  [
    "tests/archive-capabilities/archive-curator.mjs"
  ],
  [
    "tests/archive-capabilities/archive-curator-ui.mjs"
  ],
  [
    "tests/mancer-codemancer/runtime.mjs"
  ],
  [
    "tests/mancer-codemancer/ui.mjs"
  ],
  [
    "tests/mancer-codemancer/semantic-workbench.mjs"
  ],
  [
    "tests/ui-browser/native-dialogs.mjs"
  ],
  [
    "tests/integrity-security/platform-hardening.mjs"
  ],
  [
    "tests/ui-browser/core-roadmap.mjs"
  ],
  [
    "tests/ui-browser/navigation-shell.mjs"
  ],
  [
    "tests/ui-browser/navigation-shell-visual.mjs"
  ],
  [
    "tests/ui-browser/core-shell-semantics.mjs"
  ],
  [
    "tests/ui-browser/responsive-workspace-navigation.mjs"
  ],
  [
    "tests/narramancer/authoring.mjs"
  ],
  [
    "tests/content-editorial/evidence-interaction.mjs"
  ],
  [
    "tests/ui-browser/visual-system.mjs"
  ],
  [
    "tests/narramancer/vertical-slice.mjs"
  ],
  [
    "tests/core-runtime/agent-pool-control.mjs"
  ],
  [
    "tests/core-runtime/tool-broker.mjs"
  ],
  [
    "tests/core-runtime/model-router.mjs"
  ],
  [
    "tests/core-runtime/agent-layer.mjs"
  ],
  [
    "tests/core-runtime/orchestrator.mjs"
  ],
  [
    "scripts/domain-migration-check.mjs"
  ],
  [
    "seo-check.mjs"
  ]
];

for (const [index,args] of STEPS.entries()) {
  const label=args.join(' ');
  console.log(`\n[${String(index+1).padStart(2,'0')}/${STEPS.length}] ${label}`);
  const result=spawnSync(process.execPath,args,{stdio:'inherit',env:process.env});
  if(result.error) throw result.error;
  if(result.status!==0){
    console.error(`\nRelease gate failed: ${label}`);
    process.exit(result.status||1);
  }
}
console.log(`\n✓ Release gate complete: ${STEPS.length}/${STEPS.length} steps passed`);
