import assert from 'node:assert/strict';
import fs from 'node:fs';
import { readAdminCss } from '../../scripts/read-admin-css.mjs';
let ok=0;const test=(name,fn)=>{fn();ok++;console.log(`✓ ${name}`)};
const html=fs.readFileSync('admin.html','utf8');
const js=fs.readFileSync('admin-orchestrator.js','utf8');
const css=readAdminCss();
const build=fs.readFileSync('scripts/build-blog.mjs','utf8');
const api=fs.readFileSync('server/admin-routes/agents.js','utf8');
await import('node:child_process').then(({execFileSync})=>execFileSync(process.execPath,['--check','admin-orchestrator.js'],{stdio:'pipe'}));
test('adminissa on työtilaorkestrointi ja ajoloki ilman työpinnan release-leimaa',()=>{assert.match(html,/>TYÖTILAORKESTROINTI</);assert.doesNotMatch(html,/16\.3 · TYÖTILAORKESTROINTI/);assert.match(html,/orchestraTerminal/);assert.match(html,/IHMINEN PÄÄTTÄÄ LOPULLISESTI/);});
test('putki sisältää kaikki kahdeksan agenttia oikeassa järjestyksessä',()=>{assert.match(js,/source[\s\S]*structure[\s\S]*writer[\s\S]*critic[\s\S]*audience[\s\S]*voice[\s\S]*claims[\s\S]*package/);});
test('orkestrointi käyttää vain olemassa olevaa agentti-API:a',()=>{assert.match(js,/\/api\/admin\/core\?resource=agents/);assert.doesNotMatch(js,/\/api\/admin\/posts|publishBtn\.click|saveDraftBtn\.click/);});
test('human approval gate jää viimeiseksi',()=>{assert.match(js,/humanApprovalRequired:true/);assert.match(js,/Lähdeagentin ehdokkaat ovat edelleen ihmisen tarkistettavia/);assert.match(js,/Mitään ei julkaista tällä toiminnolla/);});
test('välitulokset siirtyvät työmuistissa seuraaville agenteille',()=>{assert.match(js,/ctx\.post\.sources=mergeSources/);assert.match(js,/ctx\.post\.claims=d\.result\.claims/);assert.match(js,/ctx\.post\.body=d\.result\.body/);assert.match(js,/RAKENNEAGENTIN EHDOTUS JSON/);assert.match(js,/ÄÄNIEDITORIN JÄLKEISEN nykyisen tekstin/);assert.match(js,/KRIITIKON HAVAINNOT JSON/);});
test('live terminal tukee pysäytystä ja turvallista diagnostiikkaa',()=>{assert.match(js,/Pysäytys pyydetty/);assert.match(js,/for\(const controller of controllers\)controller\.abort\(\)/);assert.match(js,/errorDiagnostic/);assert.match(css,/orchestra-terminal/);});
test('orkesterin sisäinen konteksti mahtuu agentti-API:n instruction-rajaan',()=>{assert.match(api,/MAX_CUSTOM_CHARS=12_000/);assert.match(js,/slice\(0,12000\)/);});
test('build stageaa orchestrator-JS:n publiciin',()=>{assert.match(build,/admin-orchestrator\.js/);});
test('tilapäinen DeepSeek-virhe saa yhden automaattisen uusintayrityksen',()=>{assert.match(js,/automaattinen uusintayritys 1\/1/);assert.match(js,/attempt===1&&isRetryable/);assert.match(js,/retryAfterMs/);assert.match(js,/DEEPSEEK_EMPTY/);});
test('checkpoint tallennetaan sessionStorageen ja sisältää serverin allekirjoittaman runtime-snapshotin',()=>{assert.match(js,/sessionStorage\.setItem\(checkpointKey\(\)/);assert.match(js,/sessionStorage\.getItem\(checkpointKey\(\)/);assert.match(js,/checkpoint\.v15\.9\.0/);assert.doesNotMatch(js,/localStorage\.setItem/);});
test('checkpoint on sidottu luonnoksen identiteettiin ja valmis tulos säilyy',()=>{assert.match(js,/draftIdentity/);assert.match(js,/instanceId/);assert.match(js,/sameDocument/);assert.match(js,/ctx\.status='complete'/);assert.match(js,/function finishRun[\s\S]{0,2000}saveCheckpoint\(ctx\)/);});
test('virheen jälkeen voidaan yrittää yksi vaihe uudelleen tai jatkaa tarkistuspisteestä',()=>{assert.match(html,/orchestraRetryBtn/);assert.match(html,/orchestraResumeBtn/);assert.match(js,/retryFailedStage/);assert.match(js,/resumePipeline/);assert.match(js,/tarkistuspiste säilyi/);});
test('lähdeagentin varareitti tai nolla lähdettä näkyy heikentyneenä tilana',()=>{assert.match(js,/sourceIsDegraded/);assert.match(js,/degraded:'heikentynyt'/);assert.match(css,/data-state=degraded/);assert.match(js,/Älä merkitse väitteitä tuetuiksi tämän lähdevaiheen perusteella/);});
test('checkpoint säilyttää vain näkyvät agenttitulokset eikä reasoning-sisältöä',()=>{assert.match(js,/outputs:ctx\.outputs/);assert.match(js,/metas:ctx\.metas/);assert.doesNotMatch(js,/reasoning_content|chainOfThought|reasoningText/);});
test('paketoija ei saa kirjoittaa Evidence Layeria uusiksi',()=>{assert.match(js,/Evidence Layer \(claims \+ sources\).*audience \+ audienceDepth.*lukittuja/);const start=js.indexOf('function mergePackageIntoPost');const end=js.indexOf('async function getSession',start);const merge=js.slice(start,end);assert.doesNotMatch(merge,/next\.sources|next\.claims/);});
test('lähdemerge täyttää pysyvän source-id:n eikä hukkaa duplikaatin metadataa',()=>{assert.match(js,/stableSourceId/);assert.match(js,/if\(!existing\[key\]&&normalized\[key\]\)existing\[key\]=normalized\[key\]/);});

await test('orkesterissa yleisökerros on kritiikin jälkeen ja Väitevahti vasta lopullisen äänen jälkeen',()=>{const js=fs.readFileSync('admin-orchestrator.js','utf8');const critic=js.indexOf("{id:'critic'");const audience=js.indexOf("{id:'audience'");const voice=js.indexOf("{id:'voice'");const claims=js.indexOf("{id:'claims'");assert.ok(critic<audience&&audience<voice&&voice<claims);assert.match(js,/stage\.id==='audience'.*ctx\.post\.body/s);assert.match(js,/audienceDepth:q\('#audienceDepth'\)/);});
await test('pakettivaihe ei voi vaihtaa Audience Contractia selaimessa',()=>{const js=fs.readFileSync('admin-orchestrator.js','utf8');const fn=js.slice(js.indexOf('function mergePackageIntoPost'),js.indexOf('function stageInstruction'));assert.doesNotMatch(fn,/next\.audience/);assert.match(js,/audience \+ audienceDepth ovat lukittuja/);});
console.log(`\n${ok}/${ok} ORCHESTRATOR RESILIENCE -testiä läpi`);
