import crypto from 'node:crypto';
import { CORE_VERSION, ORCHESTRA_REGISTRY, validateOrchestraDefinition } from './core-registry.js';
import { DEFAULT_WORKSPACE_ID, workspaceStorageScope } from './workspace-store.js';

export const ORCHESTRA_STORE_FORMAT='anomancer-orchestra-store/v2';
const DEFAULT_TAG='anomancer-orchestra-state';
const DEFAULT_PATH='.anomancer/custom-orchestras.json';
const CACHE_TTL_MS=5_000;
const clone=value=>JSON.parse(JSON.stringify(value));
const clean=value=>String(value??'').trim();
const caches=new Map(),memoryStates=new Map();
function workspaceKey(id){return String(id||DEFAULT_WORKSPACE_ID).trim()||DEFAULT_WORKSPACE_ID;}
function configuredMode(){const forced=clean(process.env.ANOMANCER_ORCHESTRA_STORE).toLowerCase();if(forced==='memory')return'memory';if(forced==='github-tag')return'github-tag';if(process.env.GITHUB_CONTENT_TOKEN&&process.env.GITHUB_REPO?.includes('/'))return'github-tag';return'unconfigured';}
function githubConfig(workspaceId=DEFAULT_WORKSPACE_ID){const token=process.env.GITHUB_CONTENT_TOKEN,repo=process.env.GITHUB_REPO,branch=process.env.GITHUB_BRANCH||'master';if(!token||!repo?.includes('/'))throw Object.assign(new Error('Custom Orchestra -tallennus ei ole konfiguroitu.'),{statusCode:503,code:'ORCHESTRA_STORE_UNCONFIGURED'});const scope=workspaceStorageScope(workspaceId,{baseTag:clean(process.env.ANOMANCER_ORCHESTRA_TAG)||DEFAULT_TAG,basePath:clean(process.env.ANOMANCER_ORCHESTRA_PATH)||DEFAULT_PATH});return{token,repo,branch,...scope};}
export function orchestraStoreStatus(workspaceId=DEFAULT_WORKSPACE_ID){const mode=configuredMode(),id=workspaceKey(workspaceId),base={format:ORCHESTRA_STORE_FORMAT,coreVersion:CORE_VERSION,workspaceId:id,mode,durable:mode==='github-tag',serverAuthoritative:true,secretsExposed:false};if(mode==='github-tag'){const c=githubConfig(id);return{...base,configured:true,ref:`refs/tags/${c.tag}`,path:c.path,legacyDefault:c.legacy};}return{...base,configured:mode==='memory'};}
function normalizeCustomList(items=[]){const out=[],ids=new Set();for(const raw of Array.isArray(items)?items:[]){const checked=validateOrchestraDefinition({...raw,source:'custom'});if(!checked.ok)continue;const o=checked.orchestra;if(ids.has(o.id)||ORCHESTRA_REGISTRY.some(item=>item.id===o.id))continue;ids.add(o.id);out.push({...o,createdAt:clean(raw.createdAt),updatedAt:clean(raw.updatedAt)});}return out.slice(0,50);}
function defaultState(workspaceId=DEFAULT_WORKSPACE_ID){return{format:ORCHESTRA_STORE_FORMAT,coreVersion:CORE_VERSION,workspaceId:workspaceKey(workspaceId),revision:0,updatedAt:'',orchestras:[]};}
function normalizeState(input={},workspaceId=DEFAULT_WORKSPACE_ID){return{format:ORCHESTRA_STORE_FORMAT,coreVersion:CORE_VERSION,workspaceId:workspaceKey(workspaceId),revision:Math.max(0,Number(input.revision)||0),updatedAt:clean(input.updatedAt),orchestras:normalizeCustomList(input.orchestras)};}
async function gh(workspaceId,path,options={}){const{token}=githubConfig(workspaceId);const response=await fetch(`https://api.github.com${path}`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'anomancer-core-orchestras-v15.9',...(options.headers||{})}});const text=await response.text();let data=null;try{data=text?JSON.parse(text):null;}catch{data={message:text};}if(!response.ok)throw Object.assign(new Error(data?.message||`GitHub ${response.status}`),{statusCode:response.status===404?404:(response.status===409||response.status===422?409:502),code:`ORCHESTRA_GITHUB_${response.status}`,githubStatus:response.status,details:data});return data;}
async function readTagRef(workspaceId){const{repo,tag}=githubConfig(workspaceId);try{return clean((await gh(workspaceId,`/repos/${repo}/git/ref/tags/${encodeURIComponent(tag)}`))?.object?.sha)||null;}catch(e){if(e.statusCode===404)return null;throw e;}}
async function readStateAtTag(workspaceId){const{repo,tag,path}=githubConfig(workspaceId);try{const d=await gh(workspaceId,`/repos/${repo}/contents/${encodeURI(path)}?ref=${encodeURIComponent(tag)}`);return normalizeState(JSON.parse(Buffer.from(String(d?.content||'').replace(/\n/g,''),'base64').toString('utf8')),workspaceId);}catch(e){if(e.statusCode===404)return defaultState(workspaceId);throw e;}}
async function branchHead(workspaceId){const{repo,branch}=githubConfig(workspaceId);return clean((await gh(workspaceId,`/repos/${repo}/git/ref/heads/${encodeURI(branch)}`))?.object?.sha);}
async function commitTree(workspaceId,sha){const{repo}=githubConfig(workspaceId);return clean((await gh(workspaceId,`/repos/${repo}/git/commits/${sha}`))?.tree?.sha);}
async function writeStateCommit(workspaceId,state,{parentSha,createRef=false}={}){const{repo,tag,path}=githubConfig(workspaceId),treeBase=await commitTree(workspaceId,parentSha);const blob=await gh(workspaceId,`/repos/${repo}/git/blobs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:`${JSON.stringify(state,null,2)}\n`,encoding:'utf-8'})});const tree=await gh(workspaceId,`/repos/${repo}/git/trees`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({base_tree:treeBase,tree:[{path,mode:'100644',type:'blob',sha:blob.sha}]})});const commit=await gh(workspaceId,`/repos/${repo}/git/commits`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`core orchestras (${workspaceKey(workspaceId)}): revision ${state.revision}`,tree:tree.sha,parents:[parentSha]})});if(createRef)await gh(workspaceId,`/repos/${repo}/git/refs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:`refs/tags/${tag}`,sha:commit.sha})});else await gh(workspaceId,`/repos/${repo}/git/refs/tags/${encodeURIComponent(tag)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({sha:commit.sha,force:false})});return commit.sha;}
export async function loadOrchestraState({force=false,workspaceId=DEFAULT_WORKSPACE_ID}={}){const id=workspaceKey(workspaceId),mode=configuredMode();if(mode==='memory'){if(!memoryStates.has(id))memoryStates.set(id,defaultState(id));return clone(memoryStates.get(id));}if(mode==='unconfigured')throw Object.assign(new Error('Custom Orchestra -tallennus ei ole konfiguroitu.'),{statusCode:503,code:'ORCHESTRA_STORE_UNCONFIGURED'});const cached=caches.get(id);if(!force&&cached&&cached.expiresAt>Date.now())return clone(cached.state);const refSha=await readTagRef(id),state=refSha?await readStateAtTag(id):defaultState(id);caches.set(id,{state:normalizeState(state,id),refSha,expiresAt:Date.now()+CACHE_TTL_MS});return clone(caches.get(id).state);}
export async function saveOrchestraState(input,{expectedRevision=null,workspaceId=DEFAULT_WORKSPACE_ID}={}){const id=workspaceKey(workspaceId),mode=configuredMode();if(mode==='memory'){const current=await loadOrchestraState({force:true,workspaceId:id});if(expectedRevision!==null&&Number(expectedRevision)!==current.revision)throw Object.assign(new Error('Orkesterirekisteri muuttui toisessa istunnossa.'),{statusCode:409,code:'ORCHESTRA_REVISION_CONFLICT'});const next=normalizeState({...input,revision:current.revision+1,updatedAt:new Date().toISOString()},id);memoryStates.set(id,next);return clone(next);}if(mode==='unconfigured')throw Object.assign(new Error('Custom Orchestra -tallennus ei ole konfiguroitu.'),{statusCode:503,code:'ORCHESTRA_STORE_UNCONFIGURED'});for(let attempt=0;attempt<2;attempt++){caches.delete(id);const current=await loadOrchestraState({force:true,workspaceId:id}),cached=caches.get(id),refSha=cached?.refSha||await readTagRef(id);if(expectedRevision!==null&&Number(expectedRevision)!==current.revision)throw Object.assign(new Error('Orkesterirekisteri muuttui toisessa istunnossa.'),{statusCode:409,code:'ORCHESTRA_REVISION_CONFLICT'});const next=normalizeState({...input,revision:current.revision+1,updatedAt:new Date().toISOString()},id);try{if(refSha)await writeStateCommit(id,next,{parentSha:refSha});else await writeStateCommit(id,next,{parentSha:await branchHead(id),createRef:true});caches.set(id,{state:next,refSha:null,expiresAt:Date.now()+CACHE_TTL_MS});return clone(next);}catch(e){if(e.statusCode===409&&attempt===0){caches.delete(id);continue;}throw e;}}throw Object.assign(new Error('Orkesterirekisterin rinnakkaisuuskonflikti.'),{statusCode:409,code:'ORCHESTRA_WRITE_CONFLICT'});}
function makeId(name='orchestra'){const slug=String(name).toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,36)||'orchestra';return`custom-${slug}-${crypto.randomBytes(3).toString('hex')}`;}
export async function listAvailableOrchestras(workspaceId=DEFAULT_WORKSPACE_ID){const state=await loadOrchestraState({workspaceId});return{state,builtins:ORCHESTRA_REGISTRY.map(clone),custom:state.orchestras.map(clone),all:[...ORCHESTRA_REGISTRY.map(clone),...state.orchestras.map(clone)]};}
export async function getAvailableOrchestra(id='editorial',workspaceId=DEFAULT_WORKSPACE_ID){const key=String(id||''),builtin=ORCHESTRA_REGISTRY.find(x=>x.id===key);if(builtin)return clone(builtin);const state=await loadOrchestraState({workspaceId});return clone(state.orchestras.find(x=>x.id===key)||null);}
export async function upsertCustomOrchestra(input={},options={}){const workspaceId=workspaceKey(options.workspaceId),current=await loadOrchestraState({force:true,workspaceId}),existingId=String(input.id||'').trim(),existing=current.orchestras.find(x=>x.id===existingId),id=existing?.id||makeId(input.name);const checked=validateOrchestraDefinition({...input,id,source:'custom'});if(!checked.ok)throw Object.assign(new Error(checked.errors.map(x=>x.message).join(' ')),{statusCode:400,code:checked.errors[0]?.code||'ORCHESTRA_INVALID',errors:checked.errors});const now=new Date().toISOString(),next={...checked.orchestra,createdAt:existing?.createdAt||now,updatedAt:now},orchestras=existing?current.orchestras.map(x=>x.id===id?next:x):[...current.orchestras,next];const state=await saveOrchestraState({...current,orchestras},{expectedRevision:options.expectedRevision??current.revision,workspaceId});return{state,orchestra:state.orchestras.find(x=>x.id===id)};}
export async function deleteCustomOrchestra(id,options={}){const workspaceId=workspaceKey(options.workspaceId),current=await loadOrchestraState({force:true,workspaceId}),key=String(id||'');if(ORCHESTRA_REGISTRY.some(x=>x.id===key))throw Object.assign(new Error('Sisäänrakennettua orkesteria ei voi poistaa.'),{statusCode:400,code:'ORCHESTRA_BUILTIN'});if(!current.orchestras.some(x=>x.id===key))throw Object.assign(new Error('Orkesteria ei löytynyt.'),{statusCode:404,code:'ORCHESTRA_NOT_FOUND'});const state=await saveOrchestraState({...current,orchestras:current.orchestras.filter(x=>x.id!==key)},{expectedRevision:options.expectedRevision??current.revision,workspaceId});return{state};}
export function __resetOrchestraStoreForTests(){caches.clear();memoryStates.clear();}
