import crypto from 'node:crypto';
import { CORE_VERSION, ORCHESTRA_REGISTRY, validateOrchestraDefinition } from './core-registry.js';
import { DEFAULT_WORKSPACE_ID, requireWorkspace } from './workspace-store.js';
import { stateBackendMode, stateBackendStatus, readStateJson, writeStateJson } from './state-backend.js';
import { getWorkspaceTemplate } from './workspace-templates.js';

export const ORCHESTRA_STORE_FORMAT='anomancer-orchestra-store/v2';
const CACHE_TTL_MS=5_000;
const clone=value=>JSON.parse(JSON.stringify(value));
const clean=value=>String(value??'').trim();
const caches=new Map(),memoryStates=new Map();
function workspaceKey(id){return String(id||DEFAULT_WORKSPACE_ID).trim()||DEFAULT_WORKSPACE_ID;}
const STORE_ENV=['ANOMANCER_ORCHESTRA_STORE'];
function keyFor(id){return `orchestras/${workspaceKey(id)}.json`;}
function configuredMode(){return stateBackendMode(STORE_ENV);}
export function orchestraStoreStatus(workspaceId=DEFAULT_WORKSPACE_ID){const id=workspaceKey(workspaceId),backend=stateBackendStatus(keyFor(id),STORE_ENV);return{format:ORCHESTRA_STORE_FORMAT,coreVersion:CORE_VERSION,workspaceId:id,...backend};}
function normalizeCustomList(items=[]){const out=[],ids=new Set();for(const raw of Array.isArray(items)?items:[]){const checked=validateOrchestraDefinition({...raw,source:'custom'},{custom:true});if(!checked.ok)continue;const o=checked.orchestra;if(ids.has(o.id)||ORCHESTRA_REGISTRY.some(item=>item.id===o.id))continue;ids.add(o.id);out.push({...o,createdAt:clean(raw.createdAt),updatedAt:clean(raw.updatedAt)});}return out.slice(0,50);}
function defaultState(workspaceId=DEFAULT_WORKSPACE_ID){return{format:ORCHESTRA_STORE_FORMAT,coreVersion:CORE_VERSION,workspaceId:workspaceKey(workspaceId),revision:0,updatedAt:'',orchestras:[]};}
function normalizeState(input={},workspaceId=DEFAULT_WORKSPACE_ID){return{format:ORCHESTRA_STORE_FORMAT,coreVersion:CORE_VERSION,workspaceId:workspaceKey(workspaceId),revision:Math.max(0,Number(input.revision)||0),updatedAt:clean(input.updatedAt),orchestras:normalizeCustomList(input.orchestras)};}
export async function loadOrchestraState({force=false,workspaceId=DEFAULT_WORKSPACE_ID}={}){const id=workspaceKey(workspaceId),m=configuredMode();if(m==='memory'){if(!memoryStates.has(id))memoryStates.set(id,defaultState(id));return clone(memoryStates.get(id));}const cached=caches.get(id);if(!force&&cached&&cached.expiresAt>Date.now())return clone(cached.state);const stored=await readStateJson(keyFor(id),defaultState(id),STORE_ENV),state=normalizeState(stored.value,id);caches.set(id,{state,version:stored.version,expiresAt:Date.now()+CACHE_TTL_MS});return clone(state);}
export async function saveOrchestraState(input,{expectedRevision=null,workspaceId=DEFAULT_WORKSPACE_ID}={}){const id=workspaceKey(workspaceId),m=configuredMode();if(m==='memory'){const current=await loadOrchestraState({force:true,workspaceId:id});if(expectedRevision!==null&&Number(expectedRevision)!==current.revision)throw Object.assign(new Error('Orkesterirekisteri muuttui toisessa istunnossa.'),{statusCode:409,code:'ORCHESTRA_REVISION_CONFLICT'});const next=normalizeState({...input,revision:current.revision+1,updatedAt:new Date().toISOString()},id);memoryStates.set(id,next);return clone(next);}caches.delete(id);const current=await loadOrchestraState({force:true,workspaceId:id}),version=caches.get(id)?.version??null;if(expectedRevision!==null&&Number(expectedRevision)!==current.revision)throw Object.assign(new Error('Orkesterirekisteri muuttui toisessa istunnossa.'),{statusCode:409,code:'ORCHESTRA_REVISION_CONFLICT'});const next=normalizeState({...input,revision:current.revision+1,updatedAt:new Date().toISOString()},id);try{const written=await writeStateJson(keyFor(id),next,{expectedVersion:version,envNames:STORE_ENV});caches.set(id,{state:next,version:written.version,expiresAt:Date.now()+CACHE_TTL_MS});return clone(next);}catch(error){if(error?.code==='STATE_WRITE_CONFLICT')throw Object.assign(new Error('Orkesterirekisterin rinnakkaisuuskonflikti.'),{statusCode:409,code:'ORCHESTRA_WRITE_CONFLICT'});throw error;}}
function makeId(name='orchestra'){const slug=String(name).toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,36)||'orchestra';return`custom-${slug}-${crypto.randomBytes(3).toString('hex')}`;}
async function orchestraPolicy(workspaceId){const workspace=await requireWorkspace(workspaceId),template=getWorkspaceTemplate(workspace.templateId);return{workspace,template,builtins:ORCHESTRA_REGISTRY.filter(item=>(template?.builtInOrchestraIds||[]).includes(item.id)).map(clone)};}
export async function listAvailableOrchestras(workspaceId=DEFAULT_WORKSPACE_ID){const policy=await orchestraPolicy(workspaceId),state=await loadOrchestraState({workspaceId:policy.workspace.id});return{state,builtins:policy.builtins,custom:state.orchestras.map(clone),all:[...policy.builtins,...state.orchestras.map(clone)]};}
export async function getAvailableOrchestra(id='editorial',workspaceId=DEFAULT_WORKSPACE_ID){const key=String(id||''),policy=await orchestraPolicy(workspaceId),builtin=policy.builtins.find(x=>x.id===key);if(builtin)return clone(builtin);const state=await loadOrchestraState({workspaceId:policy.workspace.id});return clone(state.orchestras.find(x=>x.id===key)||null);}
export async function upsertCustomOrchestra(input={},options={}){const workspaceId=workspaceKey(options.workspaceId),policy=await orchestraPolicy(workspaceId),current=await loadOrchestraState({force:true,workspaceId}),existingId=String(input.id||'').trim(),existing=current.orchestras.find(x=>x.id===existingId),id=existing?.id||makeId(input.name);const checked=validateOrchestraDefinition({...input,id,source:'custom'},{custom:true});if(!checked.ok)throw Object.assign(new Error(checked.errors.map(x=>x.message).join(' ')),{statusCode:400,code:checked.errors[0]?.code||'ORCHESTRA_INVALID',errors:checked.errors});const allowed=new Set(policy.template?.allowedAgentIds||[]),forbidden=checked.orchestra.stages.filter(agentId=>!allowed.has(agentId));if(forbidden.length)throw Object.assign(new Error(`Työtilatyyppi ei salli agentteja: ${[...new Set(forbidden)].join(', ')}`),{statusCode:400,code:'WORKSPACE_AGENT_NOT_ALLOWED'});const now=new Date().toISOString(),next={...checked.orchestra,createdAt:existing?.createdAt||now,updatedAt:now},orchestras=existing?current.orchestras.map(x=>x.id===id?next:x):[...current.orchestras,next];const state=await saveOrchestraState({...current,orchestras},{expectedRevision:options.expectedRevision??current.revision,workspaceId});return{state,orchestra:state.orchestras.find(x=>x.id===id)};}
export async function deleteCustomOrchestra(id,options={}){const workspaceId=workspaceKey(options.workspaceId),current=await loadOrchestraState({force:true,workspaceId}),key=String(id||'');if(ORCHESTRA_REGISTRY.some(x=>x.id===key))throw Object.assign(new Error('Sisäänrakennettua orkesteria ei voi poistaa.'),{statusCode:400,code:'ORCHESTRA_BUILTIN'});if(!current.orchestras.some(x=>x.id===key))throw Object.assign(new Error('Orkesteria ei löytynyt.'),{statusCode:404,code:'ORCHESTRA_NOT_FOUND'});const state=await saveOrchestraState({...current,orchestras:current.orchestras.filter(x=>x.id!==key)},{expectedRevision:options.expectedRevision??current.revision,workspaceId});return{state};}
export function __resetOrchestraStoreForTests(){caches.clear();memoryStates.clear();}
