import { CORE_VERSION, digest } from './core-registry.js';
import { DEFAULT_WORKSPACE_ID } from './workspace-store.js';
import { stateBackendMode, stateBackendStatus, readStateJson, writeStateJson } from './state-backend.js';

export const RUN_STORE_FORMAT='anomancer-run-store/v2';
export const RUN_RECORD_FORMAT='anomancer-run-record/v2';
const HISTORY_LIMIT=60;
const CACHE_TTL_MS=3000;
const clone=v=>JSON.parse(JSON.stringify(v));
const clean=v=>String(v??'').trim();
const caches=new Map(),memoryStates=new Map(),writeQueues=new Map();
function workspaceKey(id){return clean(id)||DEFAULT_WORKSPACE_ID;}
const STORE_ENV=['ANOMANCER_RUN_STORE'];
function keyFor(id){return `runs/${workspaceKey(id)}.json`;}
function mode(){return stateBackendMode(STORE_ENV);}
export function runStoreStatus(workspaceId=DEFAULT_WORKSPACE_ID){const id=workspaceKey(workspaceId),backend=stateBackendStatus(keyFor(id),STORE_ENV);return{format:RUN_STORE_FORMAT,coreVersion:CORE_VERSION,workspaceId:id,...backend,containsRawPrompt:false,containsRawOutput:false,historyLimit:HISTORY_LIMIT};}
function emptyUsage(){return{runs:0,inputTokens:0,outputTokens:0,totalTokens:0,reasoningTokens:0,durationMs:0,estimatedCostEuro:0,pricedReceipts:0,fallbacks:0,toolAllows:0,toolDenies:0,toolHumanRequired:0,providers:{},agents:{},orchestras:{}};}
function defaultState(workspaceId=DEFAULT_WORKSPACE_ID){return{format:RUN_STORE_FORMAT,coreVersion:CORE_VERSION,workspaceId:workspaceKey(workspaceId),revision:0,updatedAt:'',chainHead:'GENESIS',runs:[],lifetime:emptyUsage()};}
function compactReceipt(r={}){const estimated=estimateReceiptCost(r);return{format:r.format||'',id:clean(r.id),workspaceId:workspaceKey(r.workspaceId),orchestraRunId:clean(r.orchestraRunId),stageIndex:Number.isInteger(r.stageIndex)?r.stageIndex:null,agent:r.agent||null,model:r.model||null,routing:r.routing||null,runtime:r.runtime||null,usage:{...(r.usage||{}),costEuro:estimated},tools:Array.isArray(r.tools)?r.tools:[],toolPolicy:Array.isArray(r.toolPolicy)?r.toolPolicy:[],status:clean(r.status)||'completed',inputHash:clean(r.inputHash),outputHash:clean(r.outputHash),startedAt:clean(r.startedAt),finishedAt:clean(r.finishedAt),durationMs:Number(r.durationMs)||0,humanApprovalRequired:r.humanApprovalRequired!==false};}
function usageOfReceipts(receipts=[]){const u=emptyUsage();for(const r of receipts){const x=r.usage||{};u.inputTokens+=Number(x.inputTokens)||0;u.outputTokens+=Number(x.outputTokens)||0;u.totalTokens+=Number(x.totalTokens)||0;u.reasoningTokens+=Number(x.reasoningTokens)||0;u.durationMs+=Number(r.durationMs)||0;const p=clean(r.model?.provider)||'unknown';u.providers[p]=(u.providers[p]||0)+(Number(x.totalTokens)||0);const a=clean(r.agent?.id)||'unknown';u.agents[a]=(u.agents[a]||0)+(Number(x.totalTokens)||0);if(r.routing?.fallbackUsed)u.fallbacks++;for(const d of r.toolPolicy||[]){if(d.outcome==='allow')u.toolAllows++;else if(d.outcome==='human_required')u.toolHumanRequired++;else u.toolDenies++;}const c=x.costEuro===null||x.costEuro===undefined?null:Number(x.costEuro);if(c!==null&&Number.isFinite(c)){u.estimatedCostEuro+=c;u.pricedReceipts++;}}return u;}
function mergeUsage(a,b){const out=emptyUsage();for(const k of ['runs','inputTokens','outputTokens','totalTokens','reasoningTokens','durationMs','estimatedCostEuro','pricedReceipts','fallbacks','toolAllows','toolDenies','toolHumanRequired'])out[k]=(Number(a?.[k])||0)+(Number(b?.[k])||0);for(const key of ['providers','agents','orchestras'])for(const id of new Set([...Object.keys(a?.[key]||{}),...Object.keys(b?.[key]||{})]))out[key][id]=(Number(a?.[key]?.[id])||0)+(Number(b?.[key]?.[id])||0);return out;}
function normalizeRun(raw={},workspaceId=DEFAULT_WORKSPACE_ID){const id=workspaceKey(workspaceId),receipts=(Array.isArray(raw.receipts)?raw.receipts:[]).map(r=>compactReceipt({...r,workspaceId:id})).filter(x=>x.id),usage=usageOfReceipts(receipts);return{format:RUN_RECORD_FORMAT,coreVersion:CORE_VERSION,workspaceId:id,id:clean(raw.id||raw.orchestraRunId).slice(0,120),orchestraRunId:clean(raw.orchestraRunId||raw.id).slice(0,120),orchestra:raw.orchestra?{id:clean(raw.orchestra.id),name:clean(raw.orchestra.name),orchestraHash:clean(raw.orchestra.orchestraHash)}:null,status:['running','checkpoint','stopped','completed','degraded','failed','aborted'].includes(raw.status)?raw.status:'running',humanApproval:{required:true,status:['pending','editor_applied'].includes(raw.humanApproval?.status)?raw.humanApproval.status:'pending',appliedAt:clean(raw.humanApproval?.appliedAt)},startedAt:clean(raw.startedAt)||receipts[0]?.startedAt||'',finishedAt:clean(raw.finishedAt),updatedAt:clean(raw.updatedAt),degradedStages:Array.isArray(raw.degradedStages)?raw.degradedStages.map(clean).filter(Boolean):[],disabledStages:Array.isArray(raw.disabledStages)?raw.disabledStages.map(clean).filter(Boolean):[],error:raw.error?{code:clean(raw.error.code),message:clean(raw.error.message).slice(0,500)}:null,receipts,usage,receiptCount:receipts.length,previousRunHash:clean(raw.previousRunHash)||'',runHash:clean(raw.runHash)||'',counted:Boolean(raw.counted)};}
function normalizeState(raw={},workspaceId=DEFAULT_WORKSPACE_ID){const id=workspaceKey(workspaceId),runs=(Array.isArray(raw.runs)?raw.runs:[]).map(r=>normalizeRun(r,id)).filter(r=>r.id).slice(-HISTORY_LIMIT);return{format:RUN_STORE_FORMAT,coreVersion:CORE_VERSION,workspaceId:id,revision:Math.max(0,Number(raw.revision)||0),updatedAt:clean(raw.updatedAt),chainHead:clean(raw.chainHead)||'GENESIS',runs,lifetime:{...emptyUsage(),...(raw.lifetime||{})}};}
function rateEnv(provider,kind){const key=`ANOMANCER_COST_${String(provider||'').toUpperCase().replace(/[^A-Z0-9]/g,'_')}_${kind}_EUR_PER_M`,n=Number(process.env[key]);return Number.isFinite(n)&&n>=0?n:null;}
export function estimateReceiptCost(receipt={}){const provider=clean(receipt.model?.provider),input=rateEnv(provider,'INPUT'),output=rateEnv(provider,'OUTPUT');if(input===null||output===null)return null;const u=receipt.usage||{};return((Number(u.inputTokens)||0)*input+(Number(u.outputTokens)||0)*output)/1_000_000;}
export async function loadRunState({force=false,workspaceId=DEFAULT_WORKSPACE_ID}={}){const id=workspaceKey(workspaceId),m=mode();if(m==='memory'){if(!memoryStates.has(id))memoryStates.set(id,defaultState(id));return clone(memoryStates.get(id));}const cached=caches.get(id);if(!force&&cached&&cached.expiresAt>Date.now())return clone(cached.state);const stored=await readStateJson(keyFor(id),defaultState(id),STORE_ENV),state=normalizeState(stored.value,id);caches.set(id,{state,version:stored.version,expiresAt:Date.now()+CACHE_TTL_MS});return clone(state);}
const RUN_WRITE_ATTEMPTS=12;
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function runWriteDelay(attempt){return Math.min(480,24*(2**attempt))+Math.floor(Math.random()*41);}
function queueWrite(workspaceId,task){const id=workspaceKey(workspaceId),previous=writeQueues.get(id)||Promise.resolve();const queued=previous.catch(()=>{}).then(task);const tracked=queued.finally(()=>{if(writeQueues.get(id)===tracked)writeQueues.delete(id);});writeQueues.set(id,tracked);return queued;}
async function mutate(workspaceId,fn){const id=workspaceKey(workspaceId);return queueWrite(id,async()=>{const m=mode();if(m==='memory'){const current=await loadRunState({force:true,workspaceId:id}),next=normalizeState(fn(clone(current)),id);next.revision=current.revision+1;next.updatedAt=new Date().toISOString();memoryStates.set(id,next);return clone(next);}for(let attempt=0;attempt<RUN_WRITE_ATTEMPTS;attempt++){caches.delete(id);const current=await loadRunState({force:true,workspaceId:id}),version=caches.get(id)?.version??null,next=normalizeState(fn(clone(current)),id);next.revision=current.revision+1;next.updatedAt=new Date().toISOString();try{const written=await writeStateJson(keyFor(id),next,{expectedVersion:version,envNames:STORE_ENV});caches.set(id,{state:next,version:written.version,expiresAt:Date.now()+CACHE_TTL_MS});return clone(next);}catch(error){if(error?.code==='STATE_WRITE_CONFLICT'&&attempt<RUN_WRITE_ATTEMPTS-1){await wait(runWriteDelay(attempt));continue;}if(error?.code==='STATE_WRITE_CONFLICT')throw Object.assign(new Error('Run Storen rinnakkaisuuskonflikti ei ratkennut automaattisilla uudelleenyrityksillä.'),{statusCode:409,code:'RUN_WRITE_CONFLICT'});throw error;}}throw Object.assign(new Error('Run Storen rinnakkaisuuskonflikti ei ratkennut automaattisilla uudelleenyrityksillä.'),{statusCode:409,code:'RUN_WRITE_CONFLICT'});});}
function finalizeHash(run,previous){const u=run.usage||{},usage={inputTokens:u.inputTokens||0,outputTokens:u.outputTokens||0,totalTokens:u.totalTokens||0,reasoningTokens:u.reasoningTokens||0,fallbacks:u.fallbacks||0,toolAllows:u.toolAllows||0,toolDenies:u.toolDenies||0,toolHumanRequired:u.toolHumanRequired||0,providers:u.providers||{},agents:u.agents||{}},payload={id:run.id,orchestra:run.orchestra,status:run.status,startedAt:run.startedAt,finishedAt:run.finishedAt,receiptIds:run.receipts.map(r=>r.id),receiptHashes:run.receipts.map(r=>r.outputHash),usage,previousRunHash:previous};return digest(payload);}
function mergeReceiptsIntoRun(run, receipts, workspaceId){
  if(!Array.isArray(receipts)||!receipts.length)return;
  const seen=new Set(run.receipts.map(r=>r.id));
  for(const receipt of receipts){
    if(!receipt?.id||!receipt?.orchestraRunId||clean(receipt.orchestraRunId)!==run.id||seen.has(clean(receipt.id)))continue;
    run.receipts.push(compactReceipt({...receipt,workspaceId}));
    seen.add(clean(receipt.id));
  }
}
export async function appendRunReceipt(receipt){if(!receipt?.id||!receipt?.orchestraRunId)return null;const workspaceId=workspaceKey(receipt.workspaceId),state=await mutate(workspaceId,s=>{let run=s.runs.find(r=>r.id===receipt.orchestraRunId);if(!run){run=normalizeRun({id:receipt.orchestraRunId,orchestraRunId:receipt.orchestraRunId,orchestra:receipt.orchestra,status:'running',startedAt:receipt.startedAt,receipts:[]},workspaceId);s.runs.push(run);}mergeReceiptsIntoRun(run,[receipt],workspaceId);run.updatedAt=new Date().toISOString();return s;});return state.runs.find(r=>r.id===receipt.orchestraRunId)||null;}
export async function checkpointRun(id,patch={},workspaceId=DEFAULT_WORKSPACE_ID){const key=clean(id),wid=workspaceKey(workspaceId),state=await mutate(wid,s=>{let run=s.runs.find(r=>r.id===key);if(!run){run=normalizeRun({id:key,orchestraRunId:key,orchestra:patch.orchestra,status:'running',startedAt:patch.startedAt||new Date().toISOString(),receipts:[]},wid);s.runs.push(run);}mergeReceiptsIntoRun(run,patch.receipts,wid);run.status=patch.status==='stopped'?'stopped':'checkpoint';run.degradedStages=Array.isArray(patch.degradedStages)?patch.degradedStages.map(clean).filter(Boolean):run.degradedStages;run.disabledStages=Array.isArray(patch.disabledStages)?patch.disabledStages.map(clean).filter(Boolean):run.disabledStages;run.error=patch.error?{code:clean(patch.error.code),message:clean(patch.error.message).slice(0,500)}:null;run.orchestra=run.orchestra||patch.orchestra||null;run.updatedAt=new Date().toISOString();return s;});return state.runs.find(r=>r.id===key)||null;}
export async function finalizeRun(id,patch={},workspaceId=DEFAULT_WORKSPACE_ID){const key=clean(id),wid=workspaceKey(workspaceId),state=await mutate(wid,s=>{let run=s.runs.find(r=>r.id===key);if(!run){run=normalizeRun({id:key,orchestraRunId:key,orchestra:patch.orchestra,status:'running',startedAt:patch.startedAt||new Date().toISOString(),receipts:[]},wid);s.runs.push(run);}mergeReceiptsIntoRun(run,patch.receipts,wid);run.status=['completed','degraded','failed','aborted'].includes(patch.status)?patch.status:run.status;run.finishedAt=clean(patch.finishedAt)||new Date().toISOString();run.degradedStages=Array.isArray(patch.degradedStages)?patch.degradedStages.map(clean).filter(Boolean):run.degradedStages;run.disabledStages=Array.isArray(patch.disabledStages)?patch.disabledStages.map(clean).filter(Boolean):run.disabledStages;run.error=patch.error?{code:clean(patch.error.code),message:clean(patch.error.message).slice(0,500)}:run.error;run.orchestra=run.orchestra||patch.orchestra||null;run.updatedAt=new Date().toISOString();run.usage=usageOfReceipts(run.receipts);if(!run.runHash){run.previousRunHash=s.chainHead||'GENESIS';run.runHash=finalizeHash(run,run.previousRunHash);s.chainHead=run.runHash;}if(!run.counted){s.lifetime=mergeUsage(s.lifetime,{...run.usage,runs:1,orchestras:{[run.orchestra?.id||'unknown']:1}});run.counted=true;}return s;});return state.runs.find(r=>r.id===key)||null;}
export async function markRunApplied(id,workspaceId=DEFAULT_WORKSPACE_ID){const key=clean(id),wid=workspaceKey(workspaceId),state=await mutate(wid,s=>{const run=s.runs.find(r=>r.id===key);if(!run)throw Object.assign(new Error('Ajoa ei löytynyt.'),{statusCode:404,code:'RUN_NOT_FOUND'});run.humanApproval={required:true,status:'editor_applied',appliedAt:new Date().toISOString()};run.updatedAt=new Date().toISOString();return s;});return state.runs.find(r=>r.id===key);}
export async function listRuns({limit=30,status='',agent='',provider='',orchestra='',workspaceId=DEFAULT_WORKSPACE_ID}={}){const wid=workspaceKey(workspaceId),s=await loadRunState({workspaceId:wid});let rows=[...s.runs].reverse();if(status)rows=rows.filter(r=>r.status===status);if(orchestra)rows=rows.filter(r=>r.orchestra?.id===orchestra);if(agent)rows=rows.filter(r=>r.receipts.some(x=>x.agent?.id===agent));if(provider)rows=rows.filter(r=>r.receipts.some(x=>x.model?.provider===provider));return{workspaceId:wid,runs:rows.slice(0,Math.max(1,Math.min(60,Number(limit)||30))).map(runSummary),usage:usageSnapshotFromState(s),chainOk:verifyRunChain(s.runs),store:runStoreStatus(wid)};}
function runSummary(r){return{workspaceId:r.workspaceId,id:r.id,orchestraRunId:r.orchestraRunId,orchestra:r.orchestra,status:r.status,humanApproval:r.humanApproval,startedAt:r.startedAt,finishedAt:r.finishedAt,updatedAt:r.updatedAt,degradedStages:r.degradedStages,disabledStages:r.disabledStages,error:r.error,receiptCount:r.receiptCount||r.receipts.length,usage:r.usage,previousRunHash:r.previousRunHash,runHash:r.runHash};}
export async function getRun(id,workspaceId=DEFAULT_WORKSPACE_ID){const s=await loadRunState({workspaceId}),r=s.runs.find(x=>x.id===clean(id));return r?clone(r):null;}
function usageSnapshotFromState(s){const recent=s.runs.reduce((acc,r)=>{const final=['completed','degraded','failed','aborted'].includes(r.status);return mergeUsage(acc,{...r.usage,runs:final?1:0,orchestras:final?{[r.orchestra?.id||'unknown']:1}:{}});},emptyUsage());return{workspaceId:s.workspaceId,recent,lifetime:s.lifetime,chainHead:s.chainHead,historySize:s.runs.length,historyLimit:HISTORY_LIMIT};}
export async function usageSnapshot(workspaceId=DEFAULT_WORKSPACE_ID){return usageSnapshotFromState(await loadRunState({workspaceId}));}
export function verifyRunChain(runs=[]){const ordered=[...runs].filter(x=>x.runHash).sort((a,b)=>String(a.finishedAt).localeCompare(String(b.finishedAt)));let previous=ordered[0]?.previousRunHash||'GENESIS';for(const r of ordered){if(r.previousRunHash!==previous)return false;if(finalizeHash(r,previous)!==r.runHash)return false;previous=r.runHash;}return true;}
export function __resetRunStoreForTests(){caches.clear();memoryStates.clear();}
