import crypto from 'node:crypto';
import { AGENT_RUNTIME_FORMAT, CORE_VERSION, normalizeAgentRuntime, normalizeAgentRuntimeMap, listAgentIds, validateOrchestraDefinition, getOrchestra } from './core-registry.js';
import { getAvailableOrchestra } from './orchestra-store.js';
import { DEFAULT_WORKSPACE_ID, requireWorkspace } from './workspace-store.js';
import { stateBackendMode, stateBackendStatus, readStateJson, writeStateJson } from './state-backend.js';
import { ANOMANCER_TEMPLATE_ID, getConstitution, getWorkspaceTemplate } from './workspace-templates.js';
import { artifactBoundaryForWorkspace } from './artifact-boundary.js';

export const RUNTIME_STORE_FORMAT='anomancer-runtime-store/v3';
export const RUNTIME_SNAPSHOT_FORMAT='anomancer-runtime-snapshot/v4';
const CACHE_TTL_MS=5_000;
const SNAPSHOT_TTL_SECONDS=60*60*12;
const clone=value=>JSON.parse(JSON.stringify(value));
const clean=value=>String(value??'').trim();
const caches=new Map(),memoryStates=new Map();
function workspaceKey(id){return clean(id)||DEFAULT_WORKSPACE_ID;}
function b64url(input){return Buffer.from(input).toString('base64url');}
function fromB64url(input){return Buffer.from(String(input),'base64url').toString('utf8');}
function safeEqual(a,b){const aa=Buffer.from(String(a)),bb=Buffer.from(String(b));return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb);}
const STORE_ENV=['ANOMANCER_RUNTIME_STORE'];
function keyFor(id){return `runtime/${workspaceKey(id)}.json`;}
function configuredMode(){return stateBackendMode(STORE_ENV);}
export function runtimeStoreStatus(workspaceId=DEFAULT_WORKSPACE_ID){const id=workspaceKey(workspaceId),backend=stateBackendStatus(keyFor(id),STORE_ENV);return{format:RUNTIME_STORE_FORMAT,coreVersion:CORE_VERSION,workspaceId:id,...backend};}
function defaultProfiles(){return normalizeAgentRuntimeMap({});}
function strictProfiles(input={}){const source=input&&typeof input==='object'?input:{};return Object.fromEntries(listAgentIds().map(id=>{const fallback=normalizeAgentRuntime(id,{}),raw=source[id]||{};return[id,raw.contractHash===fallback.contractHash?normalizeAgentRuntime(id,raw):fallback];}));}
function defaultState(workspaceId=DEFAULT_WORKSPACE_ID){return{format:RUNTIME_STORE_FORMAT,coreVersion:CORE_VERSION,workspaceId:workspaceKey(workspaceId),revision:0,updatedAt:'',profiles:defaultProfiles()};}
function normalizeState(input={},workspaceId=DEFAULT_WORKSPACE_ID){return{format:RUNTIME_STORE_FORMAT,coreVersion:CORE_VERSION,workspaceId:workspaceKey(workspaceId),revision:Math.max(0,Number(input.revision)||0),updatedAt:clean(input.updatedAt),profiles:strictProfiles(input.profiles||{})};}
export async function loadRuntimeState({force=false,workspaceId=DEFAULT_WORKSPACE_ID}={}){const id=workspaceKey(workspaceId),m=configuredMode();if(m==='memory'){if(!memoryStates.has(id))memoryStates.set(id,defaultState(id));return clone(memoryStates.get(id));}const cached=caches.get(id);if(!force&&cached&&cached.expiresAt>Date.now())return clone(cached.state);const stored=await readStateJson(keyFor(id),defaultState(id),STORE_ENV),state=normalizeState(stored.value,id);caches.set(id,{state,version:stored.version,expiresAt:Date.now()+CACHE_TTL_MS});return clone(state);}
export async function saveRuntimeState(input,{expectedRevision=null,workspaceId=DEFAULT_WORKSPACE_ID}={}){const id=workspaceKey(workspaceId),m=configuredMode();if(m==='memory'){const current=await loadRuntimeState({force:true,workspaceId:id});if(expectedRevision!==null&&Number(expectedRevision)!==current.revision)throw Object.assign(new Error('Runtime Profile muuttui toisessa istunnossa. Päivitä näkymä ja yritä uudelleen.'),{statusCode:409,code:'RUNTIME_REVISION_CONFLICT'});const next=normalizeState({...input,revision:current.revision+1,updatedAt:new Date().toISOString()},id);memoryStates.set(id,next);return clone(next);}caches.delete(id);const current=await loadRuntimeState({force:true,workspaceId:id}),version=caches.get(id)?.version??null;if(expectedRevision!==null&&Number(expectedRevision)!==current.revision)throw Object.assign(new Error('Runtime Profile muuttui toisessa istunnossa. Päivitä näkymä ja yritä uudelleen.'),{statusCode:409,code:'RUNTIME_REVISION_CONFLICT'});const next=normalizeState({...input,revision:current.revision+1,updatedAt:new Date().toISOString()},id);try{const written=await writeStateJson(keyFor(id),next,{expectedVersion:version,envNames:STORE_ENV});caches.set(id,{state:next,version:written.version,expiresAt:Date.now()+CACHE_TTL_MS});return clone(next);}catch(error){if(error?.code==='STATE_WRITE_CONFLICT')throw Object.assign(new Error('Runtime Profile -tallennuksen rinnakkaisuuskonflikti.'),{statusCode:409,code:'RUNTIME_WRITE_CONFLICT'});throw error;}}
export async function getRuntimeProfiles(workspaceId=DEFAULT_WORKSPACE_ID){return(await loadRuntimeState({workspaceId})).profiles;}
export async function getRuntimeProfile(agentId,workspaceId=DEFAULT_WORKSPACE_ID){const state=await loadRuntimeState({workspaceId});return state.profiles?.[agentId]||normalizeAgentRuntime(agentId,{});}
export async function updateRuntimeProfile(agentId,patch={},options={}){if(!listAgentIds().includes(agentId))throw Object.assign(new Error('Tuntematon agentti.'),{statusCode:400,code:'AGENT_UNKNOWN'});const workspaceId=workspaceKey(options.workspaceId),current=await loadRuntimeState({force:true,workspaceId}),base=current.profiles?.[agentId]||{},profile=normalizeAgentRuntime(agentId,{...base,...patch,contractHash:base.contractHash}),profiles={...current.profiles,[agentId]:profile};const state=await saveRuntimeState({...current,profiles},{expectedRevision:options.expectedRevision??current.revision,workspaceId});return{state,profile:state.profiles[agentId]};}
export async function resetRuntimeProfile(agentId,options={}){const workspaceId=workspaceKey(options.workspaceId),current=await loadRuntimeState({force:true,workspaceId}),profiles={...current.profiles};if(agentId){if(!listAgentIds().includes(agentId))throw Object.assign(new Error('Tuntematon agentti.'),{statusCode:400,code:'AGENT_UNKNOWN'});profiles[agentId]=normalizeAgentRuntime(agentId,{});}else for(const id of listAgentIds())profiles[id]=normalizeAgentRuntime(id,{});const state=await saveRuntimeState({...current,profiles},{expectedRevision:options.expectedRevision??current.revision,workspaceId});return{state,profile:agentId?state.profiles[agentId]:null};}
function snapshotSecret(){const secret=process.env.ADMIN_SESSION_SECRET;if(!secret||String(secret).length<32)throw Object.assign(new Error('Runtime snapshot -allekirjoitusavain puuttuu.'),{statusCode:503,code:'RUNTIME_SNAPSHOT_SECRET'});return String(secret);}
function minimalProfiles(profiles={}){return Object.fromEntries(listAgentIds().map(id=>{const p=normalizeAgentRuntime(id,profiles[id]||{});return[id,{format:AGENT_RUNTIME_FORMAT,agentId:id,contractHash:p.contractHash,active:p.active!==false,maxOutputTokens:p.maxOutputTokens,modelTarget:p.modelTarget}];}));}
export function signRuntimeSnapshot({orchestraRunId,profiles,revision=0,orchestra=null,workspace=null,now=Date.now(),ttlSeconds=SNAPSHOT_TTL_SECONDS}={}){const runId=clean(orchestraRunId).slice(0,120);if(!runId)throw Object.assign(new Error('orchestraRunId puuttuu runtime snapshotista.'),{statusCode:400,code:'RUNTIME_SNAPSHOT_RUN'});const selected=orchestra||getOrchestra('editorial'),checked=validateOrchestraDefinition(selected||{});if(!checked.ok)throw Object.assign(new Error('Orkesterin määrittely ei ole kelvollinen Runtime Snapshotiin.'),{statusCode:400,code:'RUNTIME_SNAPSHOT_ORCHESTRA'});const orchestraView={id:checked.orchestra.id,name:checked.orchestra.name,version:checked.orchestra.version,description:checked.orchestra.description,steps:checked.orchestra.steps,stages:checked.orchestra.stages,humanFinalAuthority:true,evidencePolicy:checked.orchestra.evidencePolicy,citationPolicy:checked.orchestra.citationPolicy,visualizationPolicy:checked.orchestra.visualizationPolicy,audiencePolicy:checked.orchestra.audiencePolicy,...(checked.orchestra.continuityPolicy?{continuityPolicy:checked.orchestra.continuityPolicy}:{}),orchestraHash:checked.orchestra.orchestraHash,source:checked.orchestra.source};const template=getWorkspaceTemplate(workspace?.templateId||ANOMANCER_TEMPLATE_ID),constitution=getConstitution(template?.constitutionId),workspaceView={id:clean(workspace?.id)||DEFAULT_WORKSPACE_ID,name:clean(workspace?.name)||'Anomancer',workspaceHash:clean(workspace?.workspaceHash),templateId:template?.id||'',templateHash:template?.templateHash||'',constitutionId:constitution?.id||'',constitutionHash:constitution?.constitutionHash||'',artifactStoreId:template?.artifactStoreId||'',contentAdapterId:template?.contentAdapterId||'',outputAdapterId:template?.outputAdapterId||'',uiProfileId:template?.uiProfileId||''},artifact=artifactBoundaryForWorkspace(workspaceView);const payload={format:RUNTIME_SNAPSHOT_FORMAT,coreVersion:CORE_VERSION,workspaceId:workspaceView.id,workspace:workspaceView,artifact,orchestraRunId:runId,revision:Number(revision)||0,iat:Math.floor(now/1000),exp:Math.floor(now/1000)+ttlSeconds,profiles:minimalProfiles(profiles),orchestra:orchestraView};const body=b64url(JSON.stringify(payload)),sig=crypto.createHmac('sha256',snapshotSecret()).update(body).digest('base64url'),snapshotId=`rts-${crypto.createHash('sha256').update(body).digest('hex').slice(0,20)}`;return{token:`${body}.${sig}`,snapshotId,payload};}
export function verifyRuntimeSnapshot(token,{orchestraRunId,workspaceId,now=Date.now()}={}){try{const[body,sig]=String(token||'').split('.');if(!body||!sig)throw new Error('missing');const expected=crypto.createHmac('sha256',snapshotSecret()).update(body).digest('base64url');if(!safeEqual(sig,expected))throw new Error('signature');const payload=JSON.parse(fromB64url(body));if(payload.format!==RUNTIME_SNAPSHOT_FORMAT||payload.coreVersion!==CORE_VERSION)throw new Error('format');if(payload.exp<=Math.floor(now/1000))throw Object.assign(new Error('Runtime snapshot vanheni.'),{statusCode:409,code:'RUNTIME_SNAPSHOT_EXPIRED'});if(orchestraRunId&&payload.orchestraRunId!==clean(orchestraRunId).slice(0,120))throw Object.assign(new Error('Runtime snapshot ei kuulu tähän orkesteriajoon.'),{statusCode:409,code:'RUNTIME_SNAPSHOT_RUN_MISMATCH'});if(workspaceId&&payload.workspaceId!==workspaceKey(workspaceId))throw Object.assign(new Error('Runtime snapshot kuuluu eri workspaceen.'),{statusCode:409,code:'RUNTIME_SNAPSHOT_WORKSPACE_MISMATCH'});const template=getWorkspaceTemplate(payload.workspace?.templateId),constitution=getConstitution(payload.workspace?.constitutionId),artifact=artifactBoundaryForWorkspace(payload.workspace||{});if(!template||template.templateHash!==payload.workspace?.templateHash||!constitution||constitution.constitutionHash!==payload.workspace?.constitutionHash)throw Object.assign(new Error('Runtime snapshotin Workspace Template tai Constitution vanheni.'),{statusCode:409,code:'RUNTIME_SNAPSHOT_WORKSPACE_STALE'});if(artifact.boundaryHash!==payload.artifact?.boundaryHash)throw Object.assign(new Error('Runtime snapshotin Artifact Boundary ei ole kelvollinen.'),{statusCode:409,code:'RUNTIME_SNAPSHOT_ARTIFACT_STALE'});for(const id of listAgentIds()){const expectedHash=normalizeAgentRuntime(id,{}).contractHash;if(payload.profiles?.[id]?.contractHash!==expectedHash)throw Object.assign(new Error(`Runtime snapshotin Agent Contract vanheni: ${id}.`),{statusCode:409,code:'RUNTIME_SNAPSHOT_STALE'});}const checked=validateOrchestraDefinition(payload.orchestra||{});if(!checked.ok||checked.orchestra.orchestraHash!==payload.orchestra?.orchestraHash)throw Object.assign(new Error('Runtime snapshotin Orchestra Contract ei ole kelvollinen.'),{statusCode:409,code:'RUNTIME_SNAPSHOT_ORCHESTRA_STALE'});const profiles=minimalProfiles(payload.profiles||{});return{...payload,profiles,orchestra:{...payload.orchestra,steps:checked.orchestra.steps,stages:checked.orchestra.stages}};}catch(error){if(error?.code)throw error;throw Object.assign(new Error('Runtime snapshot ei ole kelvollinen.'),{statusCode:409,code:'RUNTIME_SNAPSHOT_INVALID'});}}
export async function createRuntimeSnapshot(orchestraRunId,orchestraId='editorial',workspaceId=DEFAULT_WORKSPACE_ID){const workspace=await requireWorkspace(workspaceId),state=await loadRuntimeState({force:true,workspaceId:workspace.id}),orchestra=await getAvailableOrchestra(orchestraId,workspace.id);if(!orchestra)throw Object.assign(new Error('Valittua orkesteria ei löytynyt.'),{statusCode:404,code:'ORCHESTRA_NOT_FOUND'});const signed=signRuntimeSnapshot({orchestraRunId,profiles:state.profiles,revision:state.revision,orchestra,workspace});return{...signed,state,orchestra:signed.payload.orchestra,workspace:signed.payload.workspace};}
export function __resetRuntimeStoreForTests(){caches.clear();memoryStates.clear();}
