import crypto from 'node:crypto';
import { CORE_VERSION, digest } from './core-registry.js';
import { ANOMANCER_TEMPLATE_ID, BLANK_PRIVATE_TEMPLATE_ID, defaultTemplateIdFor, getWorkspaceTemplate, requireWorkspaceTemplate, workspaceTemplateBinding } from './workspace-templates.js';

export const WORKSPACE_STORE_FORMAT='anomancer-workspace-store/v2';
export const WORKSPACE_FORMAT='anomancer-workspace/v2';
export const DEFAULT_WORKSPACE_ID='default';
const DEFAULT_TAG='anomancer-workspace-state';
const DEFAULT_PATH='.anomancer/workspaces.json';
const CACHE_TTL_MS=5_000;
const MAX_WORKSPACES=24;
const clone=v=>JSON.parse(JSON.stringify(v));
const clean=v=>String(v??'').trim();
let cache=null,memoryState=null;

function safeId(v=''){return clean(v).toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60);}
function workspaceView(input={},source='custom'){
  const id=source==='built-in'?DEFAULT_WORKSPACE_ID:safeId(input.id);
  const requested=source==='built-in'?ANOMANCER_TEMPLATE_ID:clean(input.templateId);
  const templateId=getWorkspaceTemplate(requested)?.id||defaultTemplateIdFor(source);
  const binding=workspaceTemplateBinding(templateId);
  const base={format:WORKSPACE_FORMAT,coreVersion:CORE_VERSION,id,name:clean(input.name).slice(0,80)||getWorkspaceTemplate(templateId)?.name||'Untitled Workspace',description:clean(input.description).slice(0,400),status:input.status==='archived'?'archived':'active',source,...binding,createdAt:clean(input.createdAt),updatedAt:clean(input.updatedAt)};
  const hashable={...base};delete hashable.coreVersion;delete hashable.workspaceHash;delete hashable.updatedAt;base.workspaceHash=digest(hashable);return base;
}
export const DEFAULT_WORKSPACE=Object.freeze(workspaceView({id:DEFAULT_WORKSPACE_ID,name:'Anomancer',description:'Nykyinen Anomancer Core, julkaisut ja legacy runtime-, orkesteri- ja run-historia samoilla id- ja tag-refeillä.',status:'active'},'built-in'));

function mode(){const forced=clean(process.env.ANOMANCER_WORKSPACE_STORE).toLowerCase();if(forced==='memory')return'memory';if(forced==='github-tag')return'github-tag';if(process.env.GITHUB_CONTENT_TOKEN&&process.env.GITHUB_REPO?.includes('/'))return'github-tag';return'unconfigured';}
function cfg(){const token=process.env.GITHUB_CONTENT_TOKEN,repo=process.env.GITHUB_REPO,branch=process.env.GITHUB_BRANCH||'master';if(!token||!repo?.includes('/'))throw Object.assign(new Error('Workspace Store ei ole konfiguroitu.'),{statusCode:503,code:'WORKSPACE_STORE_UNCONFIGURED'});return{token,repo,branch,tag:clean(process.env.ANOMANCER_WORKSPACE_TAG)||DEFAULT_TAG,path:clean(process.env.ANOMANCER_WORKSPACE_PATH)||DEFAULT_PATH};}
export function workspaceStoreStatus(){const m=mode(),base={format:WORKSPACE_STORE_FORMAT,coreVersion:CORE_VERSION,mode:m,durable:m==='github-tag',serverAuthoritative:true,secretsExposed:false,maxWorkspaces:MAX_WORKSPACES};if(m==='github-tag'){const c=cfg();return{...base,configured:true,ref:`refs/tags/${c.tag}`,path:c.path};}return{...base,configured:m==='memory'};}
function normalizeCustom(items=[]){const out=[],ids=new Set();for(const raw of Array.isArray(items)?items:[]){const id=safeId(raw.id);if(!id||id===DEFAULT_WORKSPACE_ID||ids.has(id))continue;ids.add(id);out.push(workspaceView({...raw,id},'custom'));}return out.slice(0,MAX_WORKSPACES-1);}
function defaultState(){return{format:WORKSPACE_STORE_FORMAT,coreVersion:CORE_VERSION,revision:0,updatedAt:'',workspaces:[]};}
function normalizeState(raw={}){return{format:WORKSPACE_STORE_FORMAT,coreVersion:CORE_VERSION,revision:Math.max(0,Number(raw.revision)||0),updatedAt:clean(raw.updatedAt),workspaces:normalizeCustom(raw.workspaces)};}
async function gh(path,options={}){const {token}=cfg();const r=await fetch(`https://api.github.com${path}`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'anomancer-core-workspaces-v15.9',...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null;}catch{data={message:text};}if(!r.ok)throw Object.assign(new Error(data?.message||`GitHub ${r.status}`),{statusCode:r.status===404?404:(r.status===409||r.status===422?409:502),code:`WORKSPACE_GITHUB_${r.status}`,githubStatus:r.status,details:data});return data;}
async function tagRef(){const {repo,tag}=cfg();try{return clean((await gh(`/repos/${repo}/git/ref/tags/${encodeURIComponent(tag)}`))?.object?.sha)||null;}catch(e){if(e.statusCode===404)return null;throw e;}}
async function readTag(){const {repo,tag,path}=cfg();try{const d=await gh(`/repos/${repo}/contents/${encodeURI(path)}?ref=${encodeURIComponent(tag)}`);return normalizeState(JSON.parse(Buffer.from(String(d?.content||'').replace(/\n/g,''),'base64').toString('utf8')));}catch(e){if(e.statusCode===404)return defaultState();throw e;}}
async function branchHead(){const {repo,branch}=cfg();return clean((await gh(`/repos/${repo}/git/ref/heads/${encodeURI(branch)}`))?.object?.sha);}
async function commitTree(sha){const {repo}=cfg();return clean((await gh(`/repos/${repo}/git/commits/${sha}`))?.tree?.sha);}
async function writeState(state,{parentSha,create=false}={}){const {repo,tag,path}=cfg(),base=await commitTree(parentSha);const blob=await gh(`/repos/${repo}/git/blobs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:`${JSON.stringify(state,null,2)}\n`,encoding:'utf-8'})});const tree=await gh(`/repos/${repo}/git/trees`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({base_tree:base,tree:[{path,mode:'100644',type:'blob',sha:blob.sha}]})});const commit=await gh(`/repos/${repo}/git/commits`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`core workspaces: revision ${state.revision}`,tree:tree.sha,parents:[parentSha]})});if(create)await gh(`/repos/${repo}/git/refs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:`refs/tags/${tag}`,sha:commit.sha})});else await gh(`/repos/${repo}/git/refs/tags/${encodeURIComponent(tag)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({sha:commit.sha,force:false})});}
export async function loadWorkspaceState({force=false}={}){const m=mode();if(m==='memory'){if(!memoryState)memoryState=defaultState();return clone(memoryState);}if(m==='unconfigured')throw Object.assign(new Error('Workspace Store ei ole konfiguroitu.'),{statusCode:503,code:'WORKSPACE_STORE_UNCONFIGURED'});if(!force&&cache&&cache.expiresAt>Date.now())return clone(cache.state);const ref=await tagRef(),state=ref?await readTag():defaultState();cache={state:normalizeState(state),refSha:ref,expiresAt:Date.now()+CACHE_TTL_MS};return clone(cache.state);}
async function saveState(input,{expectedRevision=null}={}){const m=mode();if(m==='memory'){const current=await loadWorkspaceState({force:true});if(expectedRevision!==null&&Number(expectedRevision)!==current.revision)throw Object.assign(new Error('Workspace-rekisteri muuttui toisessa istunnossa.'),{statusCode:409,code:'WORKSPACE_REVISION_CONFLICT'});memoryState=normalizeState({...input,revision:current.revision+1,updatedAt:new Date().toISOString()});return clone(memoryState);}if(m==='unconfigured')throw Object.assign(new Error('Workspace Store ei ole konfiguroitu.'),{statusCode:503,code:'WORKSPACE_STORE_UNCONFIGURED'});for(let a=0;a<2;a++){cache=null;const current=await loadWorkspaceState({force:true}),ref=cache?.refSha||await tagRef();if(expectedRevision!==null&&Number(expectedRevision)!==current.revision)throw Object.assign(new Error('Workspace-rekisteri muuttui toisessa istunnossa.'),{statusCode:409,code:'WORKSPACE_REVISION_CONFLICT'});const next=normalizeState({...input,revision:current.revision+1,updatedAt:new Date().toISOString()});try{await writeState(next,{parentSha:ref||await branchHead(),create:!ref});cache={state:next,refSha:null,expiresAt:Date.now()+CACHE_TTL_MS};return clone(next);}catch(e){if(e.statusCode===409&&a===0)continue;throw e;}}throw Object.assign(new Error('Workspace Storen rinnakkaisuuskonflikti.'),{statusCode:409,code:'WORKSPACE_WRITE_CONFLICT'});}
function makeId(name='workspace'){const slug=safeId(name).slice(0,32)||'workspace';return `ws-${slug}-${crypto.randomBytes(3).toString('hex')}`;}
export async function listWorkspaces({includeArchived=true}={}){const state=await loadWorkspaceState();const custom=includeArchived?state.workspaces:state.workspaces.filter(w=>w.status!=='archived');return{state,builtins:[clone(DEFAULT_WORKSPACE)],custom:custom.map(clone),all:[clone(DEFAULT_WORKSPACE),...custom.map(clone)]};}
export async function getWorkspace(id=DEFAULT_WORKSPACE_ID){const key=safeId(id)||DEFAULT_WORKSPACE_ID;if(key===DEFAULT_WORKSPACE_ID)return clone(DEFAULT_WORKSPACE);const state=await loadWorkspaceState();return clone(state.workspaces.find(w=>w.id===key)||null);}
export async function requireWorkspace(id=DEFAULT_WORKSPACE_ID,{allowArchived=false}={}){const workspace=await getWorkspace(id);if(!workspace)throw Object.assign(new Error('Workspacea ei löytynyt.'),{statusCode:404,code:'WORKSPACE_NOT_FOUND'});if(workspace.status==='archived'&&!allowArchived)throw Object.assign(new Error('Workspace on arkistoitu.'),{statusCode:409,code:'WORKSPACE_ARCHIVED'});return workspace;}
export async function upsertWorkspace(input={},options={}){const current=await loadWorkspaceState({force:true});const requested=safeId(input.id);if(requested===DEFAULT_WORKSPACE_ID)throw Object.assign(new Error('Sisäänrakennettua Anomancer-työtilaa ei muokata.'),{statusCode:400,code:'WORKSPACE_BUILTIN'});const existing=current.workspaces.find(w=>w.id===requested);if(!existing&&current.workspaces.length>=MAX_WORKSPACES-1)throw Object.assign(new Error('Workspace-raja tuli vastaan.'),{statusCode:409,code:'WORKSPACE_LIMIT'});const requestedTemplate=clean(input.templateId)||existing?.templateId||BLANK_PRIVATE_TEMPLATE_ID,template=requireWorkspaceTemplate(requestedTemplate);if(template.instancePolicy==='singleton-default')throw Object.assign(new Error('Anomancer-template kuuluu vain legacy default -työtilalle.'),{statusCode:400,code:'WORKSPACE_TEMPLATE_SINGLETON'});if(existing&&clean(input.templateId)&&input.templateId!==existing.templateId)throw Object.assign(new Error('Työtilatyyppiä ei voi vaihtaa luonnin jälkeen.'),{statusCode:409,code:'WORKSPACE_TEMPLATE_IMMUTABLE'});const id=existing?.id||makeId(input.name);const now=new Date().toISOString();const next=workspaceView({...input,templateId:template.id,id,status:existing?.status||'active',createdAt:existing?.createdAt||now,updatedAt:now},'custom');const workspaces=existing?current.workspaces.map(w=>w.id===id?next:w):[...current.workspaces,next];const state=await saveState({...current,workspaces},{expectedRevision:options.expectedRevision??current.revision});return{state,workspace:state.workspaces.find(w=>w.id===id)};}
export async function archiveWorkspace(id,{expectedRevision=null,archived=true}={}){const key=safeId(id);if(!key||key===DEFAULT_WORKSPACE_ID)throw Object.assign(new Error('Default-workspacea ei voi arkistoida.'),{statusCode:400,code:'WORKSPACE_BUILTIN'});const current=await loadWorkspaceState({force:true});const existing=current.workspaces.find(w=>w.id===key);if(!existing)throw Object.assign(new Error('Workspacea ei löytynyt.'),{statusCode:404,code:'WORKSPACE_NOT_FOUND'});const next=workspaceView({...existing,status:archived?'archived':'active',updatedAt:new Date().toISOString()},'custom');const state=await saveState({...current,workspaces:current.workspaces.map(w=>w.id===key?next:w)},{expectedRevision:expectedRevision??current.revision});return{state,workspace:state.workspaces.find(w=>w.id===key)};}
export function workspaceStorageScope(workspaceId,{baseTag,basePath}){const id=safeId(workspaceId)||DEFAULT_WORKSPACE_ID;if(id===DEFAULT_WORKSPACE_ID)return{workspaceId:id,tag:baseTag,path:basePath,legacy:true};return{workspaceId:id,tag:`${baseTag}-${id}`.slice(0,120),path:basePath,legacy:false};}
export function workspaceIdFromRequest(req){return safeId(req?.headers?.['x-anomancer-workspace']||DEFAULT_WORKSPACE_ID)||DEFAULT_WORKSPACE_ID;}
export function __resetWorkspaceStoreForTests(){cache=null;memoryState=null;}
