import { getSession, requireCsrf } from '../auth.js';
import { json, readJson, sameOrigin } from '../http.js';
import { listAvailableOrchestras, upsertCustomOrchestra, deleteCustomOrchestra, orchestraStoreStatus } from '../orchestra-store.js';
import { requireWorkspace, workspaceIdFromRequest } from '../workspace-store.js';
function auth(req,res,mutating=false){const session=getSession(req);if(!session){json(res,401,{ok:false,error:'AUTH'});return null;}if(mutating&&(!sameOrigin(req)||!requireCsrf(req,session))){json(res,403,{ok:false,error:'CSRF'});return null;}return session;}
function publicState(state){return{format:state.format,coreVersion:state.coreVersion,workspaceId:state.workspaceId,revision:state.revision,updatedAt:state.updatedAt,orchestras:state.orchestras};}
export default async function handler(req,res){const workspaceId=workspaceIdFromRequest(req);
  if(req.method==='GET'){if(!auth(req,res))return;try{const workspace=await requireWorkspace(workspaceId),data=await listAvailableOrchestras(workspace.id);return json(res,200,{ok:true,workspace,builtins:data.builtins,custom:data.custom,all:data.all,state:publicState(data.state),store:orchestraStoreStatus(workspace.id),degraded:Boolean(data.degraded),degradedReason:data.degradedReason||''});}catch(error){return json(res,error.statusCode||500,{ok:false,error:error.code||'ORCHESTRA_STORE',message:error.message,store:orchestraStoreStatus(workspaceId)});}}
  if(req.method==='POST'||req.method==='PUT'){if(!auth(req,res,true))return;try{const workspace=await requireWorkspace(workspaceId),body=await readJson(req,200_000),result=await upsertCustomOrchestra(body.orchestra||body,{expectedRevision:body.expectedRevision,workspaceId:workspace.id}),data=await listAvailableOrchestras(workspace.id);return json(res,200,{ok:true,workspace,orchestra:result.orchestra,state:publicState(result.state),builtins:data.builtins,custom:data.custom,all:data.all,store:orchestraStoreStatus(workspace.id)});}catch(error){return json(res,error.statusCode||500,{ok:false,error:error.code||'ORCHESTRA_SAVE',message:error.message,errors:error.errors||[]});}}
  if(req.method==='DELETE'){if(!auth(req,res,true))return;try{const workspace=await requireWorkspace(workspaceId),body=await readJson(req,100_000),result=await deleteCustomOrchestra(String(body.id||''),{expectedRevision:body.expectedRevision,workspaceId:workspace.id}),data=await listAvailableOrchestras(workspace.id);return json(res,200,{ok:true,workspace,state:publicState(result.state),builtins:data.builtins,custom:data.custom,all:data.all,store:orchestraStoreStatus(workspace.id)});}catch(error){return json(res,error.statusCode||500,{ok:false,error:error.code||'ORCHESTRA_DELETE',message:error.message});}}
  return json(res,405,{ok:false,error:'METHOD'});
}
