import { getSession, requireCsrf } from '../auth.js';
import { json, readJson, sameOrigin } from '../http.js';
import { listRuns, getRun, finalizeRun, checkpointRun, markRunApplied, runStoreStatus, usageSnapshot } from '../run-store.js';
import { verifyRuntimeSnapshot } from '../runtime-store.js';
import { requireWorkspace, workspaceIdFromRequest } from '../workspace-store.js';
function auth(req,res,mut=false){const s=getSession(req);if(!s){json(res,401,{ok:false,error:'AUTH'});return null;}if(mut&&(!sameOrigin(req)||!requireCsrf(req,s))){json(res,403,{ok:false,error:'CSRF'});return null;}return s;}
export default async function handler(req,res){const workspaceId=workspaceIdFromRequest(req);
  if(req.method==='GET'){if(!auth(req,res))return;try{const workspace=await requireWorkspace(workspaceId),url=new URL(req.url||'/api/admin/runs','http://local'),id=String(url.searchParams.get('id')||'');if(id){const run=await getRun(id,workspace.id);return run?json(res,200,{ok:true,workspace,run,store:runStoreStatus(workspace.id)}):json(res,404,{ok:false,error:'RUN_NOT_FOUND'});}const data=await listRuns({limit:url.searchParams.get('limit'),status:url.searchParams.get('status')||'',agent:url.searchParams.get('agent')||'',provider:url.searchParams.get('provider')||'',orchestra:url.searchParams.get('orchestra')||'',workspaceId:workspace.id});return json(res,200,{ok:true,workspace,...data});}catch(e){return json(res,e.statusCode||500,{ok:false,error:e.code||'RUN_STORE',message:e.message,store:runStoreStatus(workspaceId)});}}
  if(req.method==='POST'){if(!auth(req,res,true))return;try{const workspace=await requireWorkspace(workspaceId),body=await readJson(req,120_000),action=String(body.action||'');if(action==='usage')return json(res,200,{ok:true,workspace,usage:await usageSnapshot(workspace.id),store:runStoreStatus(workspace.id)});if(!body.orchestraRunId||!body.runtimeSnapshotToken)return json(res,409,{ok:false,error:'RUN_SNAPSHOT_REQUIRED'});const snap=verifyRuntimeSnapshot(body.runtimeSnapshotToken,{orchestraRunId:String(body.orchestraRunId),workspaceId:workspace.id});if(action==='checkpoint'){const run=await checkpointRun(body.orchestraRunId,{status:body.status,startedAt:body.startedAt,degradedStages:body.degradedStages,disabledStages:body.disabledStages,error:body.error,orchestra:snap.orchestra},workspace.id);return json(res,200,{ok:true,workspace,run});}if(action==='finalize'){const run=await finalizeRun(body.orchestraRunId,{status:body.status,finishedAt:body.finishedAt,degradedStages:body.degradedStages,disabledStages:body.disabledStages,error:body.error,orchestra:snap.orchestra},workspace.id);return json(res,200,{ok:true,workspace,run});}if(action==='applied'){const run=await markRunApplied(body.orchestraRunId,workspace.id);return json(res,200,{ok:true,workspace,run});}return json(res,400,{ok:false,error:'RUN_ACTION'});}catch(e){return json(res,e.statusCode||500,{ok:false,error:e.code||'RUN_ACTION',message:e.message});}}
  return json(res,405,{ok:false,error:'METHOD'});
}
