import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { CORE_VERSION } from '../../server/core-registry.js';
import { discoverMancerPackages, loadMancerPackage, MANCER_PACKAGE_FORMAT } from '../../server/mancer-registry.js';
import { WORKSPACE_TEMPLATE_REGISTRY, CONSTITUTION_REGISTRY } from '../../server/workspace-templates.js';
import { __resetWorkspaceStoreForTests, upsertWorkspace, getWorkspace } from '../../server/workspace-store.js';
import { artifactBoundaryForWorkspace } from '../../server/artifact-boundary.js';
import { __resetMancerArtifactStoreForTests, loadMancerArtifact, saveMancerArtifact } from '../../server/mancer-artifact-store.js';
import mancerArtifactHandler from '../../server/admin-routes/mancer-artifact.js';
import { signSession, verifySession, csrfForSession } from '../../server/auth.js';
import { EventEmitter } from 'node:events';
let passed=0;const test=async(name,fn)=>{await fn();passed++;console.log(`✓ ${name}`)};
function resMock(){return{statusCode:200,headers:{},body:'',setHeader(k,v){this.headers[String(k).toLowerCase()]=v},end(v=''){this.body+=v}}}
function reqMock({method='GET',body,headers={},url='/api/admin/content?resource=mancer-artifact'}={}){const r=new EventEmitter();r.method=method;r.headers=headers;r.url=url;r.socket={remoteAddress:'127.0.0.1'};if(body!==undefined)r.body=body;return r;}
process.env.ANOMANCER_WORKSPACE_STORE='memory';process.env.ANOMANCER_MANCER_ARTIFACT_STORE='memory';process.env.ADMIN_SESSION_SECRET='m'.repeat(64);__resetWorkspaceStoreForTests();__resetMancerArtifactStoreForTests();
const templateId='codemancer/development-workbench/1.0.0';
await test('1.18.2 Core lataa Codemancerin Mancer Package -rekisteristä',()=>{assert.equal(CORE_VERSION,'1.18.7');const packages=discoverMancerPackages();assert.equal(packages.length,1);assert.equal(packages[0].manifest.id,'codemancer');assert.equal(packages[0].manifest.format,MANCER_PACKAGE_FORMAT);assert.equal(packages[0].health,'ok');assert.match(packages[0].contractHash,/^[a-f0-9]{64}$/);});
await test('paketti sisältää kaikki kahdeksan domain-sopimusta ja human final authorityn',()=>{const pkg=loadMancerPackage(path.resolve('mancers/codemancer'));assert.equal(pkg.constitution.id,pkg.manifest.constitutionId);assert.equal(pkg.approvalModel.humanFinalAuthority,true);assert.equal(pkg.archivePolicy.automaticModelMemory,false);assert.equal(pkg.artifactBoundary.workspaceIsolation,true);assert.ok(pkg.agentBindings.sharedAgentIds.length>0);assert.equal(pkg.orchestraRegistry.orchestras.length,2);assert.equal(pkg.uiSchema.sections.length,9);});
await test('Workspace Template syntyy paketista ja sisältää Package Spec -sopimukset',()=>{const t=WORKSPACE_TEMPLATE_REGISTRY.find(x=>x.id===templateId);assert.ok(t);assert.equal(t.name,'Codemancer');assert.equal(t.kind,'development');assert.equal(t.editorDefinition.renderer,'schema-workbench');assert.deepEqual(t.editorDefinition.sections.map(x=>x.id),['project','architecture','code','tasks','tests','runs','review','release','documentation']);assert.equal(t.mancerPackage.id,'codemancer');assert.equal(t.mancerPackage.approvalModel.humanFinalAuthority,true);assert.equal(t.mancerPackage.archivePolicy.automaticModelMemory,false);assert.equal(t.mancerPackage.orchestraRegistry.orchestras.length,2);assert.ok(CONSTITUTION_REGISTRY.some(x=>x.id==='codemancer/development-constitution/1.0.0'));});
await test('Codemancer-instanssi syntyy normaalista workspace-storesta ilman uutta store-erikoistapausta',async()=>{const result=await upsertWorkspace({name:'Codemancer Lab',templateId});assert.equal(result.workspace.templateId,templateId);assert.match(result.workspace.templateHash,/^[a-f0-9]{64}$/);assert.match(result.workspace.constitutionHash,/^[a-f0-9]{64}$/);assert.equal(result.workspace.uiProfileId,'mancer/schema-workbench-ui/v1');const loaded=await getWorkspace(result.workspace.id);assert.equal(loaded.id,result.workspace.id);});
await test('Artifact Boundary ei anna Codemancerille Anomancerin sisältöä tai automaattista julkaisua',async()=>{const ws=(await upsertWorkspace({name:'Boundary Lab',templateId})).workspace,b=artifactBoundaryForWorkspace(ws);assert.equal(b.contentReadable,false);assert.equal(b.contentWritable,false);assert.equal(b.publicationEnabled,false);assert.equal(b.isolated,true);assert.ok(b.capabilities.includes('artifact.package.read'));assert.ok(b.capabilities.includes('artifact.package.write'));});
await test('geneerinen Mancer Artifact Store tallentaa package-datan workspace-kohtaisesti ja revision portin takana',async()=>{const ws=(await upsertWorkspace({name:'Artifact Lab',templateId})).workspace;let state=await loadMancerArtifact({workspace:ws});assert.equal(state.packageId,'codemancer');assert.equal(state.revision,0);assert.ok(state.data.project);state=await saveMancerArtifact({...state.data,project:{...state.data.project,name:'TEE Language',goal:'Parser v1'}},{workspace:ws,expectedRevision:0});assert.equal(state.revision,1);assert.equal(state.data.project.name,'TEE Language');await assert.rejects(()=>saveMancerArtifact(state.data,{workspace:ws,expectedRevision:0}),e=>e.code==='MANCER_ARTIFACT_REVISION_CONFLICT');});
await test('Mancer Artifact API on admin+CSRF-suojattu ja workspace-scopattu',async()=>{const ws=(await upsertWorkspace({name:'API Lab',templateId})).workspace;let req=reqMock({headers:{'x-anomancer-workspace':ws.id}}),res=resMock();await mancerArtifactHandler(req,res);assert.equal(res.statusCode,401);const token=signSession(process.env.ADMIN_SESSION_SECRET,{nonce:'mancer-api'}),session=verifySession(process.env.ADMIN_SESSION_SECRET,token),csrf=csrfForSession(process.env.ADMIN_SESSION_SECRET,session),headers={cookie:`anomancer_admin=${encodeURIComponent(token)}`,origin:'https://anomancer.com',host:'anomancer.com','x-forwarded-proto':'https','x-anomancer-workspace':ws.id,'x-csrf-token':csrf};req=reqMock({headers});res=resMock();await mancerArtifactHandler(req,res);assert.equal(res.statusCode,200);let data=JSON.parse(res.body);assert.equal(data.state.packageId,'codemancer');req=reqMock({method:'POST',headers,body:{data:{project:{name:'API project'}},expectedRevision:data.state.revision}});res=resMock();await mancerArtifactHandler(req,res);assert.equal(res.statusCode,200);data=JSON.parse(res.body);assert.equal(data.state.data.project.name,'API project');assert.equal(data.humanFinalAuthority,true);});
await test('package discovery toimii install/remove/reinstall-syklissä ilman Core-muutosta',()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'anomancer-mancers-'));try{assert.equal(discoverMancerPackages({rootDir:temp}).length,0);fs.cpSync('mancers/codemancer',path.join(temp,'codemancer'),{recursive:true});assert.equal(discoverMancerPackages({rootDir:temp})[0].manifest.id,'codemancer');fs.rmSync(path.join(temp,'codemancer'),{recursive:true,force:true});assert.equal(discoverMancerPackages({rootDir:temp}).length,0);fs.cpSync('mancers/codemancer',path.join(temp,'codemancer'),{recursive:true});assert.equal(discoverMancerPackages({rootDir:temp})[0].health,'ok');}finally{fs.rmSync(temp,{recursive:true,force:true});}});
await test('Core Shell ja geneerinen renderer eivät sisällä Codemancer-nimikohtaista navigaatiota',()=>{for(const file of ['admin-shell.js','admin-workspaces.js','admin-mancer.js'])assert.doesNotMatch(fs.readFileSync(file,'utf8'),/codemancer/i,`${file} hardcodes Codemancer`);const shell=fs.readFileSync('admin-shell.js','utf8'),renderer=fs.readFileSync('admin-mancer.js','utf8');assert.match(shell,/anomancer-mancer-package\/v1/);assert.match(renderer,/template\?\.editorDefinition\?\.sections/);assert.match(renderer,/data-mancer-path/);});
await test('build, PWA ja serverless bundle sisältävät geneerisen Mancer runtimen',()=>{const build=fs.readFileSync('scripts/build-blog.mjs','utf8'),sw=fs.readFileSync('lahetyskone-sw.js','utf8'),vercel=JSON.parse(fs.readFileSync('vercel.json','utf8')),html=fs.readFileSync('admin.html','utf8');assert.match(build,/admin-mancer\.js/);assert.match(build,/admin-mancer\.css/);assert.match(sw,/admin-mancer\.js/);assert.match(sw,/admin-mancer\.css/);assert.equal(vercel.functions['api/admin/core.js'].includeFiles,'mancers/**');assert.equal(vercel.functions['api/admin/content.js'].includeFiles,'mancers/**');assert.match(html,/id="mancerWorkspace"/);assert.match(html,/id="mancerRegistryCards"/);});
console.log(`\n${passed}/${passed} MANCER RUNTIME 1.18.4 checks passed.`);
