import { getSession, requireCsrf } from '../_lib/auth.js';
import { json, readJson, sameOrigin } from '../_lib/http.js';
import { listRuns, getRun, finalizeRun, checkpointRun, markRunApplied, runStoreStatus, usageSnapshot } from '../_lib/run-store.js';
import { verifyRuntimeSnapshot } from '../_lib/runtime-store.js';
function auth(req,res,mut=false){const s=getSession(req);if(!s){json(res,401,{ok:false,error:'AUTH'});return null;}if(mut&&(!sameOrigin(req)||!requireCsrf(req,s))){json(res,403,{ok:false,error:'CSRF'});return null;}return s;}
export default async function handler(req,res){
  if(req.method==='GET'){if(!auth(req,res))return;try{const url=new URL(req.url||'/api/admin/runs','http://local');const id=String(url.searchParams.get('id')||'');if(id){const run=await getRun(id);return run?json(res,200,{ok:true,run,store:runStoreStatus()}):json(res,404,{ok:false,error:'RUN_NOT_FOUND'});}const data=await listRuns({limit:url.searchParams.get('limit'),status:url.searchParams.get('status')||'',agent:url.searchParams.get('agent')||'',provider:url.searchParams.get('provider')||'',orchestra:url.searchParams.get('orchestra')||''});return json(res,200,{ok:true,...data});}catch(e){return json(res,e.statusCode||500,{ok:false,error:e.code||'RUN_STORE',message:e.message,store:runStoreStatus()});}}
  if(req.method==='POST'){if(!auth(req,res,true))return;try{const body=await readJson(req,120_000),action=String(body.action||'');if(action==='usage')return json(res,200,{ok:true,usage:await usageSnapshot(),store:runStoreStatus()});if(!body.orchestraRunId||!body.runtimeSnapshotToken)return json(res,409,{ok:false,error:'RUN_SNAPSHOT_REQUIRED'});const snap=verifyRuntimeSnapshot(body.runtimeSnapshotToken,{orchestraRunId:String(body.orchestraRunId)});if(action==='checkpoint'){const run=await checkpointRun(body.orchestraRunId,{status:body.status,startedAt:body.startedAt,degradedStages:body.degradedStages,disabledStages:body.disabledStages,error:body.error,orchestra:snap.orchestra});return json(res,200,{ok:true,run});}if(action==='finalize'){const run=await finalizeRun(body.orchestraRunId,{status:body.status,finishedAt:body.finishedAt,degradedStages:body.degradedStages,disabledStages:body.disabledStages,error:body.error,orchestra:snap.orchestra});return json(res,200,{ok:true,run});}if(action==='applied'){const run=await markRunApplied(body.orchestraRunId);return json(res,200,{ok:true,run});}return json(res,400,{ok:false,error:'RUN_ACTION'});}catch(e){return json(res,e.statusCode||500,{ok:false,error:e.code||'RUN_ACTION',message:e.message});}}
  return json(res,405,{ok:false,error:'METHOD'});
}
