import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import fs from 'node:fs';
import path from 'node:path';
import { hashPassword, verifyPassword, signSession, verifySession, csrfForSession, sessionCookie } from '../../server/auth.js';
import { serializePost, parseMarkdown, newPostPath, normalizeCategory, normalizeAudience, normalizeAudienceDepth } from '../../server/content.js';
import { putFile, putBase64File, deleteFile } from '../../server/content-store.js';
import loginHandler from '../../server/admin-routes/login.js';
import sessionHandler from '../../server/admin-routes/session.js';
import postsHandler from '../../server/admin-routes/posts.js';
import mediaHandler from '../../server/admin-routes/media.js';
import publicDispatchesHandler from '../../api/public/dispatches.js';
const ROOT=process.cwd();
let ok=0; const test=async(name,fn)=>{await fn();ok++;console.log(`✓ ${name}`)};
function resMock(){return {statusCode:200,headers:{},body:'',setHeader(k,v){this.headers[k.toLowerCase()]=v},end(v=''){this.body+=v}};}
function reqMock({method='GET',url='/',body,headers={}}={}){const r=new EventEmitter();r.method=method;r.url=url;r.headers=headers;if(body!==undefined)r.body=body;return r;}
await test('scrypt hash hyväksyy oikean salasanan',()=>{const h=hashPassword('erittain-pitka-testi-salasana',{salt:'00112233445566778899aabbccddeeff'});assert.equal(verifyPassword('erittain-pitka-testi-salasana',h),true);assert.equal(verifyPassword('väärä salasana',h),false)});
await test('session allekirjoitetaan ja vanhenee',()=>{const secret='x'.repeat(64);const t=signSession(secret,{now:1_000_000,ttlSeconds:60,nonce:'abc'});assert.equal(verifySession(secret,t,{now:1_030_000}).nonce,'abc');assert.equal(verifySession(secret,t,{now:1_061_000}),null)});
await test('CSRF sitoutuu sessioon',()=>{const secret='y'.repeat(64);assert.notEqual(csrfForSession(secret,{nonce:'a'}),csrfForSession(secret,{nonce:'b'}))});
await test('local cookie ei pakota Securea, Vercel-cookie pakottaa',()=>{delete process.env.VERCEL_ENV;delete process.env.NODE_ENV;assert.doesNotMatch(sessionCookie('x'),/Secure/);process.env.VERCEL_ENV='production';assert.match(sessionCookie('x'),/Secure/);delete process.env.VERCEL_ENV});
await test('Markdown roundtrip säilyttää aiheen, yleisön, syvyyden ja kansikuvan',()=>{const p={lang:'fi',title:'Agentin passi',date:'2026-08-26',category:'software-safety',audience:['developer','entrepreneur'],audienceDepth:'professional',description:'Testikuvaus',slug:'agentin-passi',translationKey:'agent-pass',coverImage:'/media/2026/08/agentti.webp',coverAlt:'Agenttipassin rakenne',pinned:true,draft:false,body:'## Otsikko\n\nTeksti.'};const raw=serializePost(p);const q=parseMarkdown(raw);assert.equal(q.title,p.title);assert.equal(q.category,p.category);assert.deepEqual(q.audience,p.audience);assert.equal(q.audienceDepth,'professional');assert.equal(q.draft,false);assert.equal(q.coverImage,p.coverImage);assert.equal(q.coverAlt,p.coverAlt);assert.equal(q.pinned,true);assert.match(q.body,/Teksti/);assert.equal(newPostPath(p),'content/fi/20260826-agentin-passi.md')});
await test('vanhat kategoriat ja audience depth normalisoituvat',()=>{assert.equal(normalizeCategory('build'),'software-safety');assert.equal(normalizeCategory('field'),'info-media');assert.deepEqual(normalizeAudience(undefined),['all']);assert.deepEqual(normalizeAudience(['teacher','teacher','investor']),['teacher','investor']);assert.deepEqual(normalizeAudience(['all','teacher']),['all']);assert.equal(normalizeAudienceDepth('technical'),'technical');assert.equal(normalizeAudienceDepth('wat'),'general')});
await test('paikallinen sisältösäilö kirjoittaa ja tarkistaa revision',async()=>{process.env.ANOMANCER_CONTENT_STORE='local';const rel='content/fi/__store-test.md';try{const r=await putFile(rel,'hello',{message:'m'});assert.match(r.sha,/^[a-f0-9]{64}$/);await assert.rejects(()=>putFile(rel,'changed',{sha:'wrong'}),error=>error.code==='CONTENT_REVISION_CONFLICT');await deleteFile(rel,r.sha);}finally{try{fs.rmSync(path.join(ROOT,rel),{force:true})}catch{}}});
await test('paikallinen mediasäilö käyttää upload-rajaa',async()=>{process.env.ANOMANCER_CONTENT_STORE='local';const rel='media/uploads/2026/08/__store-test.webp';try{const r=await putBase64File(rel,'UklGRg==',{contentType:'image/webp',message:'media'});assert.match(r.commitSha,/^[a-f0-9]{64}$/);assert.equal(fs.existsSync(path.join(ROOT,rel)),true);}finally{try{fs.rmSync(path.join(ROOT,rel),{force:true})}catch{}}});

await test('login väärällä salasanalla pysähtyy 401',async()=>{process.env.ADMIN_PASSWORD_HASH=hashPassword('oikea-superpitka-salasana',{salt:'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'});process.env.ADMIN_SESSION_SECRET='s'.repeat(64);const req=reqMock({method:'POST',body:{password:'väärä-superpitkä'},headers:{origin:'https://anomancer.com',host:'anomancer.com','x-forwarded-proto':'https'}});const res=resMock();await loginHandler(req,res);assert.equal(res.statusCode,401)});
await test('login oikealla salasanalla antaa HttpOnly-session',async()=>{process.env.ADMIN_PASSWORD_HASH=hashPassword('oikea-superpitka-salasana',{salt:'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'});process.env.ADMIN_SESSION_SECRET='s'.repeat(64);process.env.VERCEL_ENV='production';const req=reqMock({method:'POST',body:{password:'oikea-superpitka-salasana'},headers:{origin:'https://anomancer.com',host:'anomancer.com','x-forwarded-proto':'https'}});const res=resMock();await loginHandler(req,res);assert.equal(res.statusCode,200);assert.match(String(res.headers['set-cookie']),/HttpOnly/);assert.match(String(res.headers['set-cookie']),/Secure/);delete process.env.VERCEL_ENV});
await test('session endpoint palauttaa CSRF:n validille cookielle',async()=>{process.env.ADMIN_SESSION_SECRET='q'.repeat(64);const token=signSession(process.env.ADMIN_SESSION_SECRET);const req=reqMock({headers:{cookie:`anomancer_admin=${encodeURIComponent(token)}`}});const res=resMock();await sessionHandler(req,res);const data=JSON.parse(res.body);assert.equal(data.authenticated,true);assert.ok(data.csrf)});
await test('posts endpoint estää kirjautumattoman',async()=>{const req=reqMock({method:'GET'});const res=resMock();await postsHandler(req,res);assert.equal(res.statusCode,401)});
await test('posts POST vaatii CSRF:n',async()=>{process.env.ADMIN_SESSION_SECRET='w'.repeat(64);const token=signSession(process.env.ADMIN_SESSION_SECRET);const req=reqMock({method:'POST',body:{},headers:{cookie:`anomancer_admin=${encodeURIComponent(token)}`,origin:'https://anomancer.com',host:'anomancer.com','x-forwarded-proto':'https'}});const res=resMock();await postsHandler(req,res);assert.equal(res.statusCode,403)});
await test('media POST hyväksyy pienen PNG-kuvan validilla sessiolla',async()=>{process.env.ADMIN_SESSION_SECRET='m'.repeat(64);process.env.ANOMANCER_CONTENT_STORE='local';const token=signSession(process.env.ADMIN_SESSION_SECRET,{nonce:'media-test'});const sess=verifySession(process.env.ADMIN_SESSION_SECRET,token);const csrf=csrfForSession(process.env.ADMIN_SESSION_SECRET,sess);const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9WlF2r0AAAAASUVORK5CYII=';const req=reqMock({method:'POST',body:{data:`data:image/png;base64,${png}`,name:'koe.png',date:'2026-08-26'},headers:{cookie:`anomancer_admin=${encodeURIComponent(token)}`,origin:'https://anomancer.com',host:'anomancer.com','x-forwarded-proto':'https','x-csrf-token':csrf}});const res=resMock();await mediaHandler(req,res);assert.equal(res.statusCode,200);const data=JSON.parse(res.body);assert.match(data.url,/^\/media\/uploads\/2026\/08\/koe-[a-f0-9]{8}\.png$/);try{fs.rmSync(path.join(ROOT,data.path),{force:true})}catch{}});

await test('julkaisu varmistetaan sisältösäilöstä ja näkyy heti julkisessa reitissä',async()=>{process.env.ADMIN_SESSION_SECRET='p'.repeat(64);process.env.ANOMANCER_CONTENT_STORE='local';const stamp=Date.now().toString(36),post={lang:'fi',title:`Julkaisuputken testi ${stamp}`,date:'2026-09-02',category:'info-media',audience:['all'],audienceDepth:'general',description:'Itsenäinen testijulkaisu varmistaa tallennuksen ja julkisen reitin ilman riippuvuutta käyttäjän aineistosta.',slug:`julkaisuputken-testi-${stamp}`,translationKey:`julkaisuputken-testi-${stamp}`,aliases:[],coverImage:'',coverAlt:'',answer:'',sources:[],claims:[],citationMode:'inline',citationPlacements:[],visualizations:[],pinned:false,draft:false,body:'## Julkaisuputken testi\n\nTämä teksti varmistaa tallennuksen ja julkisen takaisinluvun.'};const token=signSession(process.env.ADMIN_SESSION_SECRET,{nonce:`publish-${stamp}`}),session=verifySession(process.env.ADMIN_SESSION_SECRET,token),csrf=csrfForSession(process.env.ADMIN_SESSION_SECRET,session),headers={cookie:`anomancer_admin=${encodeURIComponent(token)}`,origin:'https://anomancer.com',host:'anomancer.com','x-forwarded-proto':'https','x-anomancer-workspace':'default','x-csrf-token':csrf};let saved;try{let req=reqMock({method:'POST',url:'/api/admin/content?resource=posts',headers,body:{post}}),res=resMock();await postsHandler(req,res);assert.equal(res.statusCode,200,res.body);saved=JSON.parse(res.body);assert.equal(saved.persisted,true);assert.equal(saved.published,true);assert.equal(saved.publicPath,`/lahetykset/${post.slug}`);req=reqMock({method:'POST',url:'/api/admin/content?resource=posts',headers,body:{post:{...post,date:'2099-12-31'}}});res=resMock();await postsHandler(req,res);assert.equal(res.statusCode,409);assert.equal(JSON.parse(res.body).error,'PUBLIC_ROUTE_CONFLICT');req=reqMock({method:'GET',url:`/api/public/dispatches?lang=fi&slug=${post.slug}`});res=resMock();await publicDispatchesHandler(req,res);assert.equal(res.statusCode,200,res.body);assert.match(res.body,new RegExp(post.title));assert.equal(res.headers['vercel-cdn-cache-control'],'no-store');assert.match(res.headers['cache-control'],/max-age=0/);}finally{if(saved?.path)try{await deleteFile(saved.path,saved.sha)}catch{try{fs.rmSync(path.join(ROOT,saved.path),{force:true})}catch{}}}});

await test('uusi tallentamaton luonnos saa istuntokohtaisen identiteetin',()=>{const js=fs.readFileSync(path.join(ROOT,'admin.js'),'utf8');assert.match(js,/draftInstanceId/);assert.match(js,/instanceId:state\.current\?\.path\?'':state\.draftInstanceId/);});
await test('Audience Contract tallentuu editorissa ja lukitsee syvyystason orkesterin ajaksi',()=>{const html=fs.readFileSync(path.join(ROOT,'admin.html'),'utf8');const js=fs.readFileSync(path.join(ROOT,'admin.js'),'utf8');assert.match(html,/id="audienceDepth"/);assert.match(html,/Yleisöadapteri/);assert.match(js,/audienceDepth/);assert.match(js,/#audienceDepth/);});
await test('kylmäkäynnistys näyttää aikakatkaistun virheen ja uudelleenyrityksen',()=>{const html=fs.readFileSync(path.join(ROOT,'admin.html'),'utf8');const js=fs.readFileSync(path.join(ROOT,'admin.js'),'utf8');assert.match(html,/id="bootView"/);assert.match(html,/id="bootStatus"/);assert.match(html,/id="bootRetry"/);assert.match(js,/AbortSignal\.timeout\(10_000\)/);assert.match(js,/session\(\{boot:true\}\)/);assert.match(js,/bootRetry\.onclick/);});
await test('lähteen tarkistus on yksi vahvistus ilman kirjoitettavaa selvitystä',()=>{const js=fs.readFileSync(path.join(ROOT,'admin.js'),'utf8');assert.match(js,/Merkitse lähde tarkistetuksi/);assert.match(js,/Erillistä selvitystä ei tarvitse kirjoittaa/);assert.doesNotMatch(js,/label:'Mitä tarkistit\?'/);assert.match(js,/source\.verificationMethod='direct-open'/);assert.match(js,/source\.verificationEvidence=source\.url/);assert.match(js,/source\.verifiedBy='human:admin'/);assert.match(js,/new Date\(\)\.toISOString\(\)/);});
console.log(`\n${ok}/${ok} admin-testiä läpi`);
