import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { hashPassword, verifyPassword, signSession, verifySession, csrfForSession, sessionCookie } from '../api/_lib/auth.js';
import { serializePost, parseMarkdown, newPostPath } from '../api/_lib/content.js';
import { putFile, deleteFile } from '../api/_lib/github.js';
import loginHandler from '../api/admin/login.js';
import sessionHandler from '../api/admin/session.js';
import postsHandler from '../api/admin/posts.js';
let ok=0; const test=async(name,fn)=>{await fn();ok++;console.log(`✓ ${name}`)};
function resMock(){return {statusCode:200,headers:{},body:'',setHeader(k,v){this.headers[k.toLowerCase()]=v},end(v=''){this.body+=v}};}
function reqMock({method='GET',body,headers={}}={}){const r=new EventEmitter();r.method=method;r.headers=headers;if(body!==undefined)r.body=body;return r;}
await test('scrypt hash hyväksyy oikean salasanan',()=>{const h=hashPassword('erittain-pitka-testi-salasana',{salt:'00112233445566778899aabbccddeeff'});assert.equal(verifyPassword('erittain-pitka-testi-salasana',h),true);assert.equal(verifyPassword('väärä salasana',h),false)});
await test('session allekirjoitetaan ja vanhenee',()=>{const secret='x'.repeat(64);const t=signSession(secret,{now:1_000_000,ttlSeconds:60,nonce:'abc'});assert.equal(verifySession(secret,t,{now:1_030_000}).nonce,'abc');assert.equal(verifySession(secret,t,{now:1_061_000}),null)});
await test('CSRF sitoutuu sessioon',()=>{const secret='y'.repeat(64);assert.notEqual(csrfForSession(secret,{nonce:'a'}),csrfForSession(secret,{nonce:'b'}))});
await test('local cookie ei pakota Securea, Vercel-cookie pakottaa',()=>{delete process.env.VERCEL_ENV;delete process.env.NODE_ENV;assert.doesNotMatch(sessionCookie('x'),/Secure/);process.env.VERCEL_ENV='production';assert.match(sessionCookie('x'),/Secure/);delete process.env.VERCEL_ENV});
await test('Markdown roundtrip säilyttää sisällön',()=>{const p={lang:'fi',title:'Agentin passi',date:'2026-08-26',category:'ai-agents',description:'Testikuvaus',slug:'agentin-passi',translationKey:'agent-pass',draft:false,body:'## Otsikko\n\nTeksti.'};const raw=serializePost(p);const q=parseMarkdown(raw);assert.equal(q.title,p.title);assert.equal(q.draft,false);assert.match(q.body,/Teksti/);assert.equal(newPostPath(p),'content/fi/20260826-agentin-passi.md')});
await test('GitHub PUT ei vuoda tokenia bodyyn',async()=>{process.env.GITHUB_CONTENT_TOKEN='secret-token';process.env.GITHUB_REPO='owner/repo';process.env.GITHUB_BRANCH='main';const old=global.fetch;let seen;global.fetch=async(url,opts)=>{seen={url,opts};return new Response(JSON.stringify({content:{sha:'newsha',html_url:'x'},commit:{sha:'commit'}}),{status:200})};try{const r=await putFile('content/fi/a.md','hello',{message:'m'});assert.equal(r.sha,'newsha');assert.match(seen.opts.headers.Authorization,/secret-token/);assert.doesNotMatch(seen.opts.body,/secret-token/);assert.match(seen.url,/owner\/repo\/contents\/content\/fi\/a.md/)}finally{global.fetch=old}});
await test('GitHub DELETE käyttää SHA:ta',async()=>{process.env.GITHUB_CONTENT_TOKEN='secret-token';process.env.GITHUB_REPO='owner/repo';const old=global.fetch;let body;global.fetch=async(url,opts)=>{body=JSON.parse(opts.body);return new Response(JSON.stringify({commit:{sha:'gone'}}),{status:200})};try{await deleteFile('content/fi/a.md','abc');assert.equal(body.sha,'abc')}finally{global.fetch=old}});
await test('login väärällä salasanalla pysähtyy 401',async()=>{process.env.ADMIN_PASSWORD_HASH=hashPassword('oikea-superpitka-salasana',{salt:'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'});process.env.ADMIN_SESSION_SECRET='s'.repeat(64);const req=reqMock({method:'POST',body:{password:'väärä-superpitkä'},headers:{origin:'https://anomancer.vercel.app',host:'anomancer.vercel.app','x-forwarded-proto':'https'}});const res=resMock();await loginHandler(req,res);assert.equal(res.statusCode,401)});
await test('login oikealla salasanalla antaa HttpOnly-session',async()=>{process.env.ADMIN_PASSWORD_HASH=hashPassword('oikea-superpitka-salasana',{salt:'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'});process.env.ADMIN_SESSION_SECRET='s'.repeat(64);process.env.VERCEL_ENV='production';const req=reqMock({method:'POST',body:{password:'oikea-superpitka-salasana'},headers:{origin:'https://anomancer.vercel.app',host:'anomancer.vercel.app','x-forwarded-proto':'https'}});const res=resMock();await loginHandler(req,res);assert.equal(res.statusCode,200);assert.match(String(res.headers['set-cookie']),/HttpOnly/);assert.match(String(res.headers['set-cookie']),/Secure/);delete process.env.VERCEL_ENV});
await test('session endpoint palauttaa CSRF:n validille cookielle',async()=>{process.env.ADMIN_SESSION_SECRET='q'.repeat(64);const token=signSession(process.env.ADMIN_SESSION_SECRET);const req=reqMock({headers:{cookie:`anomancer_admin=${encodeURIComponent(token)}`}});const res=resMock();await sessionHandler(req,res);const data=JSON.parse(res.body);assert.equal(data.authenticated,true);assert.ok(data.csrf)});
await test('posts endpoint estää kirjautumattoman',async()=>{const req=reqMock({method:'GET'});const res=resMock();await postsHandler(req,res);assert.equal(res.statusCode,401)});
await test('posts POST vaatii CSRF:n',async()=>{process.env.ADMIN_SESSION_SECRET='w'.repeat(64);const token=signSession(process.env.ADMIN_SESSION_SECRET);const req=reqMock({method:'POST',body:{},headers:{cookie:`anomancer_admin=${encodeURIComponent(token)}`,origin:'https://anomancer.vercel.app',host:'anomancer.vercel.app','x-forwarded-proto':'https'}});const res=resMock();await postsHandler(req,res);assert.equal(res.statusCode,403)});
console.log(`\n${ok}/${ok} admin-testiä läpi`);
