import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import fs from 'node:fs';
import path from 'node:path';
import { hashPassword, verifyPassword, signSession, verifySession, csrfForSession, sessionCookie } from '../server/auth.js';
import { serializePost, parseMarkdown, newPostPath, normalizeCategory, normalizeAudience, normalizeAudienceDepth } from '../server/content.js';
import { putFile, putBase64File, deleteFile } from '../server/github.js';
import loginHandler from '../api/admin/login.js';
import sessionHandler from '../api/admin/session.js';
import postsHandler from '../api/admin/posts.js';
import mediaHandler from '../api/admin/media.js';
const ROOT=process.cwd();
let ok=0; const test=async(name,fn)=>{await fn();ok++;console.log(`✓ ${name}`)};
function resMock(){return {statusCode:200,headers:{},body:'',setHeader(k,v){this.headers[k.toLowerCase()]=v},end(v=''){this.body+=v}};}
function reqMock({method='GET',body,headers={}}={}){const r=new EventEmitter();r.method=method;r.headers=headers;if(body!==undefined)r.body=body;return r;}
await test('scrypt hash hyväksyy oikean salasanan',()=>{const h=hashPassword('erittain-pitka-testi-salasana',{salt:'00112233445566778899aabbccddeeff'});assert.equal(verifyPassword('erittain-pitka-testi-salasana',h),true);assert.equal(verifyPassword('väärä salasana',h),false)});
await test('session allekirjoitetaan ja vanhenee',()=>{const secret='x'.repeat(64);const t=signSession(secret,{now:1_000_000,ttlSeconds:60,nonce:'abc'});assert.equal(verifySession(secret,t,{now:1_030_000}).nonce,'abc');assert.equal(verifySession(secret,t,{now:1_061_000}),null)});
await test('CSRF sitoutuu sessioon',()=>{const secret='y'.repeat(64);assert.notEqual(csrfForSession(secret,{nonce:'a'}),csrfForSession(secret,{nonce:'b'}))});
await test('local cookie ei pakota Securea, Vercel-cookie pakottaa',()=>{delete process.env.VERCEL_ENV;delete process.env.NODE_ENV;assert.doesNotMatch(sessionCookie('x'),/Secure/);process.env.VERCEL_ENV='production';assert.match(sessionCookie('x'),/Secure/);delete process.env.VERCEL_ENV});
await test('Markdown roundtrip säilyttää aiheen, yleisön, syvyyden ja kansikuvan',()=>{const p={lang:'fi',title:'Agentin passi',date:'2026-08-26',category:'software-safety',audience:['developer','entrepreneur'],audienceDepth:'professional',description:'Testikuvaus',slug:'agentin-passi',translationKey:'agent-pass',coverImage:'/media/2026/08/agentti.webp',coverAlt:'Agenttipassin rakenne',pinned:true,draft:false,body:'## Otsikko\n\nTeksti.'};const raw=serializePost(p);const q=parseMarkdown(raw);assert.equal(q.title,p.title);assert.equal(q.category,p.category);assert.deepEqual(q.audience,p.audience);assert.equal(q.audienceDepth,'professional');assert.equal(q.draft,false);assert.equal(q.coverImage,p.coverImage);assert.equal(q.coverAlt,p.coverAlt);assert.equal(q.pinned,true);assert.match(q.body,/Teksti/);assert.equal(newPostPath(p),'content/fi/20260826-agentin-passi.md')});
await test('vanhat kategoriat ja audience depth normalisoituvat',()=>{assert.equal(normalizeCategory('build'),'software-safety');assert.equal(normalizeCategory('field'),'info-media');assert.deepEqual(normalizeAudience(undefined),['all']);assert.deepEqual(normalizeAudience(['teacher','teacher','investor']),['teacher','investor']);assert.deepEqual(normalizeAudience(['all','teacher']),['all']);assert.equal(normalizeAudienceDepth('technical'),'technical');assert.equal(normalizeAudienceDepth('wat'),'general')});
await test('GitHub PUT ei vuoda tokenia bodyyn',async()=>{process.env.GITHUB_CONTENT_TOKEN='secret-token';process.env.GITHUB_REPO='owner/repo';process.env.GITHUB_BRANCH='main';const old=global.fetch;let seen;global.fetch=async(url,opts)=>{seen={url,opts};return new Response(JSON.stringify({content:{sha:'newsha',html_url:'x'},commit:{sha:'commit'}}),{status:200})};try{const r=await putFile('content/fi/a.md','hello',{message:'m'});assert.equal(r.sha,'newsha');assert.match(seen.opts.headers.Authorization,/secret-token/);assert.doesNotMatch(seen.opts.body,/secret-token/);assert.match(seen.url,/owner\/repo\/contents\/content\/fi\/a.md/)}finally{global.fetch=old}});
await test('GitHub DELETE käyttää SHA:ta',async()=>{process.env.GITHUB_CONTENT_TOKEN='secret-token';process.env.GITHUB_REPO='owner/repo';const old=global.fetch;let body;global.fetch=async(url,opts)=>{body=JSON.parse(opts.body);return new Response(JSON.stringify({commit:{sha:'gone'}}),{status:200})};try{await deleteFile('content/fi/a.md','abc');assert.equal(body.sha,'abc')}finally{global.fetch=old}});
await test('GitHub media PUT käyttää valmista base64-dataa',async()=>{process.env.GITHUB_CONTENT_TOKEN='secret-token';process.env.GITHUB_REPO='owner/repo';process.env.GITHUB_BRANCH='master';const old=global.fetch;let body,url;global.fetch=async(u,opts)=>{url=u;body=JSON.parse(opts.body);return new Response(JSON.stringify({content:{sha:'imgsha',html_url:'x'},commit:{sha:'imgcommit'}}),{status:200})};try{const r=await putBase64File('media/2026/08/test.webp','UklGRg==',{message:'media'});assert.equal(body.content,'UklGRg==');assert.equal(body.branch,'master');assert.match(url,/media\/2026\/08\/test.webp/);assert.equal(r.commitSha,'imgcommit')}finally{global.fetch=old}});

await test('login väärällä salasanalla pysähtyy 401',async()=>{process.env.ADMIN_PASSWORD_HASH=hashPassword('oikea-superpitka-salasana',{salt:'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'});process.env.ADMIN_SESSION_SECRET='s'.repeat(64);const req=reqMock({method:'POST',body:{password:'väärä-superpitkä'},headers:{origin:'https://anomancer.com',host:'anomancer.com','x-forwarded-proto':'https'}});const res=resMock();await loginHandler(req,res);assert.equal(res.statusCode,401)});
await test('login oikealla salasanalla antaa HttpOnly-session',async()=>{process.env.ADMIN_PASSWORD_HASH=hashPassword('oikea-superpitka-salasana',{salt:'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'});process.env.ADMIN_SESSION_SECRET='s'.repeat(64);process.env.VERCEL_ENV='production';const req=reqMock({method:'POST',body:{password:'oikea-superpitka-salasana'},headers:{origin:'https://anomancer.com',host:'anomancer.com','x-forwarded-proto':'https'}});const res=resMock();await loginHandler(req,res);assert.equal(res.statusCode,200);assert.match(String(res.headers['set-cookie']),/HttpOnly/);assert.match(String(res.headers['set-cookie']),/Secure/);delete process.env.VERCEL_ENV});
await test('session endpoint palauttaa CSRF:n validille cookielle',async()=>{process.env.ADMIN_SESSION_SECRET='q'.repeat(64);const token=signSession(process.env.ADMIN_SESSION_SECRET);const req=reqMock({headers:{cookie:`anomancer_admin=${encodeURIComponent(token)}`}});const res=resMock();await sessionHandler(req,res);const data=JSON.parse(res.body);assert.equal(data.authenticated,true);assert.ok(data.csrf)});
await test('posts endpoint estää kirjautumattoman',async()=>{const req=reqMock({method:'GET'});const res=resMock();await postsHandler(req,res);assert.equal(res.statusCode,401)});
await test('posts POST vaatii CSRF:n',async()=>{process.env.ADMIN_SESSION_SECRET='w'.repeat(64);const token=signSession(process.env.ADMIN_SESSION_SECRET);const req=reqMock({method:'POST',body:{},headers:{cookie:`anomancer_admin=${encodeURIComponent(token)}`,origin:'https://anomancer.com',host:'anomancer.com','x-forwarded-proto':'https'}});const res=resMock();await postsHandler(req,res);assert.equal(res.statusCode,403)});
await test('media POST hyväksyy pienen PNG-kuvan validilla sessiolla',async()=>{process.env.ADMIN_SESSION_SECRET='m'.repeat(64);process.env.GITHUB_CONTENT_TOKEN='secret-token';process.env.GITHUB_REPO='owner/repo';process.env.GITHUB_BRANCH='master';const token=signSession(process.env.ADMIN_SESSION_SECRET,{nonce:'media-test'});const sess=verifySession(process.env.ADMIN_SESSION_SECRET,token);const csrf=csrfForSession(process.env.ADMIN_SESSION_SECRET,sess);const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9WlF2r0AAAAASUVORK5CYII=';const old=global.fetch;global.fetch=async()=>new Response(JSON.stringify({content:{sha:'imgsha',html_url:'x'},commit:{sha:'imgcommit'}}),{status:200});try{const req=reqMock({method:'POST',body:{data:`data:image/png;base64,${png}`,name:'koe.png',date:'2026-08-26'},headers:{cookie:`anomancer_admin=${encodeURIComponent(token)}`,origin:'https://anomancer.com',host:'anomancer.com','x-forwarded-proto':'https','x-csrf-token':csrf}});const res=resMock();await mediaHandler(req,res);assert.equal(res.statusCode,200);const data=JSON.parse(res.body);assert.match(data.url,/^\/media\/2026\/08\/koe-[a-f0-9]{8}\.png$/)}finally{global.fetch=old}});

await test('uusi tallentamaton luonnos saa istuntokohtaisen identiteetin',()=>{const js=fs.readFileSync(path.join(ROOT,'admin.js'),'utf8');assert.match(js,/draftInstanceId/);assert.match(js,/instanceId:state\.current\?\.path\?'':state\.draftInstanceId/);});
await test('Audience Contract tallentuu editorissa ja lukitsee syvyystason orkesterin ajaksi',()=>{const html=fs.readFileSync(path.join(ROOT,'admin.html'),'utf8');const js=fs.readFileSync(path.join(ROOT,'admin.js'),'utf8');assert.match(html,/id="audienceDepth"/);assert.match(html,/Yleisöadapteri/);assert.match(js,/audienceDepth/);assert.match(js,/#audienceDepth/);});
await test('agenttilähteen tarkistetuksi merkintä vaatii ihmisen vahvistuksen',()=>{const js=fs.readFileSync(path.join(ROOT,'admin.js'),'utf8');assert.match(js,/Merkitäänkö .* tarkistetuksi/);assert.match(js,/olet avannut lähteen/);});
console.log(`\n${ok}/${ok} admin-testiä läpi`);
